Repository openshift/cluster-kube-apiserver-operator, pull requests merged in 2018-10, with the labels that each got.

#35 parametrize lock host dir
  bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml
  cmd/cluster-kube-apiserver-operator/render/config.go
  cmd/cluster-kube-apiserver-operator/render/render.go
Labels: approved, lgtm, size/S

#36 fix lock path in daemonset
  bindata/bootkube/manifests/kube-apiserver-daemonset.yaml
Labels: approved, lgtm, size/XS

#34 update manifest filenames to conform to expected CVO update payload format
  manifests/0000_10_cluster-kube-apiserver-operator_00_namespace.yaml
  manifests/0000_10_cluster-kube-apiserver-operator_01_config.crd.yaml
  manifests/0000_10_cluster-kube-apiserver-operator_02_config.yaml
  manifests/0000_10_cluster-kube-apiserver-operator_03_configmap.yaml
  manifests/0000_10_cluster-kube-apiserver-operator_04_clusterrolebinding.yaml
  manifests/0000_10_cluster-kube-apiserver-operator_05_serviceaccount.yaml
  manifests/0000_10_cluster-kube-apiserver-operator_06_deployment.yaml
Labels: approved, lgtm, size/XS

#37 Add soltysh to reviewers
  OWNERS
Labels: approved, lgtm, size/XS

#39 make bootstrap apiserver privileged to work around selinux
  bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml
Labels: approved, lgtm, size/XS

#41 use explicit lock path
  bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml
Labels: approved, lgtm, size/XS

#38 add imagePullPolicy to initContainer
  bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml
Labels: approved, lgtm, size/XS

#44 switch kube-apiserver port to 6443
  bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml
  bindata/v3.11.0/kube-apiserver/defaultconfig.yaml
  bindata/v3.11.0/kube-apiserver/deployment.yaml
  bindata/v3.11.0/kube-apiserver/svc.yaml
  manifests/0000_10_cluster-kube-apiserver-operator_06_deployment.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/S

#43 only run on master nodes
  bindata/v3.11.0/kube-apiserver/deployment.yaml
  manifests/0000_10_cluster-kube-apiserver-operator_06_deployment.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/S

#45 tolerate any taint
  bindata/v3.11.0/kube-apiserver/deployment.yaml
  manifests/0000_10_cluster-kube-apiserver-operator_06_deployment.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#46 remove operator config from payload
  bindata/v3.11.0/kube-apiserver/operator-config.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/M

#42 Add basic yaml linting test
  pkg/test/assets_test.go
Labels: approved, lgtm, size/M

#48 ensure operator config exists on start
  pkg/operator/starter.go
Labels: approved, lgtm, size/M

#52 Make sure the namespace is created first
  bindata/bootkube/manifests/00_openshift-kube-apiserver-ns.yaml
Labels: approved, lgtm, size/XS

#54 bump to latest library-go
  glide.lock
  pkg/operator/operator.go
  pkg/operator/sync_kubeapiserver_v311_00.go
  vendor/github.com/openshift/api/authorization/OWNERS
  vendor/github.com/openshift/api/oauth/OWNERS
  vendor/github.com/openshift/api/operator/v1alpha1/types.go
  vendor/github.com/openshift/api/operator/v1alpha1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/security/OWNERS
  vendor/github.com/openshift/api/user/OWNERS
  vendor/github.com/openshift/library-go/glide.lock
  vendor/github.com/openshift/library-go/pkg/config/configdefaults/config_default.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/apps.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1helpers/helper_test.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1helpers/helpers.go
Labels: approved, lgtm, size/L

#55 observe etcd urls from endpoint
  pkg/operator/observe_config.go
  pkg/operator/operator.go
  pkg/operator/starter.go
Labels: approved, lgtm, size/L

#56 render: make etcd-serving-ca customizable
  bindata/bootkube/manifests/configmap-etcd-serving-ca.yaml
  cmd/cluster-kube-apiserver-operator/render/config.go
  cmd/cluster-kube-apiserver-operator/render/render.go
Labels: approved, lgtm, size/S

#57 render: use custom etcd-serving-ca also in bootstrap config overrides
  bindata/bootkube/config/bootstrap-config-overrides.yaml
  bindata/bootkube/config/config-overrides.yaml
Labels: approved, lgtm, size/XS

#58 read etcd endpoint information
  pkg/operator/observe_config.go
  pkg/operator/starter.go
Labels: approved, lgtm, size/S

#59 use correct slice setting func
  pkg/operator/observe_config.go
Labels: approved, lgtm, size/XS

#60 render: add var-lock init container also to phase 2
  bindata/bootkube/manifests/kube-apiserver-daemonset.yaml
Labels: approved, lgtm, size/S

#61 remove etcd service
  bindata/bootkube/manifests/etcd-service.yaml
Labels: approved, lgtm, size/S

#49 remove extra namespace manifest
  bindata/v3.11.0/kube-apiserver/openshift-kube-apiserver-ns.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/M

#64 Makefile: add origin-release target
  Dockerfile-origin-release
  Makefile
Labels: approved, lgtm, size/S

#66 render: remove --config-override-file default
  cmd/cluster-kube-apiserver-operator/render/render.go
Labels: approved, lgtm, size/XS

#65 manifests: fix image name
  manifests/image-references
Labels: approved, lgtm, size/XS

#67 Allow to specify image pull policy via operator API
  glide.lock
  pkg/operator/observe_config.go
  pkg/operator/operator.go
  pkg/operator/sync_kubeapiserver_test.go
  pkg/operator/sync_kubeapiserver_v311_00.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/types.go
  vendor/github.com/openshift/api/operator/v1alpha1/types.go
  vendor/github.com/openshift/api/operator/v1alpha1/types_swagger_doc_generated.go
  vendor/github.com/openshift/library-go/.travis.yml
  vendor/github.com/spf13/cobra/.circleci/config.yml
  vendor/github.com/spf13/cobra/.travis.yml
  vendor/github.com/spf13/cobra/README.md
  vendor/github.com/spf13/cobra/bash_completions.go
  vendor/github.com/spf13/cobra/bash_completions.md
  vendor/github.com/spf13/cobra/bash_completions_test.go
  vendor/github.com/spf13/cobra/cobra/cmd/init.go
  vendor/github.com/spf13/cobra/command.go
  vendor/github.com/spf13/cobra/command_test.go
  vendor/github.com/spf13/cobra/doc/man_docs.go
  vendor/github.com/spf13/cobra/doc/man_docs_test.go
  vendor/github.com/spf13/cobra/doc/md_docs.go
  vendor/github.com/spf13/cobra/doc/md_docs_test.go
  vendor/github.com/spf13/cobra/doc/rest_docs.go
  vendor/github.com/spf13/cobra/doc/rest_docs_test.go
  vendor/github.com/spf13/pflag/bytes.go
  vendor/github.com/spf13/pflag/bytes_test.go
  vendor/github.com/spf13/pflag/flag.go
  vendor/github.com/spf13/pflag/flag_test.go
  vendor/github.com/spf13/pflag/string_to_int.go
  vendor/github.com/spf13/pflag/string_to_int_test.go
  vendor/github.com/spf13/pflag/string_to_string.go
  vendor/github.com/spf13/pflag/string_to_string_test.go
Labels: approved, lgtm, size/XXL

#71 render: pluralize --config-overrides-file
  cmd/cluster-kube-apiserver-operator/render/render.go
Labels: approved, lgtm, size/S

#63 manifests: provide kube-system configs and secrets
  bindata/bootkube/config/config-overrides.yaml
  bindata/bootkube/manifests/daemonset-kube-apiserver.yaml
  bindata/bootkube/manifests/kube-system-configmap-aggregator-client-ca.yaml
  bindata/bootkube/manifests/kube-system-configmap-client-ca.yaml
  bindata/bootkube/manifests/kube-system-configmap-etcd-serving-ca.yaml
  bindata/bootkube/manifests/kube-system-configmap-kube-apiserver-config.yaml
  bindata/bootkube/manifests/kube-system-configmap-kubelet-serving-ca.yaml
  bindata/bootkube/manifests/kube-system-configmap-sa-token-signing-certs.yaml
  bindata/bootkube/manifests/kube-system-secret-aggregator-client.yaml
  bindata/bootkube/manifests/kube-system-secret-etcd-client.yaml
  bindata/bootkube/manifests/kube-system-secret-kubelet-client.yaml
  bindata/bootkube/manifests/kube-system-secret-serving-cert.yaml
Labels: approved, lgtm, size/L

#68 Makefile: IMAGES=foo,bar for origin-release target to replace multiple images
  Makefile
  hack/lib/Dockerfile-origin-release
Labels: approved, lgtm, size/S

#73 rename conflicting file
  bindata/bootkube/manifests/configmap-kube-apiserver-client-ca.yaml
Labels: approved, lgtm, size/XS

#75 Unify kube-apiserver-config name
  bindata/bootkube/manifests/configmap-kube-apiserver-config.yaml
  bindata/v3.11.0/kube-apiserver/cm.yaml
  bindata/v3.11.0/kube-apiserver/deployment.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/S

#76 origin-release: speed-up jq install
  hack/lib/Dockerfile-origin-release
Labels: approved, lgtm, size/XS

#78 render: add rbac rules for proxy/logs from apiserver
  bindata/bootkube/manifests/cluster-role-binding-kube-apiserver.yaml
  bindata/bootkube/manifests/cluster-role-kube-apiserver.yaml
Labels: approved, lgtm, size/S

#81 wire in ClusterOperator status
  pkg/operator/starter.go
Labels: approved, lgtm, size/M

#84 add new control loops
  bindata/v3.11.0/kube-apiserver/deployment.yaml
  bindata/v3.11.0/kube-apiserver/pod-cm.yaml
  bindata/v3.11.0/kube-apiserver/pod.yaml
  manifests/0000_10_cluster-kube-apiserver-operator_06_deployment.yaml
  pkg/apis/kubeapiserver/v1alpha1/types.go
  pkg/apis/kubeapiserver/v1alpha1/zz_generated.deepcopy.go
  pkg/operator/deployment_controller.go
  pkg/operator/deployment_controller_v311_00.go
  pkg/operator/starter.go
  pkg/operator/sync_kubeapiserver_test.go
  pkg/operator/sync_kubeapiserver_v311_00.go
  pkg/operator/target_config_reconciler.go
  pkg/operator/target_config_reconciler_v311_00.go
  pkg/operator/v311_00_assets/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/core.go
Labels: approved, size/XXL

#74 sync restrictedCIDRs with install-config
  pkg/operator/observe_config.go
  pkg/operator/observe_config_test.go
  pkg/operator/starter.go
Labels: approved, lgtm, size/L

#90 makes installer create static pod
  bindata/v3.11.0/kube-apiserver/defaultconfig.yaml
  bindata/v3.11.0/kube-apiserver/deployment-config-overrides.yaml
  bindata/v3.11.0/kube-apiserver/installer-cluster-rolebinding.yaml
  bindata/v3.11.0/kube-apiserver/installer-pod.yaml
  bindata/v3.11.0/kube-apiserver/installer-sa.yaml
  bindata/v3.11.0/kube-apiserver/pod-cm.yaml
  bindata/v3.11.0/kube-apiserver/pod.yaml
  manifests/0000_10_cluster-kube-apiserver-operator_06_deployment.yaml
  pkg/apis/kubeapiserver/v1alpha1/types.go
  pkg/cmd/installer/cmd.go
  pkg/operator/installer_controller_v311_00.go
  pkg/operator/target_config_reconciler_v311_00.go
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, size/L

#92 comments and fixes
  pkg/operator/installer_controller_v311_00.go
  pkg/operator/nodeController.go
  pkg/operator/starter.go
Labels: approved, size/M

#88 fix case of the kubeapiserveroperatorconfig type
  bindata/v3.11.0/kube-apiserver/operator-config.yaml
  manifests/0000_10_cluster-kube-apiserver-operator_01_config.crd.yaml
  pkg/apis/kubeapiserver/v1alpha1/register.go
  pkg/apis/kubeapiserver/v1alpha1/types.go
  pkg/apis/kubeapiserver/v1alpha1/zz_generated.deepcopy.go
  pkg/generated/clientset/versioned/typed/kubeapiserver/v1alpha1/fake/fake_kubeapiserver_client.go
  pkg/generated/clientset/versioned/typed/kubeapiserver/v1alpha1/fake/fake_kubeapiserveroperatorconfig.go
  pkg/generated/clientset/versioned/typed/kubeapiserver/v1alpha1/generated_expansion.go
  pkg/generated/clientset/versioned/typed/kubeapiserver/v1alpha1/kubeapiserver_client.go
  pkg/generated/clientset/versioned/typed/kubeapiserver/v1alpha1/kubeapiserveroperatorconfig.go
  pkg/generated/informers/externalversions/generic.go
  pkg/generated/informers/externalversions/kubeapiserver/v1alpha1/interface.go
  pkg/generated/informers/externalversions/kubeapiserver/v1alpha1/kubeapiserveroperatorconfig.go
  pkg/generated/listers/kubeapiserver/v1alpha1/expansion_generated.go
  pkg/generated/listers/kubeapiserver/v1alpha1/kubeapiserveroperatorconfig.go
  pkg/operator/observe_config.go
  pkg/operator/operator.go
  pkg/operator/starter.go
  pkg/operator/sync_kubeapiserver_v311_00.go
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/L

#93 static pod management
  bindata/v3.11.0/kube-apiserver/defaultconfig.yaml
  bindata/v3.11.0/kube-apiserver/deployment-config-overrides.yaml
  bindata/v3.11.0/kube-apiserver/deployment.yaml
  bindata/v3.11.0/kube-apiserver/installer-cluster-rolebinding.yaml
  bindata/v3.11.0/kube-apiserver/installer-pod.yaml
  bindata/v3.11.0/kube-apiserver/installer-sa.yaml
  bindata/v3.11.0/kube-apiserver/pod-cm.yaml
  bindata/v3.11.0/kube-apiserver/pod.yaml
  cmd/cluster-kube-apiserver-operator/main.go
  manifests/0000_10_cluster-kube-apiserver-operator_06_deployment.yaml
  pkg/apis/kubeapiserver/v1alpha1/types.go
  pkg/apis/kubeapiserver/v1alpha1/zz_generated.deepcopy.go
  pkg/cmd/installer/cmd.go
  pkg/cmd/installer/cmd_test.go
  pkg/operator/deployment_controller.go
  pkg/operator/deployment_controller_v311_00.go
  pkg/operator/installer_controller.go
  pkg/operator/installer_controller_v311_00.go
  pkg/operator/nodeController.go
  pkg/operator/starter.go
  pkg/operator/sync_kubeapiserver_test.go
  pkg/operator/sync_kubeapiserver_v311_00.go
  pkg/operator/target_config_reconciler.go
  pkg/operator/target_config_reconciler_v311_00.go
  pkg/operator/v311_00_assets/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/core.go
Labels: approved, lgtm, size/XXL

#95 Makefile: print what origin-release target actually does
  hack/lib/Dockerfile-origin-release
Labels: approved, lgtm, size/XS

#91 render: temporary --disable-phase-2 flag
  cmd/cluster-kube-apiserver-operator/render/render.go
  glide.lock
  vendor/github.com/openshift/api/config/v1/register.go
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/doc.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/fake/doc.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/fake/register.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/scheme/doc.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/config_client.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/doc.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/doc.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_config_client.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_image.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/image.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/interface.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/image.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/interface.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/factory.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/generic.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/expansion_generated.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/image.go
  vendor/github.com/openshift/client-go/glide.lock
  vendor/github.com/openshift/client-go/hack/update-codegen.sh
  vendor/github.com/openshift/library-go/pkg/operator/render/render.go
  vendor/github.com/spf13/pflag/.travis.yml
  vendor/github.com/spf13/pflag/README.md
Labels: approved, lgtm, size/XXL

#99 bump(*): bring the fixes in installer controller
  glide.lock
  vendor/github.com/openshift/api/config/v1/register.go
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/types.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/build.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/config_client.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_build.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_config_client.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/build.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/interface.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/generic.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/build.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/expansion_generated.go
  vendor/github.com/openshift/client-go/glide.lock
  vendor/github.com/openshift/client-go/glide.yaml
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/staticpodcontroller/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/staticpodcontroller/installer_controller_test.go
Labels: approved, lgtm, size/XXL

#98 render: remove phase 2 by default
  bindata/bootkube/manifests/daemonset-kube-apiserver.yaml
  bindata/bootkube/manifests/kube-system-configmap-aggregator-client-ca.yaml
  bindata/bootkube/manifests/kube-system-configmap-client-ca.yaml
  bindata/bootkube/manifests/kube-system-configmap-etcd-serving-ca.yaml
  bindata/bootkube/manifests/kube-system-configmap-kube-apiserver-config.yaml
  bindata/bootkube/manifests/kube-system-configmap-kubelet-serving-ca.yaml
  bindata/bootkube/manifests/kube-system-configmap-sa-token-signing-certs.yaml
  bindata/bootkube/manifests/kube-system-secret-aggregator-client.yaml
  bindata/bootkube/manifests/kube-system-secret-etcd-client.yaml
  bindata/bootkube/manifests/kube-system-secret-kubelet-client.yaml
  bindata/bootkube/manifests/kube-system-secret-serving-cert.yaml
  cmd/cluster-kube-apiserver-operator/render/render.go
Labels: approved, lgtm, size/L

#100 remove file locking
  bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml
Labels: approved, lgtm, size/M
