Repository openshift/cluster-kube-apiserver-operator, pull requests merged in 2018-12, with the labels that each got.

#149 make static pods node critical priority
  bindata/v3.11.0/kube-apiserver/installer-pod.yaml
  bindata/v3.11.0/kube-apiserver/pod.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#147 operator: wait for spec.observedConfig to be filled before installing
  pkg/operator/target_config_reconciler.go
Labels: approved, lgtm, size/XS

#153 bump library-go
  glide.lock
  pkg/operator/starter.go
  vendor/github.com/davecgh/go-spew/.travis.yml
  vendor/github.com/davecgh/go-spew/LICENSE
  vendor/github.com/davecgh/go-spew/README.md
  vendor/github.com/davecgh/go-spew/spew/bypass.go
  vendor/github.com/davecgh/go-spew/spew/bypasssafe.go
  vendor/github.com/davecgh/go-spew/spew/dump.go
  vendor/github.com/davecgh/go-spew/spew/dump_test.go
  vendor/github.com/davecgh/go-spew/spew/dumpcgo_test.go
  vendor/github.com/davecgh/go-spew/spew/format.go
  vendor/github.com/davecgh/go-spew/spew/format_test.go
  vendor/github.com/davecgh/go-spew/spew/internal_test.go
  vendor/github.com/davecgh/go-spew/spew/internalunsafe_test.go
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/README.md
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/github.com/ghodss/yaml/yaml_go110.go
  vendor/github.com/ghodss/yaml/yaml_go110_test.go
  vendor/github.com/ghodss/yaml/yaml_test.go
  vendor/github.com/imdario/mergo/.gitignore
  vendor/github.com/imdario/mergo/.travis.yml
  vendor/github.com/imdario/mergo/CODE_OF_CONDUCT.md
  vendor/github.com/imdario/mergo/README.md
  vendor/github.com/imdario/mergo/issue17_test.go
  vendor/github.com/imdario/mergo/issue23_test.go
  vendor/github.com/imdario/mergo/issue33_test.go
  vendor/github.com/imdario/mergo/issue38_test.go
  vendor/github.com/imdario/mergo/issue50_test.go
  vendor/github.com/imdario/mergo/issue52_test.go
  vendor/github.com/imdario/mergo/issue61_test.go
  vendor/github.com/imdario/mergo/issue64_test.go
  vendor/github.com/imdario/mergo/issue66_test.go
  vendor/github.com/imdario/mergo/map.go
  vendor/github.com/imdario/mergo/merge.go
  vendor/github.com/imdario/mergo/merge_appendslice_test.go
  vendor/github.com/imdario/mergo/merge_test.go
  vendor/github.com/imdario/mergo/mergo.go
  vendor/github.com/imdario/mergo/mergo_test.go
  vendor/github.com/imdario/mergo/pr80_test.go
  vendor/github.com/imdario/mergo/pr81_test.go
  vendor/github.com/imdario/mergo/testdata/license.yml
  vendor/github.com/imdario/mergo/testdata/thing.yml
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiextensions.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/apiextensions.go
  vendor/github.com/openshift/library-go/pkg/operator/status/controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/controller_test.go
  vendor/github.com/openshift/library-go/pkg/proc/reaper.go
  vendor/github.com/openshift/library-go/pkg/proc/reaper_unsupported.go
Labels: approved, lgtm, size/XXL

#155 bump
  glide.lock
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller_test.go
Labels: approved, lgtm, size/M

#156 config observers: add OWNER files with config owners
  pkg/operator/configobservation/etcd/OWNERS
  pkg/operator/configobservation/images/OWNERS
  pkg/operator/configobservation/network/OWNERS
Labels: approved, lgtm, size/S

#159 configobserver: switch to library-go network observer helpers
  glide.lock
  pkg/operator/configobservation/network/observe_network.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/network/observe_network.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/network/observe_networking_test.go
Labels: approved, lgtm, size/L

#160 fix status reporting
  glide.lock
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcehash/as_configmap.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller_test.go
Labels: approved, lgtm, size/L

#161 add memory request to kube-apiserver and operator pods
  bindata/v3.11.0/kube-apiserver/pod.yaml
  manifests/0000_10_cluster-kube-apiserver-operator_06_deployment.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#163 add clusteroperator resource to CVO payload
  manifests/0000_10_cluster-kube-apiserver-operator_07_clusteroperator.yaml
Labels: approved, lgtm, size/XS

#167 Revert "add clusteroperator resource to CVO payload"
  manifests/0000_10_cluster-kube-apiserver-operator_07_clusteroperator.yaml
Labels: approved, lgtm, size/XS

#166 fix status
  glide.lock
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  vendor/github.com/davecgh/go-spew/.travis.yml
  vendor/github.com/davecgh/go-spew/LICENSE
  vendor/github.com/davecgh/go-spew/README.md
  vendor/github.com/davecgh/go-spew/spew/bypass.go
  vendor/github.com/davecgh/go-spew/spew/bypasssafe.go
  vendor/github.com/davecgh/go-spew/spew/dump.go
  vendor/github.com/davecgh/go-spew/spew/dump_test.go
  vendor/github.com/davecgh/go-spew/spew/dumpcgo_test.go
  vendor/github.com/davecgh/go-spew/spew/format.go
  vendor/github.com/davecgh/go-spew/spew/format_test.go
  vendor/github.com/davecgh/go-spew/spew/internal_test.go
  vendor/github.com/davecgh/go-spew/spew/internalunsafe_test.go
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/README.md
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/github.com/ghodss/yaml/yaml_go110.go
  vendor/github.com/ghodss/yaml/yaml_go110_test.go
  vendor/github.com/ghodss/yaml/yaml_test.go
  vendor/github.com/imdario/mergo/.gitignore
  vendor/github.com/imdario/mergo/.travis.yml
  vendor/github.com/imdario/mergo/CODE_OF_CONDUCT.md
  vendor/github.com/imdario/mergo/README.md
  vendor/github.com/imdario/mergo/issue17_test.go
  vendor/github.com/imdario/mergo/issue23_test.go
  vendor/github.com/imdario/mergo/issue33_test.go
  vendor/github.com/imdario/mergo/issue38_test.go
  vendor/github.com/imdario/mergo/issue50_test.go
  vendor/github.com/imdario/mergo/issue52_test.go
  vendor/github.com/imdario/mergo/issue61_test.go
  vendor/github.com/imdario/mergo/issue64_test.go
  vendor/github.com/imdario/mergo/issue66_test.go
  vendor/github.com/imdario/mergo/map.go
  vendor/github.com/imdario/mergo/merge.go
  vendor/github.com/imdario/mergo/merge_appendslice_test.go
  vendor/github.com/imdario/mergo/merge_test.go
  vendor/github.com/imdario/mergo/mergo.go
  vendor/github.com/imdario/mergo/mergo_test.go
  vendor/github.com/imdario/mergo/pr80_test.go
  vendor/github.com/imdario/mergo/pr81_test.go
  vendor/github.com/imdario/mergo/testdata/license.yml
  vendor/github.com/imdario/mergo/testdata/thing.yml
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/network/OWNERS
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/backingresource/backing_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/backingresource/backing_resource_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/common/helpers.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/common/test_utils.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/node/node_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/revision/deployment_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/interfaces.go
Labels: approved, lgtm, size/XXL

#169 bring back conditions
  glide.lock
  vendor/github.com/davecgh/go-spew/.travis.yml
  vendor/github.com/davecgh/go-spew/LICENSE
  vendor/github.com/davecgh/go-spew/README.md
  vendor/github.com/davecgh/go-spew/spew/bypass.go
  vendor/github.com/davecgh/go-spew/spew/bypasssafe.go
  vendor/github.com/davecgh/go-spew/spew/dump.go
  vendor/github.com/davecgh/go-spew/spew/dump_test.go
  vendor/github.com/davecgh/go-spew/spew/dumpcgo_test.go
  vendor/github.com/davecgh/go-spew/spew/format.go
  vendor/github.com/davecgh/go-spew/spew/format_test.go
  vendor/github.com/davecgh/go-spew/spew/internal_test.go
  vendor/github.com/davecgh/go-spew/spew/internalunsafe_test.go
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/README.md
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/github.com/ghodss/yaml/yaml_go110.go
  vendor/github.com/ghodss/yaml/yaml_go110_test.go
  vendor/github.com/ghodss/yaml/yaml_test.go
  vendor/github.com/imdario/mergo/.gitignore
  vendor/github.com/imdario/mergo/.travis.yml
  vendor/github.com/imdario/mergo/CODE_OF_CONDUCT.md
  vendor/github.com/imdario/mergo/README.md
  vendor/github.com/imdario/mergo/issue17_test.go
  vendor/github.com/imdario/mergo/issue23_test.go
  vendor/github.com/imdario/mergo/issue33_test.go
  vendor/github.com/imdario/mergo/issue38_test.go
  vendor/github.com/imdario/mergo/issue50_test.go
  vendor/github.com/imdario/mergo/issue52_test.go
  vendor/github.com/imdario/mergo/issue61_test.go
  vendor/github.com/imdario/mergo/issue64_test.go
  vendor/github.com/imdario/mergo/issue66_test.go
  vendor/github.com/imdario/mergo/map.go
  vendor/github.com/imdario/mergo/merge.go
  vendor/github.com/imdario/mergo/merge_appendslice_test.go
  vendor/github.com/imdario/mergo/merge_test.go
  vendor/github.com/imdario/mergo/mergo.go
  vendor/github.com/imdario/mergo/mergo_test.go
  vendor/github.com/imdario/mergo/pr80_test.go
  vendor/github.com/imdario/mergo/pr81_test.go
  vendor/github.com/imdario/mergo/testdata/license.yml
  vendor/github.com/imdario/mergo/testdata/thing.yml
  vendor/github.com/openshift/library-go/glide.lock
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/prune/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/prune/cmd_test.go
Labels: approved, lgtm, size/XXL

#173 bootstrap: add readiness probe, unified with operator phase
  bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml
Labels: approved, lgtm, size/XS

#164 add basic rotation
  glide.lock
  pkg/operator/aggregatorproxyrotation/cabundle.go
  pkg/operator/aggregatorproxyrotation/cabundle_test.go
  pkg/operator/aggregatorproxyrotation/client_cert_rotation_controller.go
  pkg/operator/aggregatorproxyrotation/signer.go
  pkg/operator/aggregatorproxyrotation/signer_test.go
  pkg/operator/aggregatorproxyrotation/target.go
  pkg/operator/aggregatorproxyrotation/target_test.go
  pkg/operator/aggregatorproxyrotation/testfiles/tls-expired.crt
  pkg/operator/aggregatorproxyrotation/testfiles/tls-multiple.crt
  pkg/operator/aggregatorproxyrotation/testfiles/tls.crt
  pkg/operator/aggregatorproxyrotation/testfiles/tls.key
  pkg/operator/starter.go
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_dns.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/library-go/Makefile
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/github.com/openshift/library-go/pkg/crypto/crypto_test.go
  vendor/github.com/openshift/library-go/pkg/crypto/rotation.go
  vendor/github.com/openshift/library-go/pkg/crypto/rotation_test.go
  vendor/github.com/openshift/library-go/pkg/crypto/testfiles/tls-expired.crt
  vendor/github.com/openshift/library-go/pkg/crypto/testfiles/tls-multiple.crt
  vendor/github.com/openshift/library-go/pkg/crypto/testfiles/tls.crt
  vendor/github.com/openshift/library-go/pkg/crypto/testfiles/tls.key
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/bindata/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/manifests/installer-pod.yaml
Labels: approved, lgtm, size/XXL

#174 Use consistently IMAGE_ORG everywhere
  Dockerfile-origin-release
  Makefile
  README.md
Labels: approved, lgtm, size/M
