Repository openshift/cluster-kube-apiserver-operator, pull requests merged in 2018-11, with the labels that each got.

#102 refactor starter to run static pod controllers via new method
  glide.lock
  pkg/operator/starter.go
  pkg/operator/target_config_reconciler_v311_00.go
  pkg/operator/v311_00_assets/bindata.go
  vendor/github.com/davecgh/go-spew/.travis.yml
  vendor/github.com/davecgh/go-spew/LICENSE
  vendor/github.com/davecgh/go-spew/README.md
  vendor/github.com/davecgh/go-spew/spew/bypass.go
  vendor/github.com/davecgh/go-spew/spew/bypasssafe.go
  vendor/github.com/davecgh/go-spew/spew/dump.go
  vendor/github.com/davecgh/go-spew/spew/dump_test.go
  vendor/github.com/davecgh/go-spew/spew/dumpcgo_test.go
  vendor/github.com/davecgh/go-spew/spew/format.go
  vendor/github.com/davecgh/go-spew/spew/format_test.go
  vendor/github.com/davecgh/go-spew/spew/internal_test.go
  vendor/github.com/davecgh/go-spew/spew/internalunsafe_test.go
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/README.md
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/github.com/ghodss/yaml/yaml_go110.go
  vendor/github.com/ghodss/yaml/yaml_go110_test.go
  vendor/github.com/ghodss/yaml/yaml_test.go
  vendor/github.com/golang/glog/README
  vendor/github.com/golang/glog/glog.go
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/types.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/client-go/examples/build/README.md
  vendor/github.com/openshift/library-go/Makefile
  vendor/github.com/openshift/library-go/glide.lock
  vendor/github.com/openshift/library-go/glide.yaml
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/backingresource/backing_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/backingresource/backing_resource_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/backingresource/bindata/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/backingresource/manifests/installer-cluster-rolebinding.yaml
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/backingresource/manifests/installer-sa.yaml
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/common/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/common/test_utils.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/deployment/deployment_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/deployment/deployment_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/node/node_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/node/node_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/staticpodcontroller/deployment_controller_test.go
Labels: approved, lgtm, size/XXL

#85 provide config observation operator status
  pkg/operator/observe_config.go
  pkg/operator/observe_config_test.go
Labels: approved, lgtm, size/XL

#110 Repair origin-release Makefile target
  Dockerfile-origin-release
  Makefile
Labels: approved, lgtm, size/S

#107 fix printing version
  Dockerfile
  cmd/cluster-kube-apiserver-operator/main.go
Labels: approved, lgtm, size/S

#111 observe imagePolicyConfig/internalRegistryHostname
  glide.lock
  pkg/operator/observe_config.go
  pkg/operator/observe_config_test.go
  pkg/operator/starter.go
  vendor/github.com/davecgh/go-spew/.travis.yml
  vendor/github.com/davecgh/go-spew/LICENSE
  vendor/github.com/davecgh/go-spew/README.md
  vendor/github.com/davecgh/go-spew/spew/bypass.go
  vendor/github.com/davecgh/go-spew/spew/bypasssafe.go
  vendor/github.com/davecgh/go-spew/spew/dump.go
  vendor/github.com/davecgh/go-spew/spew/dump_test.go
  vendor/github.com/davecgh/go-spew/spew/dumpcgo_test.go
  vendor/github.com/davecgh/go-spew/spew/format.go
  vendor/github.com/davecgh/go-spew/spew/format_test.go
  vendor/github.com/davecgh/go-spew/spew/internal_test.go
  vendor/github.com/davecgh/go-spew/spew/internalunsafe_test.go
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/README.md
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/github.com/ghodss/yaml/yaml_go110.go
  vendor/github.com/ghodss/yaml/yaml_go110_test.go
  vendor/github.com/ghodss/yaml/yaml_test.go
  vendor/github.com/golang/glog/README
  vendor/github.com/golang/glog/glog.go
  vendor/github.com/openshift/api/config/v1/register.go
  vendor/github.com/openshift/client-go/glide.lock
Labels: approved, lgtm, size/XL

#113 add liveness and readiness probes to static pod
  bindata/v3.11.0/kube-apiserver/pod.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/S

#115 update probes port to match the container port
  bindata/v3.11.0/kube-apiserver/pod.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#108 Move render command to pkg/cmd
  cmd/cluster-kube-apiserver-operator/main.go
  pkg/cmd/render/render.go
  pkg/test/assets_test.go
Labels: approved, lgtm, size/XS

#116 handle case of missing image.config.openshift.io type definition
  pkg/operator/observe_config.go
  pkg/operator/observe_config_test.go
Labels: approved, lgtm, size/M

#117 move to operator specific namespace
  manifests/0000_10_cluster-kube-apiserver-operator_00_namespace.yaml
  manifests/0000_10_cluster-kube-apiserver-operator_03_configmap.yaml
  manifests/0000_10_cluster-kube-apiserver-operator_04_clusterrolebinding.yaml
  manifests/0000_10_cluster-kube-apiserver-operator_05_serviceaccount.yaml
  manifests/0000_10_cluster-kube-apiserver-operator_06_deployment.yaml
  pkg/operator/starter.go
Labels: approved, lgtm

#118 pod.yaml: fix readiness endpoint
  bindata/v3.11.0/kube-apiserver/pod.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#122 update library-go for status
  glide.lock
  vendor/github.com/openshift/library-go/glide.lock
  vendor/github.com/openshift/library-go/pkg/operator/status/controller.go
Labels: approved, lgtm, size/S

#124 generic config observer
  pkg/configobserver/config_observer_controller.go
  pkg/configobserver/config_observer_controller_test.go
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/configobservation/etcd/observe_etcd.go
  pkg/operator/configobservation/images/observe_images.go
  pkg/operator/configobservation/images/observe_images_test.go
  pkg/operator/configobservation/interfaces.go
  pkg/operator/configobservation/network/observe_network.go
  pkg/operator/configobservation/network/observe_network_test.go
  pkg/operator/observe_config.go
  pkg/operator/observe_config_test.go
  pkg/operator/starter.go
  pkg/operator/staticpod_interface.go
Labels: approved, lgtm, size/XXL

#125 metrics: add svc for metrics and wire serving certs to deployment
  manifests/0000_10_cluster-kube-apiserver-operator_02_service.yaml
  manifests/0000_10_cluster-kube-apiserver-operator_06_deployment.yaml
Labels: approved, lgtm, size/S

#109 copy the etcd CA and client cert/key pair from etcd operator
  bindata/bootkube/manifests/configmap-etcd-serving-ca.yaml
  bindata/bootkube/manifests/secret-etcd-client.yaml
  pkg/operator/starter.go
  pkg/operator/target_config_reconciler_v311_00.go
Labels: approved, lgtm, size/M

#130 switch to using library-go configobserver
  glide.lock
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/configobservation/etcd/observe_etcd.go
  pkg/operator/configobservation/images/observe_images.go
  pkg/operator/configobservation/network/observe_network.go
  vendor/github.com/openshift/api/OWNERS
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer_default.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer_linux.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer_polling.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer_polling_test.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer_test.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller_test.go
  vendor/github.com/sigma/go-inotify/LICENSE
  vendor/github.com/sigma/go-inotify/PATENTS
  vendor/github.com/sigma/go-inotify/README.md
  vendor/github.com/sigma/go-inotify/inotify_linux.go
  vendor/github.com/sigma/go-inotify/inotify_linux_test.go
Labels: approved, lgtm, size/XL

#131 Use openshift-kube-apiserve as container name for easier debugging
  bindata/v3.11.0/kube-apiserver/pod.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#134 Remove public info configmap
  bindata/v3.11.0/kube-apiserver/public-info-role.yaml
  bindata/v3.11.0/kube-apiserver/public-info-rolebinding.yaml
  bindata/v3.11.0/kube-apiserver/public-info.yaml
  glide.lock
  pkg/operator/target_config_reconciler_v311_00.go
  pkg/operator/v311_00_assets/bindata.go
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go
  vendor/github.com/openshift/library-go/pkg/controller/metrics/client_metrics.go
  vendor/github.com/openshift/library-go/pkg/controller/metrics/workqueue_metrics.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/apps.go
Labels: approved, lgtm, size/L

#138 system prefix user names for node permissions
  bindata/bootkube/manifests/cluster-role-binding-kube-apiserver.yaml
  bindata/v3.11.0/kube-apiserver/defaultconfig.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#139 use host-etcd service endpoints
  pkg/operator/configobservation/etcd/observe_etcd.go
Labels: approved, lgtm, size/S

#141 wire events to operator
  glide.lock
  manifests/0000_10_cluster-kube-apiserver-operator_06_deployment.yaml
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/starter.go
  pkg/operator/target_config_reconciler.go
  pkg/operator/target_config_reconciler_v311_00.go
  vendor/github.com/openshift/library-go/pkg/config/client/client_config.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/flags.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer_polling.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/events/OWNERS
  vendor/github.com/openshift/library-go/pkg/operator/events/recorder.go
  vendor/github.com/openshift/library-go/pkg/operator/events/recorder_in_memory.go
  vendor/github.com/openshift/library-go/pkg/operator/events/recorder_logging.go
  vendor/github.com/openshift/library-go/pkg/operator/events/recorder_test.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/backingresource/backing_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/backingresource/backing_resource_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/backingresource/bindata/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/backingresource/manifests/installer-cluster-rolebinding.yaml
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/node/node_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/node/node_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/revision/deployment_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/revision/deployment_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1staticpod/controller/backingresource/backing_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1staticpod/controller/backingresource/backing_resource_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1staticpod/controllers.go
Labels: approved, lgtm, size/XL

#146 network-observer: set serviceSubnet in apiserver config
  pkg/operator/configobservation/network/observe_network.go
Labels: approved, lgtm, size/XS

#148 Update README
  README.md
Labels: approved, lgtm, size/M

#151 Shorten config resource name
  bindata/v3.11.0/kube-apiserver/cm.yaml
  bindata/v3.11.0/kube-apiserver/pod.yaml
  pkg/operator/starter.go
  pkg/operator/target_config_reconciler_v311_00.go
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/S
