Repository openshift/cluster-kube-apiserver-operator, pull requests merged in 2019-03, with the labels that each got.

#310 library-go: fix retry logic when getting installer pod self-reference
  glide.lock
  vendor/github.com/openshift/api/config/v1/types_features.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/library-go/glide.lock
  vendor/github.com/openshift/library-go/glide.yaml
  vendor/github.com/openshift/library-go/pkg/operator/resource/retry/retry.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/retry/retry_test.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/retry/wait.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/copy.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/copy_test.go
  vendor/golang.org/x/tools/go/analysis/passes/deepequalerrors/deepequalerrors.go
  vendor/golang.org/x/tools/go/analysis/passes/deepequalerrors/deepequalerrors_test.go
  vendor/golang.org/x/tools/go/analysis/passes/deepequalerrors/testdata/src/a/a.go
  vendor/golang.org/x/tools/go/analysis/passes/printf/printf.go
  vendor/golang.org/x/tools/go/analysis/passes/printf/printf_test.go
  vendor/golang.org/x/tools/go/analysis/passes/printf/testdata/src/nofmt/nofmt.go
  vendor/golang.org/x/tools/go/analysis/passes/printf/types.go
  vendor/golang.org/x/tools/go/packages/golist.go
  vendor/golang.org/x/tools/go/packages/packages_test.go
  vendor/golang.org/x/tools/internal/lsp/diagnostics.go
  vendor/golang.org/x/tools/internal/lsp/lsp_test.go
  vendor/golang.org/x/tools/internal/lsp/source/diagnostics.go
Labels: approved, lgtm, size/XL

#315 bump(library-go): improve logging of what causes a static pod rollout
  glide.lock
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/revision/revision_controller.go
Labels: approved, lgtm, size/S

#317 operator: add init container to fix audit permissions
  bindata/v3.11.0/kube-apiserver/pod.yaml
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/M

#308 minor fitting to set versions for our operator
  manifests/0000_10_kube-apiserver-operator_03_version-mapping.yaml
  manifests/0000_10_kube-apiserver-operator_06_deployment.yaml
  manifests/0000_10_kube-apiserver-operator_07_clusteroperator.yaml
  manifests/image-references
Labels: approved, lgtm, size/S

#322 manifests: operator is system-cluster-critical priority
  manifests/0000_10_kube-apiserver-operator_06_deployment.yaml
Labels: approved, lgtm, size/XS

#326 use dynamic reloading of certs to avoid rolling out new deployment versions
  bindata/v3.11.0/kube-apiserver/defaultconfig.yaml
  pkg/operator/starter.go
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/S

#329 cmd: fix operator component name
  pkg/cmd/operator/cmd.go
Labels: approved, lgtm, size/XS

#332 defaultconfig: bump http2-max-streams-per-connection to 2000
  bindata/v3.11.0/kube-apiserver/defaultconfig.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#333 initial e2e-operator tests
  Makefile
  test/e2e/operator_test.go
  test/library/client.go
Labels: approved, lgtm, priority/critical-urgent, queue/blocks-others, size/M

#330 README/Makefile: replace origin-release with oc-adm-release
  Makefile
  README.md
Labels: approved, lgtm, size/S

#338 Bump cert rotation to 30 days
  pkg/operator/certrotationcontroller/certrotationcontroller.go
Labels: approved, lgtm, size/M

#341 Update readme
  README.md
Labels: approved, lgtm, size/S

#331 copy observed cert secrets and configmaps to correct namespace
  pkg/operator/configobservation/apiserver/observe_apiserver.go
  pkg/operator/configobservation/apiserver/observe_apiserver_test.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, lgtm, size/L

#343 bump library-go to fix pod state and improve cert debugging
  glide.lock
  vendor/github.com/openshift/api/build/v1/consts.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/library-go/pkg/certs/util.go
  vendor/github.com/openshift/library-go/pkg/certs/util_test.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
Labels: approved, lgtm, size/L

#347 bump library-go to pick fix for aggregating messages in conditions
  glide.lock
  vendor/github.com/openshift/api/operator/v1/register.go
  vendor/github.com/openshift/api/operator/v1/types_dns.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/condition.go
Labels: approved, lgtm, size/L

#342 Add cert-rotation configmap for setting base rotation interval
  pkg/cmd/render/render.go
  pkg/operator/certrotationcontroller/certrotationcontroller.go
  pkg/operator/starter.go
Labels: approved, lgtm, size/M

#344 enable local volumes
  bindata/v3.11.0/kube-apiserver/defaultconfig.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#349 fix up owners files
  pkg/operator/configobservation/images/OWNERS
Labels: approved, lgtm, size/XS

#350 Fix admission config
  bindata/bootkube/config/bootstrap-config-overrides.yaml
  bindata/v3.11.0/kube-apiserver/defaultconfig.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/M

#351 Remove cluster api dependency
  pkg/cmd/render/render.go
  pkg/cmd/render/render_test.go
Labels: approved, lgtm, size/L

#346 pod.yaml: add init container waiting for free port
  bindata/v3.11.0/kube-apiserver/pod.yaml
Labels: approved, lgtm, size/S

#352 Increase minimal-shutdown-duration to 35s to cope with slowly converging SDN
  bindata/v3.11.0/kube-apiserver/defaultconfig.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#353 audit-policy: exclude /readyz
  bindata/v3.11.0/kube-apiserver/defaultconfig.yaml
  bindata/v3.11.0/kube-apiserver/pod.yaml
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/S

#354 operator/v1: fix pattern for managementState
  Dockerfile
  Dockerfile.rhel7
  glide.lock
  manifests/0000_10_kube-apiserver-operator_01_config.crd.yaml
  manifests/0000_10_kube-apiserver-operator_01_config.crd.yaml-merge-patch
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/bindata.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/codegen.mk
  vendor/github.com/pkg/profile/.travis.yml
  vendor/github.com/pkg/profile/profile.go
Labels: approved, lgtm, size/M

#356 Revert render changes from 0b686ff00295c382f245b0b4103a566d672498c8
  pkg/cmd/render/render.go
Labels: approved, lgtm, size/M
