Repository openshift/cluster-kube-apiserver-operator, pull requests merged in 2019-04, with the labels that each got.

#363 switch to constrained CSR signer for kubelet verification
  bindata/bootkube/config/bootstrap-config-overrides.yaml
  bindata/bootkube/config/config-overrides.yaml
  bindata/bootkube/manifests/configmap-csr-controller-ca.yaml
Labels: approved, lgtm, size/XS

#371 upgrade fix
  glide.lock
  glide.yaml
  manifests/0000_10_kube-apiserver-operator_03_version-mapping.yaml
  manifests/0000_10_kube-apiserver-operator_06_deployment.yaml
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/version.go
Labels: approved, lgtm, size/M

#367 add test for operand image version
  test/e2e/operator_test.go
Labels: approved, lgtm, size/M

#373 Set terminationGracePeriodSeconds in pod spec
  bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml
  bindata/v3.11.0/kube-apiserver/defaultconfig.yaml
  bindata/v3.11.0/kube-apiserver/pod.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/S

#364 use new certs for service network and localhost
  bindata/bootkube/config/bootstrap-config-overrides.yaml
  bindata/bootkube/config/config-overrides.yaml
  bindata/bootkube/manifests/config.apiserver.yaml
  bindata/bootkube/manifests/secret-loadbalancer-serving-signer.yaml
  pkg/operator/configobservation/apiserver/observe_apiserver.go
  pkg/operator/configobservation/apiserver/observe_apiserver_test.go
  pkg/operator/starter.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  test/e2e/user_certs_test.go
Labels: approved, lgtm, size/L

#375 targetconfig: don't hardcode image replacements
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, lgtm, size/S

#378 switch to library-go featuregate observer
  glide.lock
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/configobservation/interfaces.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/observe_featuregates.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/observe_featuregates_test.go
Labels: approved, lgtm, size/L

#384 fix the ca-bundle used by MCD
  bindata/bootkube/manifests/configmap-initial-kube-apiserver-client-ca.yaml
Labels: approved, do-not-merge/hold, lgtm, size/XS

#390 metrics on cert rotation destablized a bunch
  glide.lock
  vendor/github.com/davecgh/go-spew/.travis.yml
  vendor/github.com/davecgh/go-spew/LICENSE
  vendor/github.com/davecgh/go-spew/README.md
  vendor/github.com/davecgh/go-spew/spew/bypass.go
  vendor/github.com/davecgh/go-spew/spew/bypasssafe.go
  vendor/github.com/davecgh/go-spew/spew/dump.go
  vendor/github.com/davecgh/go-spew/spew/dump_test.go
  vendor/github.com/davecgh/go-spew/spew/dumpcgo_test.go
  vendor/github.com/davecgh/go-spew/spew/format.go
  vendor/github.com/davecgh/go-spew/spew/format_test.go
  vendor/github.com/davecgh/go-spew/spew/internal_test.go
  vendor/github.com/davecgh/go-spew/spew/internalunsafe_test.go
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/go.mod
  vendor/github.com/ghodss/yaml/go.sum
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/github.com/ghodss/yaml/yaml_go110_test.go
  vendor/github.com/ghodss/yaml/yaml_test.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/metrics/monitor.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/metrics/util.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/gopkg.in/yaml.v2/decode_test.go
  vendor/gopkg.in/yaml.v2/encode.go
  vendor/gopkg.in/yaml.v2/encode_test.go
  vendor/k8s.io/klog/.github/ISSUE_TEMPLATE/bug_report.md
  vendor/k8s.io/klog/.github/ISSUE_TEMPLATE/feature_request.md
  vendor/k8s.io/klog/.github/PULL_REQUEST_TEMPLATE.md
  vendor/k8s.io/klog/.travis.yml
  vendor/k8s.io/klog/CONTRIBUTING.md
  vendor/k8s.io/klog/OWNERS
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/SECURITY_CONTACTS
  vendor/k8s.io/klog/code-of-conduct.md
  vendor/k8s.io/klog/examples/coexist_glog/coexist_glog.go
  vendor/k8s.io/klog/examples/klogr/main.go
  vendor/k8s.io/klog/examples/log_file/usage_log_file.go
  vendor/k8s.io/klog/examples/set_output/usage_set_output.go
  vendor/k8s.io/klog/glog/README.md
  vendor/k8s.io/klog/glog/glog.go
  vendor/k8s.io/klog/glog/glog_test.go
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
  vendor/k8s.io/klog/klog_test.go
  vendor/k8s.io/klog/klogr/README.md
  vendor/k8s.io/klog/klogr/klogr.go
  vendor/k8s.io/klog/klogr/klogr_test.go
Labels: approved, lgtm, size/XXL

#362 use the new installer certs to serve
  pkg/operator/certrotationcontroller/certrotationcontroller.go
  pkg/operator/configobservation/apiserver/observe_apiserver.go
  pkg/operator/configobservation/apiserver/observe_apiserver_test.go
  pkg/operator/starter.go
  test/e2e/user_certs_test.go
Labels: approved, lgtm, size/M

#395 remove kube-ca certs from kas-o
  bindata/bootkube/config/bootstrap-config-overrides.yaml
  bindata/bootkube/manifests/configmap-initial-kube-apiserver-serving-ca.yaml
  bindata/bootkube/manifests/configmap-node-bootstrap-client-ca.yaml
  bindata/bootkube/manifests/secret-initial-serving-cert.yaml
  bindata/v3.11.0/kube-apiserver/defaultconfig.yaml
  pkg/operator/resourcesynccontroller/resourcesynccontroller.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/M

#400 update the default cert to match
  test/e2e/user_certs_test.go
Labels: approved, lgtm, size/XS

#403 disable user sni check
  test/e2e/user_certs_test.go
Labels: approved, lgtm, size/XS

#399 ObserveAuthMetadata: default authentication.spec.type
  pkg/operator/configobservation/auth/auth_metadata.go
Labels: approved, lgtm, size/S

#398 include logs in pod status
  bindata/v3.11.0/kube-apiserver/pod.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#405 add internal load balancer cert
  bindata/bootkube/config/bootstrap-config-overrides.yaml
  pkg/operator/certrotationcontroller/certrotationcontroller.go
  pkg/operator/certrotationcontroller/externalloadbalancer.go
  pkg/operator/certrotationcontroller/internalloadbalancer.go
  pkg/operator/certrotationcontroller/loadbalancer.go
  pkg/operator/configobservation/apiserver/observe_apiserver.go
  pkg/operator/configobservation/apiserver/observe_apiserver_test.go
  pkg/operator/starter.go
Labels: approved, lgtm, size/L

#408 simplify sa token verifier using adoption
  bindata/bootkube/config/config-overrides.yaml
  bindata/bootkube/manifests/configmap-sa-token-signing-certs.yaml
  bindata/v3.11.0/kube-apiserver/defaultconfig.yaml
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/configobservation/satokencerts/observe_satokencerts.go
  pkg/operator/resourcesynccontroller/resourcesynccontroller.go
  pkg/operator/starter.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/L

#410 Switch openshift/kas-o to go1.11
  test/library/crypto.go
Labels: approved, lgtm, size/XS

#414 Switch to go1.11
  Dockerfile
  Dockerfile.rhel7
Labels: approved, lgtm, size/XS

#417 squash init containers to one
  bindata/v3.11.0/kube-apiserver/pod.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/S

#416 bump library-go to get labels on rotated certificates
  glide.lock
  vendor/github.com/gobuffalo/envy/SHOULDERS.md
  vendor/github.com/gobuffalo/envy/envy.go
  vendor/github.com/gobuffalo/envy/envy_test.go
  vendor/github.com/gobuffalo/envy/version.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle_test.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/label.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer_test.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target_test.go
  vendor/k8s.io/apiextensions-apiserver/Godeps/Godeps.json
  vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/apiserver.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/validation/validation.go
  vendor/k8s.io/apiextensions-apiserver/pkg/controller/openapi/aggregator.go
  vendor/k8s.io/apiextensions-apiserver/pkg/controller/openapi/builder.go
  vendor/k8s.io/apiextensions-apiserver/pkg/controller/openapi/builder_test.go
  vendor/k8s.io/apiextensions-apiserver/pkg/controller/openapi/controller.go
  vendor/k8s.io/apiextensions-apiserver/pkg/controller/openapi/conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/controller/openapi/conversion_test.go
  vendor/k8s.io/apiextensions-apiserver/pkg/features/kube_features.go
  vendor/k8s.io/apiextensions-apiserver/pkg/generated/openapi/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/generated/openapi/zz_generated.openapi.go
Labels: approved, lgtm, size/XXL

#368 Add cloudprovider configuration to api-server
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/configobservation/interfaces.go
  pkg/operator/starter.go
Labels: approved, lgtm, size/M

#406 re-enable SNI e2e tests
  test/e2e/user_certs_test.go
Labels: approved, lgtm, size/M

#418 use the CVO to create the operator config
  manifests/0000_10_kube-apiserver-operator_01_operator.cr.yaml
  pkg/operator/starter.go
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/M

#419 certoperator: fix incorrect use of infrastructure.config.openshift.io API
  pkg/operator/certrotationcontroller/externalloadbalancer.go
  pkg/operator/certrotationcontroller/internalloadbalancer.go
Labels: approved, lgtm, size/XS

#422 switch to relying on etcd info in openshift-config
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/operatorclient/interfaces.go
  pkg/operator/resourcesynccontroller/resourcesynccontroller.go
Labels: approved, lgtm, size/XS

#424 remove resource the MCO owns
  bindata/bootkube/manifests/configmap-initial-kube-apiserver-client-ca.yaml
Labels: approved, lgtm, size/XS

#413 Increase minimum-shutdown-duration by 35s to 70s
  bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml
  bindata/v3.11.0/kube-apiserver/defaultconfig.yaml
  bindata/v3.11.0/kube-apiserver/pod.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/S

#425 make observation func more tolerant
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/configobservation/etcd/observe_etcd.go
  pkg/operator/configobservation/interfaces.go
  pkg/operator/starter.go
Labels: approved, lgtm, size/S

#426 generate and maintain our own kube-apiserver-to-kubelet-signer
  bindata/bootkube/config/bootstrap-config-overrides.yaml
  bindata/bootkube/manifests/configmap-sa-token-signing-certs.yaml
  bindata/bootkube/manifests/secret-initial-kubelet-client.yaml
  bindata/bootkube/manifests/secret-kube-apiserver-to-kubelet-signer.yaml
  pkg/operator/certrotationcontroller/certrotationcontroller.go
  pkg/operator/resourcesynccontroller/resourcesynccontroller.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, lgtm, size/M

#427 speed up leader election
  glide.lock
  glide.yaml
  vendor/github.com/golang/glog/LICENSE
  vendor/github.com/golang/glog/README
  vendor/github.com/golang/glog/glog.go
  vendor/github.com/golang/glog/glog_file.go
  vendor/github.com/golang/glog/glog_test.go
  vendor/github.com/openshift/library-go/pkg/config/leaderelection/leaderelection.go
Labels: approved, lgtm, size/XXL

#430 update deployment for upgrade and install-gather
  manifests/0000_10_kube-apiserver-operator_06_deployment.yaml
Labels: approved, lgtm, size/XS

#432 switch to internal hostname
  test/e2e/user_certs_test.go
Labels: approved, size/S

#434 Wait for unrevisioned certs to be available
  glide.lock
  pkg/operator/operatorclient/staticpod_interface.go
  vendor/github.com/openshift/api/route/v1/generated.pb.go
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/library-go/pkg/assets/create/create_test.go
  vendor/github.com/openshift/library-go/pkg/assets/create/creater.go
  vendor/github.com/openshift/library-go/pkg/config/serving/server.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/node/node_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/revision/revision_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/test_helpers.go
Labels: approved, lgtm, size/XL

#436 emit events for version changes
  glide.lock
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/types_etcd.go
  vendor/github.com/openshift/api/operator/v1/types_serviceca.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/security/v1/generated.proto
  vendor/github.com/openshift/api/security/v1/types.go
  vendor/github.com/openshift/library-go/cmd/crd-schema-gen/generator/generator.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/int32.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
Labels: approved, lgtm, size/L

#435 only watch openshift-etcd for etcd
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/configobservation/etcd/observe_etcd.go
  pkg/operator/configobservation/interfaces.go
  pkg/operator/starter.go
Labels: approved, lgtm, size/S

#437 bindata: add STATIC_POD_VERSION variable to kube-apiserver pod
  bindata/v3.11.0/kube-apiserver/pod.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/S

#439 Add node-selector to namespace
  bindata/bootkube/manifests/00_openshift-kube-apiserver-ns.yaml
  bindata/bootkube/manifests/00_openshift-kube-apiserver-operator-ns.yaml
  bindata/v3.11.0/kube-apiserver/ns.yaml
  manifests/0000_10_kube-apiserver-operator_00_namespace.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: lgtm, size/S

#394 Add a defaultNodeSelector
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/configobservation/interfaces.go
  pkg/operator/configobservation/scheduler/OWNERS
  pkg/operator/configobservation/scheduler/observe_scheduler.go
  pkg/operator/configobservation/scheduler/observer_scheduler_test.go
Labels: approved, lgtm, size/L

#428 fix flaky e2e test
  Makefile
  test/e2e/user_certs_test.go
  test/library/cluster_operator.go
Labels: size/M

#442 Move component to an appropriate upgrade order (kube-apiserver)
  manifests/0000_20_kube-apiserver-operator_00_namespace.yaml
  manifests/0000_20_kube-apiserver-operator_01_config.crd.yaml
  manifests/0000_20_kube-apiserver-operator_01_config.crd.yaml-merge-patch
  manifests/0000_20_kube-apiserver-operator_01_operator.cr.yaml
  manifests/0000_20_kube-apiserver-operator_02_service.yaml
  manifests/0000_20_kube-apiserver-operator_03_configmap.yaml
  manifests/0000_20_kube-apiserver-operator_04_clusterrolebinding.yaml
  manifests/0000_20_kube-apiserver-operator_05_serviceaccount.yaml
  manifests/0000_20_kube-apiserver-operator_06_deployment.yaml
  manifests/0000_20_kube-apiserver-operator_07_clusteroperator.yaml
Labels: approved, lgtm, size/XS

#443 change key for cluster-operator version
  glide.lock
  manifests/0000_20_kube-apiserver-operator_07_clusteroperator.yaml
  pkg/operator/starter.go
  vendor/github.com/davecgh/go-spew/.travis.yml
  vendor/github.com/davecgh/go-spew/LICENSE
  vendor/github.com/davecgh/go-spew/README.md
  vendor/github.com/davecgh/go-spew/spew/bypass.go
  vendor/github.com/davecgh/go-spew/spew/bypasssafe.go
  vendor/github.com/davecgh/go-spew/spew/dump.go
  vendor/github.com/davecgh/go-spew/spew/dump_test.go
  vendor/github.com/davecgh/go-spew/spew/dumpcgo_test.go
  vendor/github.com/davecgh/go-spew/spew/format.go
  vendor/github.com/davecgh/go-spew/spew/format_test.go
  vendor/github.com/davecgh/go-spew/spew/internal_test.go
  vendor/github.com/davecgh/go-spew/spew/internalunsafe_test.go
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/go.mod
  vendor/github.com/ghodss/yaml/go.sum
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/github.com/ghodss/yaml/yaml_go110_test.go
  vendor/github.com/ghodss/yaml/yaml_test.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/library-go/pkg/operator/events/recorder_in_memory.go
  vendor/github.com/openshift/library-go/pkg/operator/loglevel/logging_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/loglevel/logging_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/loglevel/util.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/revision/revision_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/revision/revision_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/version.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
  vendor/gopkg.in/yaml.v2/decode_test.go
  vendor/gopkg.in/yaml.v2/encode.go
  vendor/gopkg.in/yaml.v2/encode_test.go
  vendor/k8s.io/klog/.github/ISSUE_TEMPLATE/bug_report.md
  vendor/k8s.io/klog/.github/ISSUE_TEMPLATE/feature_request.md
  vendor/k8s.io/klog/.github/PULL_REQUEST_TEMPLATE.md
  vendor/k8s.io/klog/.travis.yml
  vendor/k8s.io/klog/CONTRIBUTING.md
  vendor/k8s.io/klog/OWNERS
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/SECURITY_CONTACTS
  vendor/k8s.io/klog/code-of-conduct.md
  vendor/k8s.io/klog/examples/coexist_glog/coexist_glog.go
  vendor/k8s.io/klog/examples/klogr/main.go
  vendor/k8s.io/klog/examples/log_file/usage_log_file.go
  vendor/k8s.io/klog/examples/set_output/usage_set_output.go
  vendor/k8s.io/klog/glog/README.md
  vendor/k8s.io/klog/glog/glog.go
  vendor/k8s.io/klog/glog/glog_test.go
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
  vendor/k8s.io/klog/klog_test.go
  vendor/k8s.io/klog/klogr/README.md
  vendor/k8s.io/klog/klogr/klogr.go
  vendor/k8s.io/klog/klogr/klogr_test.go
Labels: approved, lgtm, size/XXL

#445 manifests: bump loglevel of operator to normal
  manifests/0000_20_kube-apiserver-operator_06_deployment.yaml
Labels: approved, lgtm, size/XS

#447 Make installer controller wait for required resources to exists before running installer pod
  glide.lock
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller_test.go
  vendor/sigs.k8s.io/controller-tools/Gopkg.lock
  vendor/sigs.k8s.io/controller-tools/Gopkg.toml
Labels: approved, lgtm, size/L

#449 Remove a dead ca bundle
  pkg/operator/resourcesynccontroller/resourcesynccontroller.go
Labels: approved, lgtm, size/XS
