Repository openshift/cluster-kube-apiserver-operator, pull requests merged in 2019-08, with the labels that each got.

#542 Bug 1736813: manifests: fix apiVersion for operator config
  manifests/0000_20_kube-apiserver-operator_03_configmap.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#530 Start observing the Proxy object
  glide.lock
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/configobservation/interfaces.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/default.example.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/default.example.mk.help.log
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/operator.example.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/operator.example.mk.help.log
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/images.mk
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/proxy/observe_proxy.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/proxy/observe_proxy_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/google.golang.org/appengine/capability/capability.go
Labels: approved, lgtm, size/L

#531 Bug 1732945: Report infra provider and feature set metrics
  glide.lock
  glide.yaml
  pkg/operator/configmetrics/configmetrics.go
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/starter.go
  vendor/github.com/gobuffalo/envy/.env
  vendor/github.com/gobuffalo/envy/test_env/.env
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#543 BUG 1732377: Fix kube-apiserver image in rest of the files to use hypekube
  bindata/v4.1.0/kube-apiserver/recovery-config.yaml
  bindata/v4.1.0/kube-apiserver/recovery-pod.yaml
  manifests/image-references
  pkg/cmd/render/render.go
  pkg/operator/v410_00_assets/bindata.go
  pkg/recovery/apiserver_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#544 bump library-go for updated cloudprovider observer
  glide.lock
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/SECURITY_CONTACTS
  vendor/k8s.io/klog/go.mod
  vendor/k8s.io/klog/go.sum
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
  vendor/k8s.io/klog/klog_test.go
  vendor/sigs.k8s.io/yaml/.travis.yml
  vendor/sigs.k8s.io/yaml/OWNERS
  vendor/sigs.k8s.io/yaml/README.md
  vendor/sigs.k8s.io/yaml/go.mod
  vendor/sigs.k8s.io/yaml/go.sum
  vendor/sigs.k8s.io/yaml/yaml.go
  vendor/sigs.k8s.io/yaml/yaml_test.go
Labels: approved, lgtm, size/L

#547 Bug 1738284: bump (*) to observe Proxy status instead of spec
  glide.lock
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/README.md
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/go.mod
  vendor/github.com/ghodss/yaml/go.sum
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/github.com/ghodss/yaml/yaml_go110.go
  vendor/github.com/ghodss/yaml/yaml_go110_test.go
  vendor/github.com/ghodss/yaml/yaml_test.go
  vendor/github.com/openshift/api/config/v1/register.go
  vendor/github.com/openshift/api/config/v1/types_operatorhub.go
  vendor/github.com/openshift/api/config/v1/types_proxy.go
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/client-go/glide.lock
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/proxy/observe_proxy.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/proxy/observe_proxy_test.go
  vendor/k8s.io/klog/.github/ISSUE_TEMPLATE/bug_report.md
  vendor/k8s.io/klog/.github/ISSUE_TEMPLATE/feature_request.md
  vendor/k8s.io/klog/.github/PULL_REQUEST_TEMPLATE.md
  vendor/k8s.io/klog/.travis.yml
  vendor/k8s.io/klog/CONTRIBUTING.md
  vendor/k8s.io/klog/OWNERS
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/code-of-conduct.md
  vendor/k8s.io/klog/examples/coexist_glog/coexist_glog.go
  vendor/k8s.io/klog/examples/klogr/main.go
  vendor/k8s.io/klog/examples/log_file/usage_log_file.go
  vendor/k8s.io/klog/examples/set_output/usage_set_output.go
  vendor/k8s.io/klog/glog/README.md
  vendor/k8s.io/klog/glog/glog.go
  vendor/k8s.io/klog/glog/glog_test.go
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
  vendor/k8s.io/klog/klog_test.go
  vendor/k8s.io/klog/klogr/README.md
  vendor/k8s.io/klog/klogr/klogr.go
  vendor/k8s.io/klog/klogr/klogr_test.go
  vendor/sigs.k8s.io/yaml/.travis.yml
  vendor/sigs.k8s.io/yaml/OWNERS
  vendor/sigs.k8s.io/yaml/README.md
  vendor/sigs.k8s.io/yaml/go.mod
  vendor/sigs.k8s.io/yaml/go.sum
  vendor/sigs.k8s.io/yaml/yaml.go
  vendor/sigs.k8s.io/yaml/yaml_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XXL

#545 Bug 1732945: Fallback to platform type on 4.1 infra metrics
  pkg/operator/configmetrics/configmetrics.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S

#534 Bug 1733232: Fix kube-apiserver-to-kubelet-signer validity
  pkg/operator/certrotationcontroller/certrotationcontroller.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#550 Bug 1737683: Sort the EnvVar from Proxy string map
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#555 bootstrap: set terminationMessagePolicy: FallbackToLogsOnError
  bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml
Labels: approved, lgtm, size/XS

#556 Bug 1734284: manifests: deploy kube-apiserver service monitor in the correct namespace
  manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#552 Inject kube-apiserver pods trust stores with trusted ca bundle
  bindata/v4.1.0/kube-apiserver/pod.yaml
  bindata/v4.1.0/kube-apiserver/trusted-ca-cm.yaml
  pkg/operator/starter.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, lgtm, size/M

#558 bootstrap: log to /var/log/bootstrap-control-plane/kube-apiserver.log
  bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml
Labels: approved, lgtm, size/XS

#551 updateMakefile to fix 'make images'
  Makefile
Labels: approved, lgtm, size/S

#559 only use the internalIP to speak to kubelets
  bindata/v4.1.0/kube-apiserver/defaultconfig.yaml
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, lgtm, size/XS
