Repository openshift/cluster-kube-apiserver-operator, pull requests merged in 2019-10, with the labels that each got.

#579 Add shared encryption controllers logic
  pkg/operator/encryption/shared_encryption.go
Labels: approved, lgtm, size/XL

#580 encryption: split shared code
  pkg/operator/encryption/controllers.go
  pkg/operator/encryption/crypt.go
  pkg/operator/encryption/secrets.go
  pkg/operator/encryption/shared_encryption.go
  pkg/operator/encryption/state.go
  pkg/operator/encryption/types.go
Labels: approved, lgtm, size/XXL

#569 Bug 1731228: add alert when feature set is set
  manifests/0000_90_kube-apiserver-operator_03_servicemonitor.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#583 encryption: add test helpers
  pkg/operator/encryption/helpers_test.go
Labels: approved, lgtm, size/L

#585 encryption: add migration controller
  pkg/operator/encryption/helpers_test.go
  pkg/operator/encryption/migration_controller.go
  pkg/operator/encryption/migration_controller_test.go
Labels: approved, lgtm, size/XL

#588 encryption: add prune controller
  pkg/operator/encryption/helpers_test.go
  pkg/operator/encryption/key_controller.go
  pkg/operator/encryption/key_controller_test.go
  pkg/operator/encryption/migration_controller.go
  pkg/operator/encryption/migration_controller_test.go
  pkg/operator/encryption/prune_controller.go
  pkg/operator/encryption/prune_controller_test.go
  pkg/operator/encryption/state.go
  pkg/operator/encryption/state_controller.go
  pkg/operator/encryption/state_controller_test.go
  pkg/operator/encryption/state_test.go
Labels: approved, lgtm, size/XXL

#596 Steal dev+debugging section from kcm-o
  README.md
Labels: approved, lgtm, size/M

#593 adds encryption config observer
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/configobservation/interfaces.go
  pkg/operator/encryption/observe_encryption_config.go
  pkg/operator/encryption/observe_encryption_config_test.go
Labels: approved, lgtm, size/L

#591 encryption: fix encryption bootstrap logic
  pkg/operator/encryption/controllers.go
  pkg/operator/encryption/key_controller.go
  pkg/operator/encryption/key_controller_test.go
  pkg/operator/encryption/migration_controller.go
  pkg/operator/encryption/migration_controller_test.go
  pkg/operator/encryption/prune_controller.go
  pkg/operator/encryption/prune_controller_test.go
  pkg/operator/encryption/state.go
  pkg/operator/encryption/state_controller.go
  pkg/operator/encryption/state_controller_test.go
Labels: approved, lgtm, size/L

#597 encryption: rewrite migration loop
  pkg/operator/encryption/helpers_test.go
  pkg/operator/encryption/migration_controller.go
  pkg/operator/encryption/migration_controller_test.go
  pkg/operator/encryption/secrets.go
Labels: approved, lgtm, size/L

#592 encryption: wire controllers into operator startup
  pkg/operator/starter.go
Labels: approved, lgtm, size/M

#600 encryption: simplify informer setup code
  pkg/operator/encryption/controllers.go
  pkg/operator/encryption/key_controller.go
  pkg/operator/encryption/migration_controller.go
  pkg/operator/encryption/prune_controller.go
  pkg/operator/encryption/state_controller.go
Labels: approved, lgtm, size/M

#601 encryption: decouple secret names from config
  pkg/operator/encryption/key_controller.go
  pkg/operator/encryption/prune_controller.go
  pkg/operator/encryption/prune_controller_test.go
  pkg/operator/encryption/secrets.go
  pkg/operator/encryption/state.go
  pkg/operator/encryption/state_test.go
  pkg/operator/encryption/types.go
Labels: approved, lgtm, size/M

#599 add max-in-flight
  bindata/v4.1.0/kube-apiserver/defaultconfig.yaml
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, lgtm, size/S

#606 encryption: detangle into packages
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/encryption/controllers.go
  pkg/operator/encryption/controllers/controller.go
  pkg/operator/encryption/controllers/helpers_test.go
  pkg/operator/encryption/controllers/key_controller.go
  pkg/operator/encryption/controllers/key_controller_test.go
  pkg/operator/encryption/controllers/migration_controller.go
  pkg/operator/encryption/controllers/migration_controller_test.go
  pkg/operator/encryption/controllers/prune_controller.go
  pkg/operator/encryption/controllers/prune_controller_test.go
  pkg/operator/encryption/controllers/state_controller.go
  pkg/operator/encryption/controllers/state_controller_test.go
  pkg/operator/encryption/crypt.go
  pkg/operator/encryption/crypto/keys.go
  pkg/operator/encryption/encryptionconfig/config.go
  pkg/operator/encryption/encryptionconfig/config_test.go
  pkg/operator/encryption/encryptionconfig/secret.go
  pkg/operator/encryption/observer/observe_encryption_config.go
  pkg/operator/encryption/observer/observe_encryption_config_test.go
  pkg/operator/encryption/secrets.go
  pkg/operator/encryption/secrets/secrets.go
  pkg/operator/encryption/secrets/secrets_test.go
  pkg/operator/encryption/secrets/types.go
  pkg/operator/encryption/state.go
  pkg/operator/encryption/state/helpers.go
  pkg/operator/encryption/state/types.go
  pkg/operator/encryption/statemachine/operand.go
  pkg/operator/encryption/statemachine/transition.go
  pkg/operator/encryption/statemachine/transition_test.go
  pkg/operator/encryption/testing/helpers.go
  pkg/operator/encryption/types.go
  pkg/operator/starter.go
Labels: approved, lgtm, size/XXL

#609 encryption: fix encryption config sync to target namespace
  pkg/operator/encryption/controllers.go
  pkg/operator/encryption/encryptionconfig/config.go
  pkg/operator/encryption/encryptionconfig/config_test.go
Labels: approved, lgtm, size/M

#611 encryption: abstract encryption-config deployment mechanism
  pkg/operator/encryption/controllers.go
  pkg/operator/encryption/controllers/controller.go
  pkg/operator/encryption/controllers/key_controller.go
  pkg/operator/encryption/controllers/key_controller_test.go
  pkg/operator/encryption/controllers/migration_controller.go
  pkg/operator/encryption/controllers/migration_controller_test.go
  pkg/operator/encryption/controllers/prune_controller.go
  pkg/operator/encryption/controllers/prune_controller_test.go
  pkg/operator/encryption/controllers/state_controller.go
  pkg/operator/encryption/controllers/state_controller_test.go
  pkg/operator/encryption/deployer/staticpod.go
  pkg/operator/encryption/statemachine/operand.go
  pkg/operator/encryption/statemachine/transition.go
  pkg/operator/starter.go
Labels: approved, lgtm, size/L

#610 Encryption events
  pkg/operator/encryption/controllers/key_controller.go
  pkg/operator/encryption/controllers/key_controller_test.go
  pkg/operator/encryption/controllers/migration_controller.go
  pkg/operator/encryption/controllers/migration_controller_test.go
  pkg/operator/encryption/controllers/prune_controller.go
  pkg/operator/encryption/controllers/prune_controller_test.go
  pkg/operator/encryption/controllers/state_controller.go
  pkg/operator/encryption/controllers/state_controller_test.go
  pkg/operator/encryption/testing/helpers.go
  pkg/operator/encryption/testing/recorder_wrapper.go
  vendor/github.com/openshift/library-go/pkg/operator/events/eventstesting/recorder_testing.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#615 adds an e2e happy path test case for etcd encryption
  Makefile
  test/e2e/encryption_test.go
  test/library/client.go
  test/library/encryption/assertion.go
  test/library/encryption/e_log.go
  test/library/encryption/etcd_client.go
  test/library/encryption/helpers.go
Labels: approved, lgtm, size/L

#614 encryption: e2e w/ real controllers against real cluster with fake deployer
  pkg/operator/encryption/controllers.go
  pkg/operator/encryption/controllers/migration_controller.go
  pkg/operator/starter.go
  test/e2e/encryption_quick_test.go
Labels: approved, lgtm, size/XL

#618 Encryption e2e tests rotation
  Makefile
  test/e2e-encryption/encryption_test.go
  test/e2e-encryption/main_test.go
  test/e2e/encryption_test.go
  test/library/encryption/assertion.go
  test/library/encryption/helpers.go
Labels: approved, lgtm, size/L

#623 Improves TestEncryptionTurnOnAndOff and TestEncryptionRotation
  test/e2e-encryption/encryption_test.go
  test/library/encryption/assertion.go
  test/library/encryption/helpers.go
Labels: approved, lgtm, size/L

#621 Improves TestEncryptionTurnOnAndOff scenario
  test/e2e-encryption/encryption_test.go
  test/library/encryption/assertion.go
  test/library/encryption/helpers.go
Labels: approved, do-not-merge/hold, lgtm, size/M

#626 add privilege to operator init container
  bindata/v4.1.0/kube-apiserver/pod.yaml
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#627 make whole kube-apiserver pod privileged
  bindata/v4.1.0/kube-apiserver/pod.yaml
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#629 Properly set pod as privileged
  bindata/v4.1.0/kube-apiserver/pod.yaml
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, lgtm, size/S

#628 uses e2e encryption code from library-go
  go.mod
  go.sum
  test/e2e-encryption/encryption_test.go
  test/library/encryption/assertion.go
  test/library/encryption/helpers.go
  test/library/encryption/scenarios.go
  vendor/github.com/openshift/library-go/test/library/client.go
  vendor/github.com/openshift/library-go/test/library/encryption/assertion.go
  vendor/github.com/openshift/library-go/test/library/encryption/e_log.go
  vendor/github.com/openshift/library-go/test/library/encryption/etcd_client.go
  vendor/github.com/openshift/library-go/test/library/encryption/helpers.go
  vendor/github.com/openshift/library-go/test/library/library.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#625 Add alert for deprecated apis
  .gitignore
  manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml
Labels: approved, lgtm, size/M

#581 Add an observer for TLS Security Profile
  go.mod
  go.sum
  pkg/operator/configobservation/apiserver/observe_apiserver.go
  pkg/operator/configobservation/apiserver/observe_apiserver_test.go
  pkg/operator/configobservation/apiserver/observe_cors.go
  pkg/operator/configobservation/apiserver/observe_cors_test.go
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/configobservation/interfaces.go
  vendor/github.com/certifi/gocertifi/gen.go
  vendor/github.com/gonum/matrix/gendoc.go
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/apiserver/observe_tlssecurityprofile.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/text/width/gen.go
  vendor/golang.org/x/text/width/gen_common.go
  vendor/golang.org/x/text/width/gen_trieval.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#630 metrics: report the control plane architecture
  pkg/operator/configmetrics/configmetrics.go
Labels: approved, lgtm, size/S

#631 adjust e2e encryption tests to recent changes in library-go
  go.mod
  go.sum
  test/e2e-encryption/encryption_test.go
  test/library/encryption/assertion.go
  test/library/encryption/helpers.go
  vendor/github.com/certifi/gocertifi/gen.go
  vendor/github.com/gonum/matrix/gendoc.go
  vendor/github.com/openshift/library-go/test/library/encryption/assertion.go
  vendor/github.com/openshift/library-go/test/library/encryption/helpers.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/text/width/gen.go
  vendor/golang.org/x/text/width/gen_common.go
  vendor/golang.org/x/text/width/gen_trieval.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#634 Revert "metrics: report the control plane architecture"
  pkg/operator/configmetrics/configmetrics.go
Labels: approved, lgtm, size/S
