Repository openshift/cluster-kube-apiserver-operator, pull requests merged in 2019-05, with the labels that each got.

#450 update simplified graph
  pkg/cmd/resourcegraph/resourcegraph.go
Labels: approved, lgtm, size/L

#451 Add missing revision suffix when checking for required resources
  glide.lock
  vendor/github.com/openshift/api/security/v1/generated.proto
  vendor/github.com/openshift/api/security/v1/types.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
Labels: approved, lgtm, size/L

#452 bindata: fix expansion of POD_NAMESPACE in cert-signer
  bindata/v3.11.0/kube-apiserver/pod.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#453 move SCC initialization to kas-o
  manifests/0000_20_kube-apiserver-operator_00_scc-anyuid.json
  manifests/0000_20_kube-apiserver-operator_00_scc-hostaccess.json
  manifests/0000_20_kube-apiserver-operator_00_scc-hostmount-anyuid.json
  manifests/0000_20_kube-apiserver-operator_00_scc-hostnetwork.json
  manifests/0000_20_kube-apiserver-operator_00_scc-nonroot.json
  manifests/0000_20_kube-apiserver-operator_00_scc-privileged.json
  manifests/0000_20_kube-apiserver-operator_00_scc-restricted.json
Labels: approved, lgtm, size/L

#456 Update library-go
  glide.lock
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/cloudprovider/observe_cloudprovider_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/certsyncpod/certsync_cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
Labels: approved, lgtm, size/M

#461 generate certificates synchronously and do not start a kube-apiserver
  Dockerfile
  Dockerfile.rhel7
  bindata/v3.11.0/kube-apiserver/recovery-config.yaml
  bindata/v3.11.0/kube-apiserver/recovery-pod.yaml
  cmd/cluster-kube-apiserver-operator/main.go
  glide.lock
  pkg/cmd/fixcerts/carry/kubecontrollermanager/certrotationcontroller/kubecontrollermanagercertrotation.go
  pkg/cmd/fixcerts/carry/kubecontrollermanager/operatorclient/interfaces.go
  pkg/cmd/fixcerts/fixcerts.go
  pkg/cmd/fixcerts/fixcerts_test.go
  pkg/cmd/recoveryapiserver/create.go
  pkg/cmd/recoveryapiserver/destroy.go
  pkg/cmd/recoveryapiserver/lib.go
  pkg/cmd/recoveryapiserver/recoveryapiserver.go
  pkg/operator/certrotationcontroller/certrotationcontroller.go
  pkg/operator/starter.go
  pkg/operator/v311_00_assets/bindata.go
  pkg/recovery/apiserver.go
  pkg/recovery/apiserver_test.go
  pkg/recovery/helpers.go
  pkg/test/assets_test.go
  vendor/github.com/openshift/api/authorization/v1/generated.proto
  vendor/github.com/openshift/api/authorization/v1/types.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
  vendor/k8s.io/klog/klog.go
Labels: approved, lgtm, size/XXL

#462 remove dependency on the service-ca from kube-apiserver
  bindata/v3.11.0/kube-apiserver/svc.yaml
  pkg/operator/starter.go
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#463 require storage URLs before installing
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
Labels: approved, lgtm, size/L

#454 Bug 1705649 : Cluster with halted master did not reschedule operators after 5m of being down
  manifests/0000_20_kube-apiserver-operator_06_deployment.yaml
Labels: approved, lgtm, size/S

#465 Use internal url everywhere
  glide.lock
  pkg/operator/certrotationcontroller/externalloadbalancer.go
  pkg/operator/certrotationcontroller/internalloadbalancer.go
  test/e2e/user_certs_test.go
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/README.md
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/go.mod
  vendor/github.com/ghodss/yaml/go.sum
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/github.com/ghodss/yaml/yaml_go110.go
  vendor/github.com/ghodss/yaml/yaml_go110_test.go
  vendor/github.com/ghodss/yaml/yaml_test.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/gopkg.in/yaml.v2/.travis.yml
  vendor/gopkg.in/yaml.v2/LICENSE
  vendor/gopkg.in/yaml.v2/NOTICE
  vendor/gopkg.in/yaml.v2/README.md
  vendor/gopkg.in/yaml.v2/apic.go
  vendor/gopkg.in/yaml.v2/decode.go
  vendor/gopkg.in/yaml.v2/decode_test.go
  vendor/gopkg.in/yaml.v2/emitterc.go
  vendor/gopkg.in/yaml.v2/encode.go
  vendor/gopkg.in/yaml.v2/encode_test.go
  vendor/gopkg.in/yaml.v2/example_embedded_test.go
  vendor/gopkg.in/yaml.v2/go.mod
  vendor/gopkg.in/yaml.v2/readerc.go
  vendor/gopkg.in/yaml.v2/resolve.go
  vendor/gopkg.in/yaml.v2/scannerc.go
  vendor/gopkg.in/yaml.v2/sorter.go
  vendor/gopkg.in/yaml.v2/writerc.go
  vendor/gopkg.in/yaml.v2/yaml.go
  vendor/gopkg.in/yaml.v2/yamlh.go
Labels: approved, lgtm, size/XXL

#469 Bug 1707839: regenerate-certificates needs to address derivative resources
  cmd/cluster-kube-apiserver-operator/main.go
  pkg/cmd/fixcerts/fixcerts_test.go
  pkg/cmd/recoveryapiserver/recoveryapiserver.go
  pkg/cmd/regeneratecerts/carry/kubecontrollermanager/certrotationcontroller/kubecontrollermanagercertrotation.go
  pkg/cmd/regeneratecerts/carry/kubecontrollermanager/operatorclient/interfaces.go
  pkg/cmd/regeneratecerts/carry/kubecontrollermanager/targetconfigcontroller/targetconfigcontroller.go
  pkg/cmd/regeneratecerts/regenerate_certificates.go
  pkg/cmd/regeneratecerts/regenerate_certificates_test.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, lgtm, size/L

#464 Bug 1707877: Use internal url only for internal load balancer
  pkg/operator/certrotationcontroller/externalloadbalancer.go
  test/e2e/user_certs_test.go
Labels: approved, lgtm, size/XS

#471 Fix csr-signer location to target namespace
  pkg/cmd/regeneratecerts/regenerate_certificates.go
Labels: approved, lgtm, size/XS

#472 Make recovery system:admin part of system:masters group
  pkg/recovery/apiserver.go
Labels: approved, lgtm, size/S

#468 move v3.11.0 to v4.1.0
  Makefile
  bindata/v4.1.0/kube-apiserver/cm.yaml
  bindata/v4.1.0/kube-apiserver/defaultconfig.yaml
  bindata/v4.1.0/kube-apiserver/kubeconfig-cm.yaml
  bindata/v4.1.0/kube-apiserver/ns.yaml
  bindata/v4.1.0/kube-apiserver/pod-cm.yaml
  bindata/v4.1.0/kube-apiserver/pod.yaml
  bindata/v4.1.0/kube-apiserver/recovery-config.yaml
  bindata/v4.1.0/kube-apiserver/recovery-pod.yaml
  bindata/v4.1.0/kube-apiserver/svc.yaml
  pkg/cmd/render/render.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/v410_00_assets/bindata.go
  pkg/recovery/apiserver.go
Labels: approved, lgtm, size/L

#473 Bug 1709869: tls: add openshift service names
  pkg/operator/certrotationcontroller/servicehostname.go
  test/e2e/user_certs_test.go
Labels: approved, lgtm, size/S

#474 certrotationcontroller: prevent panic when setting loadbalancer hostname
  pkg/operator/certrotationcontroller/externalloadbalancer.go
  pkg/operator/certrotationcontroller/internalloadbalancer.go
Labels: approved, lgtm, size/XS

#476 Bug 1710293 - Don't explicitly set storagePrefix to use the default value
  bindata/v3.11.0/kube-apiserver/defaultconfig.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#475 Bug 1710293 - Don't explicitly set storagePrefix to use the default value
  bindata/v4.1.0/kube-apiserver/defaultconfig.yaml
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#477 Bug 1711185 - Remove storage prefix to default to correct one for kube resources in recovery apisever
  bindata/v4.1.0/kube-apiserver/recovery-config.yaml
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, lgtm, priority/critical-urgent, size/XS

#478 Bug 1711185 - [4.1] Remove storage prefix to default to correct one for kube resources in recovery apisever
  bindata/v3.11.0/kube-apiserver/recovery-config.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, priority/critical-urgent, size/XS

#481 Bug 1711431: user-serving-cert secret not being installed
  pkg/operator/configobservation/apiserver/observe_apiserver.go
  pkg/operator/configobservation/apiserver/observe_apiserver_test.go
Labels: approved, lgtm, size/XS
