Repository openshift/cluster-kube-apiserver-operator, pull requests merged in 2019-06, with the labels that each got.

#493 Set short rotation period
  bindata/bootkube/manifests/configmap-unsupported-cert-rotation.yaml
Labels: approved, lgtm, size/XS

#495 Revert "Set short rotation period"
  bindata/bootkube/manifests/configmap-unsupported-cert-rotation.yaml
Labels: approved, lgtm, size/XS

#494 Bug 1716426 : Fix admission plugin configuration
  bindata/v4.1.0/kube-apiserver/defaultconfig.yaml
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/configobservation/network/observe_network.go
  pkg/operator/configobservation/network/observe_network_test.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, lgtm, size/L

#492 Bug 1716622: start informers after lister registration
  glide.lock
  glide.yaml
  vendor/github.com/openshift/api/Dockerfile.build
  vendor/github.com/openshift/api/OWNERS
  vendor/github.com/openshift/api/build/v1/generated.proto
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/build/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/hack/update-protobuf.sh
  vendor/github.com/openshift/api/security/v1/generated.proto
  vendor/github.com/openshift/api/security/v1/types.go
  vendor/github.com/openshift/library-go/glide.lock
  vendor/github.com/openshift/library-go/glide.yaml
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/rbac.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/certsyncpod/certsync_cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/certsyncpod/certsync_controller.go
Labels: approved, lgtm, size/L

#497 Never shorten signers
  pkg/operator/certrotationcontroller/certrotationcontroller.go
Labels: approved, lgtm, size/M

#496 Bug 1716426: Backport admission controller fixes
  bindata/v3.11.0/kube-apiserver/defaultconfig.yaml
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/configobservation/network/observe_network.go
  pkg/operator/configobservation/network/observe_network_test.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/L

#485 docs: Update default config url in Readme file
  README.md
Labels: approved, lgtm, ok-to-test, size/XS

#499 Bug 1718052: Do not log OAuth tokens in audit logs
  bindata/v4.1.0/kube-apiserver/defaultconfig.yaml
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#506 sets feature-gates in bootstrap-config-overrides for kube-apiserver-o…
  bindata/bootkube/config/bootstrap-config-overrides.yaml
  pkg/cmd/render/render_test.go
Labels: approved, lgtm, size/L

#501 manifests: add apiserver service monitor
  manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml
Labels: approved, lgtm, size/M

#502 manifests: monitor openshift-kube-apiserver namespace
  bindata/bootkube/manifests/00_openshift-kube-apiserver-ns.yaml
  bindata/v4.1.0/kube-apiserver/ns.yaml
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#507 Switch to go 1.12
  Dockerfile
  Dockerfile.rhel7
Labels: approved, lgtm, size/XS

#510 allow --new-image for step 1 of 7
  pkg/cmd/render/render.go
Labels: approved, lgtm, size/S

#511 switch to use hyperkube
  bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml
  bindata/v4.1.0/kube-apiserver/pod.yaml
  manifests/0000_20_kube-apiserver-operator_06_deployment.yaml
  pkg/cmd/render/render.go
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, lgtm, size/S

#512 use the new image since the installer is setting it correctly
  pkg/cmd/render/render.go
Labels: approved, lgtm, size/XS

#513 remove temporary image flag for switch images
  pkg/cmd/render/render.go
Labels: approved, lgtm, size/S
