Repository openshift/cluster-kube-apiserver-operator, pull requests merged in 2019-09, with the labels that each got.

#557 Bug 1714158: Prevent cert-syncer to act on stale data
  glide.lock
  pkg/operator/configobservation/apiserver/observe_apiserver.go
  pkg/operator/configobservation/apiserver/observe_apiserver_test.go
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/staleconditions/remove_stale_conditions.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/certsyncpod/certsync_cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/certsyncpod/certsync_controller.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/apiserver.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_handler.go
  vendor/k8s.io/apiextensions-apiserver/test/integration/change_test.go
  vendor/k8s.io/apiextensions-apiserver/test/integration/scope_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XL

#560 update recovery tool location for kcm CSR location change
  pkg/cmd/regeneratecerts/regenerate_certificates.go
Labels: approved, lgtm, size/XS

#566 Add stub test-e2e-encryption suite
  Makefile
  test/e2e-encryption/encryption_test.go
Labels: approved, lgtm, size/S

#564 Bug 1751841: null externalip policy should be default-deny
  pkg/operator/configobservation/network/observe_network.go
  pkg/operator/configobservation/network/observe_network_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#567 Bug 1753156: Fix the trusted-ca bundle filename
  bindata/v4.1.0/kube-apiserver/pod.yaml
  pkg/operator/starter.go
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S
