Repository openshift/cluster-kube-apiserver-operator, pull requests merged in 2019-02, with the labels that each got.

#236 tighten kube-apiserver names
  bindata/v3.11.0/kube-apiserver/operator-config.yaml
  manifests/0000_10_kube-apiserver-operator_02_service.yaml
  manifests/0000_10_kube-apiserver-operator_03_configmap.yaml
  manifests/0000_10_kube-apiserver-operator_04_clusterrolebinding.yaml
  manifests/0000_10_kube-apiserver-operator_05_serviceaccount.yaml
  manifests/0000_10_kube-apiserver-operator_06_deployment.yaml
  manifests/0000_10_kube-apiserver-operator_07_clusteroperator.yaml
  manifests/0000_90_kube-apiserver-operator_03_servicemonitor.yaml
  pkg/operator/operatorclient/staticpod_interface.go
  pkg/operator/starter.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/M

#243 bump library-go
  glide.lock
  vendor/bitbucket.org/ww/goautoneg/.hg_archival.txt
  vendor/github.com/openshift/library-go/pkg/assets/create/OWNERS
  vendor/github.com/openshift/library-go/pkg/assets/create/create_test.go
  vendor/github.com/openshift/library-go/pkg/assets/create/creater.go
  vendor/github.com/openshift/library-go/pkg/assets/create/testdata/0000_10_kube-apiserver-operator_01_config.crd.yaml
  vendor/github.com/openshift/library-go/pkg/assets/create/testdata/00_openshift-kube-apiserver-ns.yaml
  vendor/github.com/openshift/library-go/pkg/assets/create/testdata/configmap-aggregator-client-ca.yaml
  vendor/github.com/openshift/library-go/pkg/assets/create/testdata/operator-config.yaml
  vendor/github.com/openshift/library-go/pkg/assets/create/testdata/secret-aggregator-client.yaml
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/bindata/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/manifests/installer-pod.yaml
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd_test.go
Labels: approved, lgtm, size/XXL

#241 remove cruft and depend on cluster-config-operator
  bindata/bootkube/manifests/00_openshift-config-managed-ns.yaml
  bindata/bootkube/manifests/00_openshift-config-ns.yaml
  manifests/0000_10_kube-apiserver-operator_01_config.crd.old.yaml
  pkg/operator/configobservation/auth/auth_metadata.go
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/configobservation/images/observe_images.go
  pkg/operator/configobservation/images/observe_images_test.go
  pkg/operator/configobservation/interfaces.go
Labels: approved, lgtm, size/L

#246 switch network admission plugin name
  bindata/bootkube/config/bootstrap-config-overrides.yaml
  bindata/v3.11.0/kube-apiserver/defaultconfig.yaml
  pkg/operator/configobservation/network/observe_network.go
  pkg/operator/configobservation/network/observe_network_test.go
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/S

#244 move all irreplaceable content to openshift-config
  bindata/bootkube/manifests/configmap-initial-sa-token-signing-certs.yaml
  bindata/bootkube/manifests/secret-initial-kubelet-client.yaml
  bindata/bootkube/manifests/secret-initial-serving-cert.yaml
  pkg/operator/resourcesynccontroller/resourcesynccontroller.go
Labels: approved, lgtm, size/M

#248 fix namespace for cm and scheduler client ca
  pkg/operator/certrotationcontroller/certrotationcontroller.go
Labels: approved, lgtm, size/S

#252 Observe apiserver config
  pkg/operator/configobservation/apiserver/observe_apiserver.go
  pkg/operator/configobservation/apiserver/observe_apiserver_test.go
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/configobservation/interfaces.go
  pkg/operator/starter.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, lgtm, size/XL

#230 observe apiserver config
  pkg/operator/configobservation/apiserver/observe_apiserver.go
  pkg/operator/configobservation/apiserver/observe_apiserver_test.go
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/configobservation/interfaces.go
  pkg/operator/starter.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: do-not-merge/hold, size/XL

#255 Fix log spamming by auth and apiserver observer
  pkg/operator/configobservation/apiserver/observe_apiserver.go
  pkg/operator/configobservation/auth/auth_metadata.go
Labels: approved, lgtm, size/XS

#258 sa tokens
  bindata/v3.11.0/kube-apiserver/defaultconfig.yaml
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/configobservation/satokencerts/observe_satokencerts.go
  pkg/operator/resourcesynccontroller/resourcesynccontroller.go
  pkg/operator/starter.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/L

#247 start requiring kubelet trust
  bindata/v3.11.0/kube-apiserver/defaultconfig.yaml
  pkg/operator/resourcesynccontroller/resourcesynccontroller.go
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/S

#256 operator: remove openshift prefix from pod name
  bindata/v3.11.0/kube-apiserver/pod.yaml
  pkg/operator/starter.go
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/S

#263 explain where kube-apiserver resources come from
  pkg/operator/reactionchain/interfaces.go
  pkg/operator/reactionchain/reactionchain.go
Labels: approved, lgtm, size/L

#264 correct set version information
  glide.lock
  manifests/0000_10_kube-apiserver-operator_03_version-mapping.yaml
  manifests/0000_10_kube-apiserver-operator_06_deployment.yaml
  pkg/cmd/resourcegraph/resourcegraph.go
  pkg/operator/reactionchain/interfaces.go
  pkg/operator/reactionchain/reactionchain.go
  pkg/operator/starter.go
  vendor/github.com/davecgh/go-spew/.travis.yml
  vendor/github.com/davecgh/go-spew/LICENSE
  vendor/github.com/davecgh/go-spew/README.md
  vendor/github.com/davecgh/go-spew/spew/bypass.go
  vendor/github.com/davecgh/go-spew/spew/bypasssafe.go
  vendor/github.com/davecgh/go-spew/spew/dump.go
  vendor/github.com/davecgh/go-spew/spew/dump_test.go
  vendor/github.com/davecgh/go-spew/spew/dumpcgo_test.go
  vendor/github.com/davecgh/go-spew/spew/format.go
  vendor/github.com/davecgh/go-spew/spew/format_test.go
  vendor/github.com/davecgh/go-spew/spew/internal_test.go
  vendor/github.com/davecgh/go-spew/spew/internalunsafe_test.go
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/README.md
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/go.mod
  vendor/github.com/ghodss/yaml/go.sum
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/github.com/ghodss/yaml/yaml_go110.go
  vendor/github.com/ghodss/yaml/yaml_go110_test.go
  vendor/github.com/ghodss/yaml/yaml_test.go
  vendor/github.com/gonum/graph/.github/ISSUE_TEMPLATE.md
  vendor/github.com/gonum/graph/.github/PULL_REQUEST_TEMPLATE.md
  vendor/github.com/gonum/graph/README.md
  vendor/github.com/openshift/library-go/glide.lock
  vendor/github.com/openshift/library-go/glide.yaml
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcegraph/coordinates.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcegraph/interface.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcegraph/resource.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcegraph/resources.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/status/version.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
Labels: approved, do-not-merge/hold, size/XXL

#271 Simplify conditions
  glide.lock
  pkg/cmd/render/render.go
  vendor/github.com/openshift/library-go/pkg/operator/render/options/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apps.go
  vendor/github.com/openshift/library-go/pkg/operator/status/condition.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller_test.go
Labels: approved, lgtm, size/L

#272 targetconfigcontroller: emit warning when management state is set to unknown value
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, lgtm, size/XS

#260 stop serving oauth config
  bindata/bootkube/config/bootstrap-config-overrides.yaml
  bindata/bootkube/config/config-overrides.yaml
  bindata/v3.11.0/kube-apiserver/defaultconfig.yaml
  pkg/operator/targetconfigcontroller/config_restriction.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/M

#277 fix file content race
  glide.lock
  vendor/github.com/openshift/api/config/v1/types_console.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/library-go/Makefile
  vendor/github.com/openshift/library-go/cmd/crd-schema-gen/generator/generator.go
  vendor/github.com/openshift/library-go/cmd/crd-schema-gen/main.go
  vendor/github.com/openshift/library-go/glide.lock
  vendor/github.com/openshift/library-go/glide.yaml
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/flags.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer_polling.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer_polling_test.go
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/backingresource/backing_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/revision/revision_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
Labels: approved, lgtm, size/XL

#280 honor both the old and new csr signers until kcm switches
  bindata/bootkube/manifests/configmap-initial-kubelet-serving-ca.yaml
Labels: approved, lgtm, size/XS

#281 add trust for new admin kubeconfig client-ca
  bindata/bootkube/manifests/configmap-initial-kube-apiserver-admin-kubeconfig-client-ca.yaml
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, lgtm, size/S

#278 targetconfig: switch pull policy to if not present
  manifests/0000_10_kube-apiserver-operator_06_deployment.yaml
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, lgtm, size/XS

#282 adopt signers from installer for rotating serving certs
  bindata/bootkube/manifests/secret-loadbalancer-serving-signer.yaml
  bindata/bootkube/manifests/secret-localhost-serving-signer.yaml
  bindata/bootkube/manifests/secret-service-network-serving-signer.yaml
  glide.lock
  pkg/operator/certrotationcontroller/certrotationcontroller.go
  vendor/github.com/openshift/library-go/pkg/assets/template.go
  vendor/golang.org/x/tools/go/gcexportdata/example_test.go
  vendor/golang.org/x/tools/internal/lsp/cache/view.go
  vendor/golang.org/x/tools/internal/lsp/lsp_test.go
  vendor/golang.org/x/tools/internal/lsp/protocol/text.go
  vendor/golang.org/x/tools/internal/lsp/server.go
Labels: approved, size/L

#286 Dynamically set hostnames
  bindata/bootkube/manifests/configmap-initial-kube-apiserver-admin-kubeconfig-client-ca.yaml
  bindata/bootkube/manifests/configmap-initial-kubelet-serving-ca.yaml
  glide.lock
  glide.yaml
  manifests/0000_10_kube-apiserver-operator_06_deployment.yaml
  pkg/operator/certrotationcontroller/certrotationcontroller.go
  pkg/operator/certrotationcontroller/dynamic_serving.go
  pkg/operator/certrotationcontroller/loadbalancer.go
  pkg/operator/certrotationcontroller/servicehostname.go
  pkg/operator/configobservation/network/observe_network_test.go
  pkg/operator/starter.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  vendor/github.com/apparentlymart/go-cidr/.travis.yml
  vendor/github.com/apparentlymart/go-cidr/LICENSE
  vendor/github.com/apparentlymart/go-cidr/cidr/cidr.go
  vendor/github.com/apparentlymart/go-cidr/cidr/cidr_test.go
  vendor/github.com/apparentlymart/go-cidr/cidr/wrangling.go
  vendor/github.com/apparentlymart/go-cidr/go.mod
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target_test.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/rbac.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
Labels: approved, lgtm, size/XXL

#288 trust the new initial kubelet client CA
  bindata/bootkube/manifests/configmap-initial-kubelet-client-ca.yaml
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, lgtm, size/S

#279 switch to new aggregator cert
  bindata/bootkube/config/bootstrap-config-overrides.yaml
  bindata/bootkube/config/config-overrides.yaml
  bindata/bootkube/manifests/configmap-initial-aggregator-client-ca.yaml
Labels: approved, lgtm, size/S

#290 provide ca bundle for trusting the kube-apiserver
  bindata/bootkube/manifests/configmap-initial-kube-apiserver-serving-ca.yaml
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, size/M

#295 trust csr signer to serve kubelets
  bindata/bootkube/manifests/configmap-initial-kubelet-serving-ca.yaml
Labels: approved, lgtm, size/XS

#292 adopt aggregator-signer
  bindata/bootkube/manifests/configmap-initial-aggregator-client-ca.yaml
  bindata/bootkube/manifests/secret-aggregator-client-signer.yaml
  glide.lock
  pkg/operator/certrotationcontroller/certrotationcontroller.go
  pkg/operator/resourcesynccontroller/resourcesynccontroller.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer_test.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target_test.go
Labels: approved, size/XL

#293 prime the csr CA in a single canonical spot
  bindata/bootkube/manifests/configmap-csr-controller-ca.yaml
  bindata/bootkube/manifests/configmap-initial-kubelet-serving-ca.yaml
  pkg/operator/resourcesynccontroller/resourcesynccontroller.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, size/M

#297 trust the kubeconfig signers from the installer
  bindata/bootkube/manifests/configmap-admin-kubeconfig-client-ca.yaml
  bindata/bootkube/manifests/configmap-node-bootstrap-client-ca.yaml
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, lgtm, size/S

#285 fix setting loglevel for the operand
  bindata/v3.11.0/kube-apiserver/pod.yaml
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/S

#289 Set minimal-shutdown-duration to 3s
  bindata/v3.11.0/kube-apiserver/defaultconfig.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#300 trust the kubelet-signer as client
  bindata/bootkube/manifests/configmap-csr-controller-ca.yaml
Labels: approved, lgtm, size/XS

#301 use the full client-ca bundle provided by the installer
  bindata/bootkube/config/bootstrap-config-overrides.yaml
  bindata/bootkube/config/config-overrides.yaml
  bindata/bootkube/manifests/configmap-initial-kube-apiserver-client-ca.yaml
  bindata/bootkube/manifests/configmap-initial-temporary-kube-apiserver-client-ca.yaml
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, lgtm, size/S

#306 default the registry internal hostname to the correct expected value
  bindata/v3.11.0/kube-apiserver/defaultconfig.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/L

#307 bump(*): fix installer pod shutdown and rolebinding
  glide.lock
  vendor/github.com/davecgh/go-spew/.travis.yml
  vendor/github.com/davecgh/go-spew/LICENSE
  vendor/github.com/davecgh/go-spew/README.md
  vendor/github.com/davecgh/go-spew/spew/bypass.go
  vendor/github.com/davecgh/go-spew/spew/bypasssafe.go
  vendor/github.com/davecgh/go-spew/spew/dump.go
  vendor/github.com/davecgh/go-spew/spew/dump_test.go
  vendor/github.com/davecgh/go-spew/spew/dumpcgo_test.go
  vendor/github.com/davecgh/go-spew/spew/format.go
  vendor/github.com/davecgh/go-spew/spew/format_test.go
  vendor/github.com/davecgh/go-spew/spew/internal_test.go
  vendor/github.com/davecgh/go-spew/spew/internalunsafe_test.go
  vendor/github.com/evanphx/json-patch/README.md
  vendor/github.com/evanphx/json-patch/errors.go
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/github.com/evanphx/json-patch/patch_test.go
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/README.md
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/go.mod
  vendor/github.com/ghodss/yaml/go.sum
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/github.com/ghodss/yaml/yaml_go110.go
  vendor/github.com/ghodss/yaml/yaml_go110_test.go
  vendor/github.com/ghodss/yaml/yaml_test.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/rbac.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/golang.org/x/tools/cmd/golsp/main.go
  vendor/golang.org/x/tools/cmd/guru/what.go
Labels: approved, lgtm, size/XL

#309 bump to fix early status
  glide.lock
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/library-go/pkg/operator/status/condition.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller_test.go
  vendor/golang.org/x/tools/go/packages/golist.go
Labels: approved, lgtm, size/L

#311 do not default the internal registry hostname to anything
  bindata/v3.11.0/kube-apiserver/defaultconfig.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#313 switch to pull if not present
  manifests/0000_10_kube-apiserver-operator_06_deployment.yaml
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, lgtm, size/XS
