Repository openshift/cluster-kube-apiserver-operator, pull requests merged in 2019-07, with the labels that each got.

#518 Bug 1720770: remove broken default serving cert
  pkg/operator/configobservation/apiserver/observe_apiserver.go
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#509 ConfigObservation: add ExternalIPRanger admission controller
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/configobservation/network/observe_network.go
  pkg/operator/configobservation/network/observe_network_test.go
Labels: approved, lgtm, size/L

#528 bindata/bootkube: fix image for http-check-container
  bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml
Labels: approved, lgtm, size/XS

#526 Bug 1731232: Report infrastructure provider metric from the operator
  pkg/operator/configmetrics/configmetrics.go
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/starter.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#529 metrics: Report values to improve querying for core metrics
  pkg/operator/configmetrics/configmetrics.go
Labels: approved, lgtm, size/S

#533 Bug 1733109: Fix kube-apiserver-to-kubelet-signer validity
  pkg/operator/certrotationcontroller/certrotationcontroller.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#441 Revision hotlooping e2e test
  test/e2e/operator_test.go
Labels: approved, lgtm, size/M

#536 switch to generic client
  glide.lock
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/operatorclient/staticpod_interface.go
  pkg/operator/starter.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  test/e2e/operator_test.go
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_console.go
  vendor/github.com/openshift/api/config/v1/types_dns.go
  vendor/github.com/openshift/api/config/v1/types_proxy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/console/v1/types_console_external_log_links.go
  vendor/github.com/openshift/api/console/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1alpha1/types_image_content_source_policy.go
  vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/client-go/glide.lock
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/lib/golang.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/images.mk
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/proxy/observe_proxy.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/proxy/observe_proxy_test.go
  vendor/github.com/openshift/library-go/pkg/operator/genericoperatorclient/dynamic_operator_client.go
  vendor/github.com/openshift/library-go/pkg/operator/genericoperatorclient/dynamic_operator_client_test.go
  vendor/github.com/openshift/library-go/pkg/operator/genericoperatorclient/dynamic_staticpod_operator_client.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/generic_config_merger.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/generic_config_merger_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staleconditions/remove_stale_conditions.go
Labels: approved, lgtm, size/XXL

#538 block upgrades on bad featuregates
  pkg/operator/featureupgradablecontroller/feature_upgradeable_controller.go
  pkg/operator/featureupgradablecontroller/feature_upgradeable_controller_test.go
  pkg/operator/starter.go
  test/e2e/featuregate_upgradeable_test.go
Labels: approved, lgtm, size/L

#539 add cert rotate upgrade prevention
  pkg/operator/certrotationtimeupgradeablecontroller/certrotationtime_upgradeable.go
  pkg/operator/certrotationtimeupgradeablecontroller/certrotationtime_upgradeable_test.go
  pkg/operator/starter.go
  test/e2e/certrotationtime_upgradeable_test.go
Labels: approved, lgtm, size/L
