Repository openshift/cluster-kube-apiserver-operator, pull requests merged in 2020-07, with the labels that each got.

#850 Set flags instead of different config format
  bindata/bootkube/config/bootstrap-config-overrides.yaml
  bindata/v4.1.0/config/config-overrides.yaml
  bindata/v4.1.0/config/defaultconfig.yaml
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, lgtm

#852 switch etcd storage urls to be kube-apiserver args
  bindata/bootkube/config/bootstrap-config-overrides.yaml
  bindata/v4.1.0/config/defaultconfig.yaml
  pkg/operator/configobservation/etcd/OWNERS
  pkg/operator/configobservation/etcd/observe_etcd.go
  pkg/operator/configobservation/etcd/observe_etcd_test.go
  pkg/operator/configobservation/etcdendpoints/observe_etcd_endpoints.go
  pkg/operator/configobservation/etcdendpoints/observe_etcd_endpoints_test.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, lgtm

#897 enable etcd latency metrics in kube-apiserver
  manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml
Labels: approved, lgtm

#898 point-to-point network check: add parameterized namespace
  bindata/v4.1.0/kube-apiserver/pod.yaml
  cmd/cluster-kube-apiserver-operator/main.go
  pkg/cmd/checkendpoints/cmd.go
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, lgtm

#896 check-endpoints: missing openshift apiserver service endpoints endpoints
  pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
Labels: approved, lgtm

#890 add an observer for webhookTokenAuthenticator
  go.mod
  go.sum
  pkg/operator/configobservation/auth/webhook_authenticator.go
  pkg/operator/configobservation/auth/webhook_authenticator_test.go
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/configobservation/interfaces.go
  pkg/operator/starter.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_build.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_network.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_oauth.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_scheduler.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_build.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/imageregistry/v1/00-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/01-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/types.go
  vendor/github.com/openshift/api/imageregistry/v1/types_imagepruner.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/types.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster_storage_operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/register.go
  vendor/github.com/openshift/api/operator/v1/types_storage.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm

#902 check-endpoints: add outage duration to connectivity restored event
  pkg/cmd/checkendpoints/controller/connection_checker.go
Labels: approved, lgtm

#901 point-to-point network check: use tls dialer
  go.mod
  go.sum
  pkg/cmd/checkendpoints/cmd.go
  pkg/cmd/checkendpoints/controller/connection_checker.go
  pkg/cmd/checkendpoints/controller/pod_network_connectivity_check_controller.go
  pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/go.mod
  vendor/github.com/openshift/api/go.sum
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/0000_10-pod-network-connectivity-check.crd.yaml
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/types_conditioncheck.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/osin/v1/types.go
  vendor/github.com/openshift/api/osin/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/crd-schema-gen.mk
  vendor/modules.txt
Labels: approved, lgtm

#876 Log non-graceful termination to /var/log/kube-apiserver/termination.log and stdout
  bindata/v4.1.0/kube-apiserver/pod.yaml
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, lgtm

#893 add metric reporting to check-endpoints
  bindata/v4.1.0/kube-apiserver/pod.yaml
  pkg/cmd/checkendpoints/cmd.go
  pkg/cmd/checkendpoints/controller/connection_checker.go
  pkg/cmd/checkendpoints/controller/metrics.go
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, lgtm

#905 kube-apiserver-cert-syncer-kubeconfig: point to serving cert
  bindata/v4.1.0/kube-apiserver/kubeconfig-cm.yaml
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, lgtm

#906 ponetworkconnectivitychecks not being updated
  pkg/cmd/checkendpoints/cmd.go
Labels: approved, lgtm

#907 add /etc/kubernetes/static-pod-certs/configmaps/control-plane-node-ku…
  bindata/v4.1.0/kube-apiserver/control-plane-node-kubeconfig-cm.yaml
  pkg/operator/certrotationcontroller/certrotationcontroller.go
  pkg/operator/starter.go
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, lgtm

#909 make the connectivity check controller re-useable
  pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
  pkg/operator/connectivitycheckcontroller/connectivity_checks.go
  pkg/operator/starter.go
Labels: approved, lgtm

#914 allow the check-endpoints target and pod to mutate over time
  pkg/cmd/checkendpoints/controller/connection_checker.go
  pkg/cmd/checkendpoints/controller/pod_network_connectivity_check_controller.go
Labels: approved, lgtm

#855 Change the method to get the ApiServer hostname
  pkg/operator/certrotationcontroller/externalloadbalancer.go
Labels: approved, lgtm, ok-to-test

#894 Support configuring ServicesNodePortRange via network config
  go.mod
  go.sum
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/configobservation/network/observe_network.go
  pkg/operator/configobservation/network/observe_network_test.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/network/observe_network.go
  vendor/github.com/openshift/library-go/pkg/operator/eventwatch/controller.go
  vendor/github.com/openshift/library-go/pkg/operator/genericoperatorclient/dynamic_operator_client.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/test_helpers.go
  vendor/modules.txt
Labels: approved, lgtm

#915 connectivitycheckcontroller: name endpoints using node names
  pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
  pkg/operator/connectivitycheckcontroller/connectivity_checks.go
Labels: approved, lgtm

#911 add start/end logs to outage entries
  go.mod
  go.sum
  pkg/cmd/checkendpoints/controller/connection_checker.go
  pkg/cmd/checkendpoints/controller/connection_checker_test.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_oauth.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/0000_10-pod-network-connectivity-check.crd.yaml
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/types_conditioncheck.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/osin/v1/types.go
  vendor/modules.txt
Labels: approved, lgtm

#920 Bug 1861431: LatencySensitive feature gate allows upgrades
  pkg/operator/featureupgradablecontroller/feature_upgradeable_controller.go
  pkg/operator/featureupgradablecontroller/feature_upgradeable_controller_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
