Repository openshift/cluster-kube-apiserver-operator, pull requests merged in 2020-08, with the labels that each got.

#874 Add Config Observer for AccessTokenInactivityTimeout in OAuth Cluster Config
  Makefile
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/configobservation/interfaces.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  test/e2e/token_inactivity_timeout_test.go
  test/library/cluster_operator.go
  vendor/github.com/openshift/client-go/oauth/clientset/versioned/scheme/doc.go
  vendor/github.com/openshift/client-go/oauth/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/oauth/clientset/versioned/typed/oauth/v1/doc.go
  vendor/github.com/openshift/client-go/oauth/clientset/versioned/typed/oauth/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/oauth/clientset/versioned/typed/oauth/v1/oauth_client.go
  vendor/github.com/openshift/client-go/oauth/clientset/versioned/typed/oauth/v1/oauthaccesstoken.go
  vendor/github.com/openshift/client-go/oauth/clientset/versioned/typed/oauth/v1/oauthauthorizetoken.go
  vendor/github.com/openshift/client-go/oauth/clientset/versioned/typed/oauth/v1/oauthclient.go
  vendor/github.com/openshift/client-go/oauth/clientset/versioned/typed/oauth/v1/oauthclientauthorization.go
  vendor/github.com/openshift/client-go/user/clientset/versioned/scheme/doc.go
  vendor/github.com/openshift/client-go/user/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/user/clientset/versioned/typed/user/v1/doc.go
  vendor/github.com/openshift/client-go/user/clientset/versioned/typed/user/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/user/clientset/versioned/typed/user/v1/group.go
  vendor/github.com/openshift/client-go/user/clientset/versioned/typed/user/v1/identity.go
  vendor/github.com/openshift/client-go/user/clientset/versioned/typed/user/v1/user.go
  vendor/github.com/openshift/client-go/user/clientset/versioned/typed/user/v1/user_client.go
  vendor/github.com/openshift/client-go/user/clientset/versioned/typed/user/v1/useridentitymapping.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/oauth/observe_tokenconfig.go
  vendor/modules.txt
Labels: approved, lgtm

#926 connectivitycheckcontroller: add checks for load balancers
  pkg/operator/connectivitycheckcontroller/connectivity_checks.go
  pkg/operator/starter.go
Labels: approved, lgtm

#923 [release-4.4] Bug 1863076: LatencySensitive feature gate allows upgrades
  pkg/operator/featureupgradablecontroller/feature_upgradeable_controller.go
  pkg/operator/featureupgradablecontroller/feature_upgradeable_controller_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#924 check-endpoints: minimize sorting delay
  pkg/cmd/checkendpoints/controller/connection_checker.go
  pkg/cmd/checkendpoints/controller/connection_checker_test.go
  pkg/cmd/checkendpoints/controller/pod_network_connectivity_check_controller.go
  pkg/cmd/checkendpoints/controller/updates_manager.go
  pkg/cmd/checkendpoints/controller/updates_manager_test.go
Labels: approved, lgtm

#927 Move to klog v2
  go.mod
  pkg/cmd/certregenerationcontroller/cabundlesyncer.go
  pkg/cmd/checkendpoints/controller/connection_checker.go
  pkg/cmd/checkendpoints/controller/pod_network_connectivity_check_controller.go
  pkg/cmd/checkendpoints/trace/latency.go
  pkg/cmd/insecurereadyz/readyz.go
  pkg/cmd/recoveryapiserver/create.go
  pkg/cmd/regeneratecerts/carry/kubecontrollermanager/certrotationcontroller/kubecontrollermanagercertrotation.go
  pkg/cmd/regeneratecerts/regenerate_certificates.go
  pkg/cmd/render/render.go
  pkg/cmd/resourcegraph/resourcegraph.go
  pkg/operator/boundsatokensignercontroller/controller.go
  pkg/operator/certrotationcontroller/certrotationcontroller.go
  pkg/operator/certrotationcontroller/externalloadbalancer.go
  pkg/operator/certrotationcontroller/internalloadbalancer.go
  pkg/operator/certrotationcontroller/servicehostname.go
  pkg/operator/configobservation/apiserver/observe_apiserver.go
  pkg/operator/configobservation/apiserver/observe_cors.go
  pkg/operator/configobservation/auth/auth_metadata.go
  pkg/operator/configobservation/auth/auth_serviceaccountissuer.go
  pkg/operator/configobservation/images/observe_images.go
  pkg/operator/configobservation/scheduler/observe_scheduler.go
  pkg/operator/terminationobserver/termination_observer.go
  pkg/recovery/apiserver.go
  pkg/recovery/helpers.go
  vendor/k8s.io/klog/.travis.yml
  vendor/k8s.io/klog/CONTRIBUTING.md
  vendor/k8s.io/klog/LICENSE
  vendor/k8s.io/klog/OWNERS
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/RELEASE.md
  vendor/k8s.io/klog/SECURITY_CONTACTS
  vendor/k8s.io/klog/code-of-conduct.md
  vendor/k8s.io/klog/go.mod
  vendor/k8s.io/klog/go.sum
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
  vendor/modules.txt
Labels: approved, lgtm

#925 connectivitycheckcontroller: create check for localhost etcd conn.
  pkg/operator/connectivitycheckcontroller/connectivity_checks.go
Labels: approved, lgtm

#928 avoid overlaping connectivity check names
  pkg/operator/connectivitycheckcontroller/connectivity_checks.go
Labels: approved, lgtm

#932 bump to delay version update until operand updated
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/version.go
  vendor/github.com/openshift/library-go/test/library/encryption/errors.go
  vendor/modules.txt
Labels: approved, lgtm

#930 inactivity timeout test waits until all kube-apiservers are on same revision
  test/e2e/token_inactivity_timeout_test.go
Labels: approved, lgtm

#929 Bug 1855575: Bump to go 1.14
  Dockerfile.rhel7
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#939 Bug 1858763: static-pod-installer: remove deadlock by recreating installers that disappear
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
