Repository openshift/cluster-kube-apiserver-operator, pull requests merged in 2020-05, with the labels that each got.

#826 [release 4-1] Bug 1810186: Components using globs in Dockerfile COPY commands may break on OCP 4
  Dockerfile.rhel7
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#847 Bug 1832143: bump(*): vendor update
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/config/clusteroperator/v1helpers/status.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#854 Bug 1813894: Stop using service ca from service account token
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/monitoring/bindata/bindata.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#841 Bug 1834852: Add make target to run operator with telepresence
  .gitignore
  Makefile
  go.mod
  go.sum
  vendor/github.com/openshift/build-machinery-go/go.mod
  vendor/github.com/openshift/build-machinery-go/make/operator.example.mk.help.log
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/telepresence.mk
  vendor/github.com/openshift/build-machinery-go/scripts/run-telepresence.sh
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#765 Bug 1802161: `regenerate-certificates` command blocked by error `illegal base64 data at input byte 3`
  bindata/v4.1.0/kube-apiserver/recovery-config.yaml
  bindata/v4.1.0/kube-apiserver/recovery-encryption-config.yaml
  pkg/operator/v410_00_assets/bindata.go
  pkg/recovery/apiserver.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#857 Bug 1834852: Fix bad vendoring from telepresence PR
  go.mod
  go.sum
  vendor/github.com/openshift/build-machinery-go/scripts/run-telepresence.sh
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#862 Bug 1806453: Host mount audit dir on bootstrap node
  bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#860 bug 1837451: prevent goaway chance in kubeapiserver to avoid tripping up golang clients
  bindata/v4.1.0/config/defaultconfig.yaml
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#861 Bug 1832143: bump(*): vendor update
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/controller/factory/factory.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#865 Bug 1838122: add admission webhooks to must-gather for kas-o
  manifests/0000_20_kube-apiserver-operator_07_clusteroperator.yaml
  pkg/operator/starter.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#866 bug 1837881: remove humorous help from dev focused command
  pkg/cmd/resourcegraph/resourcegraph.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#867 Bug 1812126: increase memory and resource limits for installer and pruner static pods
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_oauth.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/go.mod
  vendor/github.com/openshift/api/go.sum
  vendor/github.com/openshift/api/security/v1/0000_03_security-openshift_01_scc.crd.yaml
  vendor/github.com/openshift/api/security/v1/generated.proto
  vendor/github.com/openshift/api/security/v1/types.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/bindata/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/node/node_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/bindata/bindata.go
  vendor/k8s.io/apimachinery/pkg/util/json/json.go
  vendor/k8s.io/apimachinery/pkg/util/wait/wait.go
  vendor/k8s.io/apiserver/pkg/server/config.go
  vendor/k8s.io/client-go/tools/clientcmd/client_config.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/configmaplock.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#863 Bug 1806980: remove override for fast cert rotation
  pkg/operator/certrotationcontroller/certrotationcontroller.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#856 Bug 1833558: create cluster roles for modiyfing scc-s
  manifests/0000_20_kube-apiserver-operator_00_cr-anyuid.yaml
  manifests/0000_20_kube-apiserver-operator_00_cr-hostaccess.yaml
  manifests/0000_20_kube-apiserver-operator_00_cr-hostmount-anyuid.yaml
  manifests/0000_20_kube-apiserver-operator_00_cr-hostnetwork.yaml
  manifests/0000_20_kube-apiserver-operator_00_cr-nonroot.yaml
  manifests/0000_20_kube-apiserver-operator_00_cr-privileged.yaml
  manifests/0000_20_kube-apiserver-operator_00_cr-restricted.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#864 Bug 1837992: wait for port 6443 to be open in the kube-apiserver container; use ss isntead of lsof
  bindata/v4.1.0/kube-apiserver/pod.yaml
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
