Repository openshift/cluster-kube-apiserver-operator, pull requests merged in 2020-01, with the labels that each got.

#703 add test for cert rotation type stomping
  test/e2e/certrotation_test.go
Labels: approved, lgtm, size/M

#706 bump: openshift/library-go#653
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/lib/golang.mk
  vendor/github.com/openshift/library-go/pkg/config/leaderelection/leaderelection.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer_polling.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#708 bump(*): openshift/library-go
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/config/configdefaults/config_default.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#653 If the cluster is single-stack IPv6, bind to :: rather than 0.0.0.0.
  bindata/bootkube/config/bootstrap-config-overrides.yaml
  pkg/cmd/render/render.go
  pkg/cmd/render/render_test.go
  pkg/operator/configobservation/network/observe_network.go
  pkg/operator/configobservation/network/observe_network_test.go
Labels: approved, lgtm, size/L

#705 removes unused UsingDeprecatedAPIAppsV1Beta1 and UsingDeprecatedAPIAppsV1Beta2 alerts
  manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml
Labels: approved, lgtm, size/S

#711 bump(*): vendor update
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/deps-gomod.mk
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/node/node_controller.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#712 Bug 1788188: [release-4.3] bump(*): vendor update
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/config/configdefaults/config_default.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/node/node_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/condition.go
  vendor/github.com/openshift/library-go/pkg/operator/status/inertia.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#716 bump(*): vendor update
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/event_helpers.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcehelper/resource_helpers.go
  vendor/github.com/openshift/library-go/test/library/encryption/helpers.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#699 manifests: Drop deprecated kubernetes metrics
  manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml
Labels: approved, lgtm, size/S

#720 Fix certrotationcontroller.Run to wait for context to be canceled
  pkg/operator/certrotationcontroller/certrotationcontroller.go
Labels: approved, lgtm, size/XS

#725 Bug 1794309: Copy default SCC into release image
  manifests/0000_20_kube-apiserver-operator_00_scc-anyuid.json
  manifests/0000_20_kube-apiserver-operator_00_scc-anyuid.yaml
  manifests/0000_20_kube-apiserver-operator_00_scc-hostaccess.json
  manifests/0000_20_kube-apiserver-operator_00_scc-hostaccess.yaml
  manifests/0000_20_kube-apiserver-operator_00_scc-hostmount-anyuid.json
  manifests/0000_20_kube-apiserver-operator_00_scc-hostmount-anyuid.yaml
  manifests/0000_20_kube-apiserver-operator_00_scc-hostnetwork.json
  manifests/0000_20_kube-apiserver-operator_00_scc-hostnetwork.yaml
  manifests/0000_20_kube-apiserver-operator_00_scc-nonroot.json
  manifests/0000_20_kube-apiserver-operator_00_scc-nonroot.yaml
  manifests/0000_20_kube-apiserver-operator_00_scc-privileged.json
  manifests/0000_20_kube-apiserver-operator_00_scc-privileged.yaml
  manifests/0000_20_kube-apiserver-operator_00_scc-restricted.json
  manifests/0000_20_kube-apiserver-operator_00_scc-restricted.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XL

#722 picks kube 1.17.1
  go.mod
  go.sum
  vendor/k8s.io/client-go/discovery/discovery_client.go
  vendor/k8s.io/client-go/tools/cache/reflector.go
  vendor/k8s.io/client-go/tools/clientcmd/api/v1/conversion.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#713 encryption: switch to kube-storage-version-migrator
  go.mod
  go.sum
  pkg/operator/starter.go
  vendor/github.com/golang/groupcache/lru/lru.go
  vendor/github.com/kubernetes-sigs/kube-storage-version-migrator/pkg/clients/informer/factory.go
  vendor/github.com/kubernetes-sigs/kube-storage-version-migrator/pkg/clients/informer/generic.go
  vendor/github.com/kubernetes-sigs/kube-storage-version-migrator/pkg/clients/informer/migration/interface.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#718 Enable bound SA tokens
  bindata/v4.1.0/kube-apiserver/config-overrides.yaml
  pkg/operator/boundsatokensignercontroller/controller.go
  pkg/operator/resourcesynccontroller/resourcesynccontroller.go
  pkg/operator/starter.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/v410_00_assets/bindata.go
  test/e2e/bound_sa_token_test.go
  test/e2e/operator_test.go
Labels: approved, lgtm, size/XL

#635 Add cert regeneration controller
  bindata/v4.1.0/kube-apiserver/pod.yaml
  cmd/cluster-kube-apiserver-operator/main.go
  go.mod
  go.sum
  pkg/cmd/certregenerationcontroller/cabundlesyncer.go
  pkg/cmd/certregenerationcontroller/cmd.go
  pkg/cmd/regeneratecerts/regenerate_certificates.go
  pkg/operator/certrotationcontroller/certrotationcontroller.go
  pkg/operator/v410_00_assets/bindata.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/flags.go
  vendor/github.com/openshift/library-go/pkg/operator/events/recorder.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiextensions.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/apiextensions.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/apiextensions.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/core_getters.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#727 Enable changing bound service account token issuer from default
  pkg/operator/configobservation/auth/auth_serviceaccountissuer.go
  pkg/operator/configobservation/auth/auth_serviceaccountissuer_test.go
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  test/e2e/bound_sa_token_test.go
Labels: approved, lgtm, size/L

#738 Cleanup post-bootstrap config handling
  README.md
  bindata/bootkube/config/config-overrides.yaml
  bindata/v4.1.0/config/config-overrides.yaml
  bindata/v4.1.0/config/defaultconfig.yaml
  go.mod
  go.sum
  pkg/cmd/render/render.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/v410_00_assets/bindata.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/flags.go
  vendor/github.com/openshift/library-go/pkg/operator/render/options/config.go
  vendor/github.com/openshift/library-go/pkg/operator/render/options/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/bindata/bindata.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#504 manifests: set caFile for service monitor
  manifests/0000_90_kube-apiserver-operator_03_servicemonitor.yaml
Labels: approved, lgtm, size/XS

#739 bump library-go to get controller factory
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/controller/factory/base_controller.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/controller_context.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/factory.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/loglevel/logging_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/certsyncpod/certsync_cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/certsyncpod/certsync_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installerstate/installer_state_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/node/node_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/unsupportedconfigoverridescontroller/unsupportedconfigoverrides_controller.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/XXL
