Repository openshift/cluster-kube-apiserver-operator, pull requests merged in 2020-09, with the labels that each got.

#933 Bug 1874521: connectivity check metrics cannot be aggregated across components
  pkg/cmd/checkendpoints/cmd.go
  pkg/cmd/checkendpoints/controller/connection_checker.go
  pkg/cmd/checkendpoints/controller/metrics.go
  pkg/cmd/checkendpoints/controller/pod_network_connectivity_check_controller.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#931 Bug 1868801: check-endpoints should use minimal credentials
  bindata/v4.1.0/kube-apiserver/check-endpoints-clusterrole.yaml
  bindata/v4.1.0/kube-apiserver/check-endpoints-clusterrolebinding.yaml
  bindata/v4.1.0/kube-apiserver/check-endpoints-kubeconfig-cm.yaml
  bindata/v4.1.0/kube-apiserver/check-endpoints-rolebinding-kube-system.yaml
  bindata/v4.1.0/kube-apiserver/check-endpoints-rolebinding.yaml
  bindata/v4.1.0/kube-apiserver/pod.yaml
  pkg/operator/certrotationcontroller/certrotationcontroller.go
  pkg/operator/starter.go
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#944 Bug 1876874: [audit] log request and response bodies for identities
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#942 Bug 1874597: static-pod-installer: remove deadlock by recreating inst…
  go.mod
  go.sum
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/build/v1/generated.pb.go
  vendor/github.com/openshift/api/build/v1/generated.proto
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/build/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/go.mod
  vendor/github.com/openshift/api/imageregistry/v1/01-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/types_imagepruner.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_40_cloud-credential-operator_00_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/register.go
  vendor/github.com/openshift/api/operator/v1/types_cloudcredential.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#946 Bug 1877234: Drop recovery apiserver
  cmd/cluster-kube-apiserver-operator/main.go
  pkg/cmd/recoveryapiserver/create.go
  pkg/cmd/recoveryapiserver/destroy.go
  pkg/cmd/recoveryapiserver/lib.go
  pkg/cmd/recoveryapiserver/recoveryapiserver.go
  pkg/cmd/regeneratecerts/carry/kubecontrollermanager/certrotationcontroller/kubecontrollermanagercertrotation.go
  pkg/cmd/regeneratecerts/carry/kubecontrollermanager/operatorclient/interfaces.go
  pkg/cmd/regeneratecerts/carry/kubecontrollermanager/targetconfigcontroller/targetconfigcontroller.go
  pkg/cmd/regeneratecerts/regenerate_certificates.go
  pkg/cmd/regeneratecerts/regenerate_certificates_test.go
  vendor/k8s.io/client-go/tools/watch/informerwatcher.go
  vendor/k8s.io/client-go/tools/watch/retrywatcher.go
  vendor/k8s.io/client-go/tools/watch/until.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#934 Bug 1878289: connectivity check events have ambiguous related object
  bindata/v4.1.0/kube-apiserver/check-endpoints-clusterrole-node-reader.yaml
  bindata/v4.1.0/kube-apiserver/check-endpoints-clusterrole.yaml
  bindata/v4.1.0/kube-apiserver/check-endpoints-clusterrolebinding-auth-delegator.yaml
  bindata/v4.1.0/kube-apiserver/check-endpoints-clusterrolebinding-node-reader.yaml
  pkg/cmd/checkendpoints/cmd.go
  pkg/operator/starter.go
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#950 Bug 1874056: bump: update library-go to get exit on control-loop failure behavior
  go.mod
  go.sum
  pkg/operator/starter.go
  vendor/github.com/openshift/api/imageregistry/v1/00-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/types.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/library-go/pkg/controller/factory/base_controller.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/controller_context.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/factory.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/migrators/kubestorageversionmigrator.go
  vendor/github.com/openshift/library-go/pkg/operator/loglevel/logging_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/loglevel/util.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/retry/retry.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/blame.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/modules.txt
  vendor/sigs.k8s.io/kube-storage-version-migrator/LICENSE
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/apis/migration/v1alpha1/doc.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/apis/migration/v1alpha1/register.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/apis/migration/v1alpha1/types.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/apis/migration/v1alpha1/zz_generated.deepcopy.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/clientset.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/doc.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/scheme/doc.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/scheme/register.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/typed/migration/v1alpha1/doc.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/typed/migration/v1alpha1/generated_expansion.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/typed/migration/v1alpha1/migration_client.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/typed/migration/v1alpha1/storagestate.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/typed/migration/v1alpha1/storageversionmigration.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/informer/factory.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/informer/generic.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/informer/internalinterfaces/factory_interfaces.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/informer/migration/interface.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/informer/migration/v1alpha1/interface.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/informer/migration/v1alpha1/storagestate.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/informer/migration/v1alpha1/storageversionmigration.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/lister/migration/v1alpha1/expansion_generated.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/lister/migration/v1alpha1/storagestate.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/lister/migration/v1alpha1/storageversionmigration.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#956 Bug 1873412: OAuth server returned error after cluster being used for few days
  pkg/cmd/checkendpoints/controller/connection_checker.go
  pkg/cmd/checkendpoints/controller/connection_checker_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#948 Bug 1877106: Connectivity checker creates excessive events and possibly etcd db growth on Azure
  pkg/cmd/checkendpoints/controller/backoff_recorder.go
  pkg/cmd/checkendpoints/controller/backoff_recorder_test.go
  pkg/cmd/checkendpoints/controller/connection_checker.go
  pkg/cmd/checkendpoints/controller/pod_network_connectivity_check_controller.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#957 bug 1871890: add current profile annotations to CVO manifests
  go.sum
  manifests/0000_20_kube-apiserver-operator_00_cr-anyuid.yaml
  manifests/0000_20_kube-apiserver-operator_00_cr-hostaccess.yaml
  manifests/0000_20_kube-apiserver-operator_00_cr-hostmount-anyuid.yaml
  manifests/0000_20_kube-apiserver-operator_00_cr-hostnetwork.yaml
  manifests/0000_20_kube-apiserver-operator_00_cr-nonroot.yaml
  manifests/0000_20_kube-apiserver-operator_00_cr-privileged.yaml
  manifests/0000_20_kube-apiserver-operator_00_cr-restricted.yaml
  manifests/0000_20_kube-apiserver-operator_00_namespace.yaml
  manifests/0000_20_kube-apiserver-operator_00_scc-anyuid.yaml
  manifests/0000_20_kube-apiserver-operator_00_scc-hostaccess.yaml
  manifests/0000_20_kube-apiserver-operator_00_scc-hostmount-anyuid.yaml
  manifests/0000_20_kube-apiserver-operator_00_scc-hostnetwork.yaml
  manifests/0000_20_kube-apiserver-operator_00_scc-nonroot.yaml
  manifests/0000_20_kube-apiserver-operator_00_scc-privileged.yaml
  manifests/0000_20_kube-apiserver-operator_00_scc-restricted.yaml
  manifests/0000_20_kube-apiserver-operator_01_operator.cr.yaml
  manifests/0000_20_kube-apiserver-operator_02_service.yaml
  manifests/0000_20_kube-apiserver-operator_03_configmap.yaml
  manifests/0000_20_kube-apiserver-operator_04_clusterrolebinding.yaml
  manifests/0000_20_kube-apiserver-operator_05_serviceaccount.yaml
  manifests/0000_20_kube-apiserver-operator_06_deployment.yaml
  manifests/0000_20_kube-apiserver-operator_07_clusteroperator.yaml
  manifests/0000_90_kube-apiserver-operator_01_prometheusrole.yaml
  manifests/0000_90_kube-apiserver-operator_02_prometheusrolebinding.yaml
  manifests/0000_90_kube-apiserver-operator_03_servicemonitor.yaml
  manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#954 Bug 1880322: fix bug in reflector not recovering from "Too large resource version"
  go.mod
  go.sum
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/validation/validation.go
  vendor/k8s.io/apimachinery/pkg/util/net/http.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/create.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/fieldmanager.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/internal/managedfields.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/structuredmerge.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/patch.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/update.go
  vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go
  vendor/k8s.io/apiserver/pkg/server/config.go
  vendor/k8s.io/apiserver/pkg/server/healthz/healthz.go
  vendor/k8s.io/apiserver/pkg/storage/errors.go
  vendor/k8s.io/client-go/tools/cache/reflector.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#955 Bug 1882737: check-endpoints should gracefully handle missing podnetworkconnectivitycheck crd
  bindata/v4.1.0/kube-apiserver/check-endpoints-clusterrole-crd-reader.yaml
  bindata/v4.1.0/kube-apiserver/check-endpoints-clusterrolebinding-crd-reader.yaml
  go.mod
  pkg/cmd/checkendpoints/cmd.go
  pkg/cmd/checkendpoints/controller/pod_network_connectivity_check_controller.go
  pkg/cmd/checkendpoints/start_stop_controllers.go
  pkg/operator/starter.go
  pkg/operator/v410_00_assets/bindata.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/interface.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1/interface.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1beta1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1beta1/interface.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/factory.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/generic.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1/expansion_generated.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1beta1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1beta1/expansion_generated.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#962 Bug 1883698: Bug 1883603: Bump openshift/api
  go.mod
  go.sum
  vendor/github.com/openshift/api/go.mod
  vendor/github.com/openshift/api/imageregistry/v1/00-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/01-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/types.go
  vendor/github.com/openshift/api/imageregistry/v1/types_imagepruner.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_10_config-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_12_etcd-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_20_kube-apiserver-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-controller-manager-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-scheduler-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_30_openshift-apiserver-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_40_cloud-credential-operator_00_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_40_kube-storage-version-migrator-operator_00_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster-authentication-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster-openshift-controller-manager-operator_02_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster_storage_operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_service-ca-operator_02_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_console-operator.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_80_csi_snapshot_controller_operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/0000_10-pod-network-connectivity-check.crd.yaml
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
