Repository openshift/cluster-kube-apiserver-operator, pull requests merged in 2020-04, with the labels that each got.

#810 Bug 1820147: certrotationcontroller: fix typo calling wrong internal LB func
  pkg/operator/certrotationcontroller/internalloadbalancer.go
Labels: approved, bugzilla/valid-bug, lgtm

#816 Bug 1810184: Components using globs in Dockerfile COPY commands may break on OCP 4
  Dockerfile.rhel7
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#815 Bug 1820255: Fix race for localhost-recovery-client-token snapshotting
  go.mod
  go.sum
  pkg/operator/starter.go
  vendor/github.com/openshift/api/Dockerfile.build
  vendor/github.com/openshift/api/config/v1/types_operatorhub.go
  vendor/github.com/openshift/api/go.mod
  vendor/github.com/openshift/api/go.sum
  vendor/github.com/openshift/api/operator/v1/0000_10_config-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster-svcat-apiserver-operator_02_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_config.go
  vendor/github.com/openshift/api/operator/v1/types_servicecatalogapiserver.go
  vendor/github.com/openshift/api/operator/v1/types_servicecatalogcontrollermanager.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/config_client.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/operatorhub.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/interface.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/operatorhub.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/generic.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/expansion_generated.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/operatorhub.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/base_controller.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/factory.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/condition_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/key_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/migration_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/migrators/inprocess.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/migrators/kubestorageversionmigrator.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/migrators/types.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/prune_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/state_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/deployer/deploynodeprovider.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/deployer/revisionedpod.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/deployer/unionrevisionedpod.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/statemachine/transition.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/storage.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/k8s.io/api/networking/v1beta1/generated.proto
  vendor/k8s.io/api/networking/v1beta1/types.go
  vendor/k8s.io/api/networking/v1beta1/types_swagger_doc_generated.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/helpers.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/store.go
  vendor/k8s.io/utils/net/net.go
  vendor/k8s.io/utils/net/port.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm

#809 Bug 1819246: Set service account issuer to internal dns name of kube apiserver
  bindata/v4.1.0/config/config-overrides.yaml
  pkg/operator/v410_00_assets/bindata.go
  test/e2e/bound_sa_token_test.go
Labels: approved, bugzilla/valid-bug, lgtm

#818 enable priority and fairness
  bindata/bootkube/config/bootstrap-config-overrides.yaml
  bindata/v4.1.0/config/defaultconfig.yaml
  go.mod
  go.sum
  pkg/operator/v410_00_assets/bindata.go
  vendor/github.com/openshift/api/authorization/v1/generated.proto
  vendor/github.com/openshift/api/authorization/v1/types.go
  vendor/github.com/openshift/api/build/v1/generated.proto
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_console.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/imageregistry/v1/00-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/types.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-custom-resource-definition.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_console-operator.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_console.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm

#817 Add BZ component name to OWNERS
  OWNERS
Labels: approved, lgtm

#821 [release-4.4] Bug 1820258: Fix race for localhost-recovery-client-token snapshotting
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#824 [release 4-2] Bug 1810185: Components using globs in Dockerfile COPY commands may break on OCP 4
  Dockerfile.rhel7
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#829 [release-4.4] Bug 1819247: Set service account issuer to internal dns name of kube apiserver
  bindata/v4.1.0/config/config-overrides.yaml
  go.mod
  go.sum
  pkg/operator/v410_00_assets/bindata.go
  test/e2e/bound_sa_token_test.go
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_tlssecurityprofile.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/imageregistry/v1/types.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-custom-resource-definition.yaml
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#830 Bug 1823921: Revert SCC Upgradeable False
  pkg/operator/defaultscc_assets/bindata.go
  pkg/operator/defaultscccontroller/condition.go
  pkg/operator/defaultscccontroller/condition_test.go
  pkg/operator/defaultscccontroller/defaultscc.go
  pkg/operator/defaultscccontroller/defaultscc_test.go
  pkg/operator/defaultscccontroller/defaultscccontroller.go
  pkg/operator/starter.go
  test/e2e/default_scc_upgradeable_test.go
  test/library/cluster_operator.go
  test/library/operator_config.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/doc.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/scheme/doc.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/doc.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/podsecuritypolicyreview.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/podsecuritypolicyselfsubjectreview.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/podsecuritypolicysubjectreview.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/rangeallocation.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/security_client.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/securitycontextconstraints.go
  vendor/github.com/openshift/client-go/security/informers/externalversions/factory.go
  vendor/github.com/openshift/client-go/security/informers/externalversions/generic.go
  vendor/github.com/openshift/client-go/security/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/github.com/openshift/client-go/security/informers/externalversions/security/interface.go
  vendor/github.com/openshift/client-go/security/informers/externalversions/security/v1/interface.go
  vendor/github.com/openshift/client-go/security/informers/externalversions/security/v1/rangeallocation.go
  vendor/github.com/openshift/client-go/security/informers/externalversions/security/v1/securitycontextconstraints.go
  vendor/github.com/openshift/client-go/security/listers/security/v1/expansion_generated.go
  vendor/github.com/openshift/client-go/security/listers/security/v1/rangeallocation.go
  vendor/github.com/openshift/client-go/security/listers/security/v1/securitycontextconstraints.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#831 Bug 1823933: Make default SCCs create-only by CVO
  manifests/0000_20_kube-apiserver-operator_00_scc-anyuid.yaml
  manifests/0000_20_kube-apiserver-operator_00_scc-hostaccess.yaml
  manifests/0000_20_kube-apiserver-operator_00_scc-hostmount-anyuid.yaml
  manifests/0000_20_kube-apiserver-operator_00_scc-hostnetwork.yaml
  manifests/0000_20_kube-apiserver-operator_00_scc-nonroot.yaml
  manifests/0000_20_kube-apiserver-operator_00_scc-privileged.yaml
  manifests/0000_20_kube-apiserver-operator_00_scc-restricted.yaml
Labels: approved, bugzilla/valid-bug, lgtm

#836 Bug 1823934: Make default SCCs create-only by CVO
  manifests/0000_20_kube-apiserver-operator_00_scc-anyuid.yaml
  manifests/0000_20_kube-apiserver-operator_00_scc-hostaccess.yaml
  manifests/0000_20_kube-apiserver-operator_00_scc-hostmount-anyuid.yaml
  manifests/0000_20_kube-apiserver-operator_00_scc-hostnetwork.yaml
  manifests/0000_20_kube-apiserver-operator_00_scc-nonroot.yaml
  manifests/0000_20_kube-apiserver-operator_00_scc-privileged.yaml
  manifests/0000_20_kube-apiserver-operator_00_scc-restricted.yaml
Labels: approved, bugzilla/high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#838 Bug 1827337: Remove stale condition DefaultSecurityContextConstraintsUpgradeable
  pkg/operator/starter.go
  vendor/github.com/openshift/library-go/pkg/operator/staleconditions/remove_stale_conditions.go
  vendor/modules.txt
Labels: approved, bugzilla/unspecified, bugzilla/valid-bug, cherry-pick-approved, lgtm

#839 Bug 1827336: Remove stale condition
  pkg/operator/starter.go
Labels: approved, bugzilla/unspecified, bugzilla/valid-bug, cherry-pick-approved, lgtm

#833 Bug 1828830: add relatedobjects for immediate creation by CVO
  manifests/0000_20_kube-apiserver-operator_07_clusteroperator.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
