Repository openshift/cluster-kube-apiserver-operator, pull requests merged in 2020-06, with the labels that each got.

#869 Bug 1840597: Revert "remove override for fast cert rotation" for 4.6
  pkg/operator/certrotationcontroller/certrotationcontroller.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#871 Bug 1801437: bump(*): Mark Abandoned static pod revisions
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#870 make SA Token tests to wait for API Servers to be on the same revision
  test/e2e/bound_sa_token_test.go
  test/library/library.go
Labels: approved, lgtm

#875 Bug 1843752: static pod: don't wait for 6080 in apiserver container
  bindata/v4.1.0/kube-apiserver/pod.yaml
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#872 fail if the user specifies the same certificate to be used for multip…
  pkg/operator/configobservation/apiserver/observe_apiserver.go
  pkg/operator/configobservation/apiserver/observe_apiserver_test.go
Labels: approved, lgtm

#879 factory: use less noisy synthetic requeue mechanism
  go.mod
  go.sum
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/base_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller.go
  vendor/modules.txt
Labels: approved, lgtm

#880 auth-config-observation: fix unstructured issuer slice type
  pkg/operator/configobservation/auth/auth_serviceaccountissuer.go
Labels: approved, lgtm

#851 update openshift/api for IPv6DualStackNoUpgrade featureset
  go.mod
  go.sum
  pkg/cmd/render/render_test.go
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/OWNERS
  vendor/github.com/openshift/api/build/v1/generated.pb.go
  vendor/github.com/openshift/api/build/v1/generated.proto
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/build/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/go.mod
  vendor/github.com/openshift/api/imageregistry/v1/01-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/types_imagepruner.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/install.go
  vendor/github.com/openshift/api/operator/v1/0000_20_etcd-operator_01.crd.yaml
  vendor/github.com/openshift/api/operatorcontrolplane/install.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/0000_10-pod-network-connectivity-check.crd.yaml
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/doc.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/register.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/types_conditioncheck.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm

#846 point-to-point network check tool
  Dockerfile.rhel7
  bindata/v4.1.0/kube-apiserver/pod.yaml
  cmd/cluster-kube-apiserver-operator/main.go
  go.mod
  go.sum
  manifests/0000_20_kube-apiserver-operator_07_clusteroperator.yaml
  pkg/cmd/checkendpoints/cmd.go
  pkg/cmd/checkendpoints/controller/connection_checker.go
  pkg/cmd/checkendpoints/controller/connection_checker_test.go
  pkg/cmd/checkendpoints/controller/pod_network_connectivity_check_controller.go
  pkg/cmd/checkendpoints/operatorcontrolplane/podnetworkconnectivitycheck/v1alpha1helpers/helpers.go
  pkg/cmd/checkendpoints/operatorcontrolplane/podnetworkconnectivitycheck/v1alpha1helpers/helpers_test.go
  pkg/cmd/checkendpoints/trace/latency.go
  pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
  pkg/operator/starter.go
  pkg/operator/v410_00_assets/bindata.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/config.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/operator_client.go
  vendor/github.com/openshift/client-go/operatorcontrolplane/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/operatorcontrolplane/clientset/versioned/doc.go
  vendor/github.com/openshift/client-go/operatorcontrolplane/clientset/versioned/scheme/doc.go
  vendor/github.com/openshift/client-go/operatorcontrolplane/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/operatorcontrolplane/clientset/versioned/typed/operatorcontrolplane/v1alpha1/doc.go
  vendor/github.com/openshift/client-go/operatorcontrolplane/clientset/versioned/typed/operatorcontrolplane/v1alpha1/generated_expansion.go
  vendor/github.com/openshift/client-go/operatorcontrolplane/clientset/versioned/typed/operatorcontrolplane/v1alpha1/operatorcontrolplane_client.go
  vendor/github.com/openshift/client-go/operatorcontrolplane/clientset/versioned/typed/operatorcontrolplane/v1alpha1/podnetworkconnectivitycheck.go
  vendor/github.com/openshift/client-go/operatorcontrolplane/informers/externalversions/factory.go
  vendor/github.com/openshift/client-go/operatorcontrolplane/informers/externalversions/generic.go
  vendor/github.com/openshift/client-go/operatorcontrolplane/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/github.com/openshift/client-go/operatorcontrolplane/informers/externalversions/operatorcontrolplane/interface.go
  vendor/github.com/openshift/client-go/operatorcontrolplane/informers/externalversions/operatorcontrolplane/v1alpha1/interface.go
  vendor/github.com/openshift/client-go/operatorcontrolplane/informers/externalversions/operatorcontrolplane/v1alpha1/podnetworkconnectivitycheck.go
  vendor/github.com/openshift/client-go/operatorcontrolplane/listers/operatorcontrolplane/v1alpha1/expansion_generated.go
  vendor/github.com/openshift/client-go/operatorcontrolplane/listers/operatorcontrolplane/v1alpha1/podnetworkconnectivitycheck.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/base_controller.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/factory.go
  vendor/github.com/openshift/library-go/pkg/operator/render/options/generic.go
  vendor/github.com/openshift/library-go/test/library/encryption/e_log.go
  vendor/github.com/openshift/library-go/test/library/encryption/perf_helpers.go
  vendor/github.com/robfig/cron/v3/.gitignore
  vendor/github.com/robfig/cron/v3/.travis.yml
  vendor/github.com/robfig/cron/v3/LICENSE
  vendor/github.com/robfig/cron/v3/README.md
  vendor/github.com/robfig/cron/v3/chain.go
  vendor/github.com/robfig/cron/v3/constantdelay.go
  vendor/github.com/robfig/cron/v3/cron.go
  vendor/github.com/robfig/cron/v3/doc.go
  vendor/github.com/robfig/cron/v3/go.mod
  vendor/github.com/robfig/cron/v3/logger.go
  vendor/github.com/robfig/cron/v3/option.go
  vendor/github.com/robfig/cron/v3/parser.go
  vendor/github.com/robfig/cron/v3/spec.go
  vendor/modules.txt
Labels: approved, lgtm

#887 Wire event watcher for LateConnections events
  go.mod
  go.sum
  pkg/operator/starter.go
  pkg/operator/terminationobserver/late_connections.go
  pkg/operator/terminationobserver/termination_observer.go
  vendor/github.com/openshift/library-go/pkg/operator/eventwatch/controller.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go
  vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
  vendor/modules.txt
Labels: approved, lgtm

#845 Bug 1829580: Add e2e test that ensures stale condition is removed
  test/e2e/clean_stale_condition_test.go
  test/library/operator_config.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, cherry-pick-approved, lgtm

#853 pass admission plugins to be enabled
  bindata/v4.1.0/config/defaultconfig.yaml
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, lgtm

#886 Replace whitelist/blacklist terminology by allowlist/denylist
  pkg/operator/featureupgradablecontroller/feature_upgradeable_controller.go
Labels: approved, lgtm

#891 Bug 1851066: 4.4: use "ss" instead of "lsof" to check port; check on container start
  bindata/v4.1.0/kube-apiserver/pod.yaml
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#889 add target endpoint description to check name
  pkg/cmd/checkendpoints/controller/connection_checker.go
  pkg/cmd/checkendpoints/controller/connection_checker_test.go
  pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
Labels: approved, lgtm

#840 Bug 1829576: Add e2e test that ensures stale condition is removed
  test/e2e/clean_stale_condition_test.go
  test/library/operator_config.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, cherry-pick-approved, lgtm
