Repository openshift/cluster-kube-apiserver-operator, pull requests merged in 2020-03, with the labels that each got.

#785 Bug 1810008: Use the new tls-server-name option in kubeconfig
  bindata/v4.1.0/kube-apiserver/kubeconfig-cm.yaml
  bindata/v4.1.0/kube-apiserver/pod.yaml
  go.mod
  go.sum
  pkg/cmd/certregenerationcontroller/cmd.go
  pkg/operator/v410_00_assets/bindata.go
  vendor/gopkg.in/yaml.v2/.travis.yml
  vendor/gopkg.in/yaml.v2/decode.go
  vendor/gopkg.in/yaml.v2/scannerc.go
  vendor/gopkg.in/yaml.v2/yaml.go
  vendor/gopkg.in/yaml.v2/yamlh.go
  vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go
  vendor/k8s.io/client-go/tools/clientcmd/api/types.go
  vendor/k8s.io/client-go/tools/clientcmd/api/v1/types.go
  vendor/k8s.io/client-go/tools/clientcmd/api/v1/zz_generated.conversion.go
  vendor/k8s.io/client-go/tools/clientcmd/client_config.go
  vendor/k8s.io/client-go/tools/clientcmd/overrides.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#784 Bug 1808602: kube-apiserver-operator should set upgradeable=false if default SCC mutates
  go.sum
  pkg/operator/defaultscc_assets/bindata.go
  pkg/operator/defaultscccontroller/condition.go
  pkg/operator/defaultscccontroller/condition_test.go
  pkg/operator/defaultscccontroller/defaultscc.go
  pkg/operator/defaultscccontroller/defaultscc_test.go
  pkg/operator/defaultscccontroller/defaultscccontroller.go
  pkg/operator/starter.go
  test/e2e/default_scc_upgradeable_test.go
  test/library/cluster_operator.go
  test/library/operator_config.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/doc.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/scheme/doc.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/doc.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/podsecuritypolicyreview.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/podsecuritypolicyselfsubjectreview.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/podsecuritypolicysubjectreview.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/rangeallocation.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/security_client.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/securitycontextconstraints.go
  vendor/github.com/openshift/client-go/security/informers/externalversions/factory.go
  vendor/github.com/openshift/client-go/security/informers/externalversions/generic.go
  vendor/github.com/openshift/client-go/security/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/github.com/openshift/client-go/security/informers/externalversions/security/interface.go
  vendor/github.com/openshift/client-go/security/informers/externalversions/security/v1/interface.go
  vendor/github.com/openshift/client-go/security/informers/externalversions/security/v1/rangeallocation.go
  vendor/github.com/openshift/client-go/security/informers/externalversions/security/v1/securitycontextconstraints.go
  vendor/github.com/openshift/client-go/security/listers/security/v1/expansion_generated.go
  vendor/github.com/openshift/client-go/security/listers/security/v1/rangeallocation.go
  vendor/github.com/openshift/client-go/security/listers/security/v1/securitycontextconstraints.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XXL

#788 Bug 1810712: use localhost name instead of localhost IPs
  pkg/operator/configobservation/etcd/observe_etcd.go
  pkg/operator/configobservation/etcd/observe_etcd_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#786 [release-4.4] Bug 1771410: Use the new tls-server-name option in kubeconfig
  bindata/v4.1.0/kube-apiserver/kubeconfig-cm.yaml
  bindata/v4.1.0/kube-apiserver/pod.yaml
  go.mod
  go.sum
  pkg/cmd/certregenerationcontroller/cmd.go
  pkg/operator/v410_00_assets/bindata.go
  vendor/gopkg.in/yaml.v2/.travis.yml
  vendor/gopkg.in/yaml.v2/decode.go
  vendor/gopkg.in/yaml.v2/scannerc.go
  vendor/gopkg.in/yaml.v2/yaml.go
  vendor/gopkg.in/yaml.v2/yamlh.go
  vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go
  vendor/k8s.io/client-go/tools/clientcmd/api/types.go
  vendor/k8s.io/client-go/tools/clientcmd/api/v1/types.go
  vendor/k8s.io/client-go/tools/clientcmd/api/v1/zz_generated.conversion.go
  vendor/k8s.io/client-go/tools/clientcmd/client_config.go
  vendor/k8s.io/client-go/tools/clientcmd/overrides.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#741 Bug 1795617: Remove entirely deprecated alerts
  manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#745 Controller factory controllers and graceful termination fixes
  go.mod
  go.sum
  pkg/operator/boundsatokensignercontroller/controller.go
  pkg/operator/certrotationtimeupgradeablecontroller/certrotationtime_upgradeable.go
  pkg/operator/featureupgradablecontroller/feature_upgradeable_controller.go
  pkg/operator/starter.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/base_controller.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/factory.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/interfaces.go
  vendor/github.com/openshift/library-go/pkg/controller/manager/controller_manager.go
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#793 Bug 1812583: Normalize CPU requests on masters
  bindata/v4.1.0/kube-apiserver/pod.yaml
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#797 Bug 1813911: Disable serving for cert regeneration controller to avoid wrong dependency
  pkg/cmd/certregenerationcontroller/cmd.go
Labels: approved, bugzilla/valid-bug, lgtm

#794 bump library-go
  go.mod
  go.sum
  pkg/cmd/regeneratecerts/carry/kubecontrollermanager/certrotationcontroller/kubecontrollermanagercertrotation.go
  pkg/cmd/regeneratecerts/regenerate_certificates.go
  pkg/operator/certrotationcontroller/certrotationcontroller.go
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/starter.go
  vendor/github.com/openshift/library-go/pkg/config/leaderelection/leaderelection.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/base_controller.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/controller_context.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/factory.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/loglevel/logging_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/loglevel/util.go
  vendor/github.com/openshift/library-go/pkg/operator/management/management_state_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/object_merger.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staleconditions/remove_stale_conditions.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/test_helpers.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#798 [release-4.4] Bug 1813914: Disable serving for cert regeneration controller to avoid wrong dependency
  pkg/cmd/certregenerationcontroller/cmd.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#806 bootstrap: set log-level 2 instead of 0
  bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml
Labels: approved, lgtm

#802 Bug 1810181: Components using globs in Dockerfile COPY commands may break on OCP 4
  Dockerfile.rhel7
Labels: approved, bugzilla/valid-bug, lgtm
