Repository openshift/cluster-kube-apiserver-operator, pull requests merged in 2020-10, with the labels that each got.

#964 Bug 1876166: add ability to disable kube-apiserver connectivity checks
  Dockerfile.rhel7
  go.mod
  go.sum
  pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
  pkg/operator/connectivitycheckcontroller/connectivity_checks.go
  pkg/operator/starter.go
  vendor/github.com/openshift/library-go/pkg/operator/connectivitycheckcontroller/bindata/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/connectivitycheckcontroller/connectivity_check_template.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/apiextensions.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/informers.go
  vendor/github.com/pkg/profile/.travis.yml
  vendor/github.com/pkg/profile/README.md
  vendor/github.com/pkg/profile/go.mod
  vendor/github.com/pkg/profile/mutex.go
  vendor/github.com/pkg/profile/mutex17.go
  vendor/github.com/pkg/profile/profile.go
  vendor/github.com/pkg/profile/trace.go
  vendor/github.com/pkg/profile/trace16.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#943 Bug 1876166: disable kube-apiserver connectivity checks
  pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#959 Bug 1876484: static-pod-installer: remove deadlock by recreating inst…
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/types_operatorhub.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer_polling.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apps.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/bindata/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/bindata/bindata.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#963 Bug 1840116: revert the forced cert rotation changes
  pkg/operator/certrotationcontroller/certrotationcontroller.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, group-lead-approved, lgtm

#966 protect openshift traffic by using dedicated flowschema
  manifests/0000_20_kube-apiserver-operator_08_flowschema.yaml
Labels: approved, lgtm

#967 BUG 1885356: protect openshift traffic by using dedicated flowschema
  manifests/0000_20_kube-apiserver-operator_08_flowschema.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, group-lead-approved, lgtm

#969 BUG 1886442: p&f: assign oauth server traffic to workload-high
  manifests/0000_20_kube-apiserver-operator_08_flowschema.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, group-lead-approved, lgtm

#970 Updating ose-cluster-kube-apiserver-operator builder & base images to be consistent with ART
  Dockerfile.rhel7
Labels: approved, lgtm

#977 operator: add kube-system to informers for namespaces
  pkg/operator/starter.go
Labels: approved, lgtm

#978 Bug 1876166: need to be able to disable kube-apiserver connectivity checks
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/migration_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissions.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#981 bug 1888015: bump library-go to pick up static pod graceful timeout workaround
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/core.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/status/condition.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#971 Revert "connectivitycheckcontroller: disable by default"
  pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
Labels: approved, lgtm

#968 BUG 1885353: protect openshift traffic by using dedicated flowschema
  manifests/0000_20_kube-apiserver-operator_08_flowschema.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#987 Bug 1889308: Set dnsPolicy ClusterFirstWithHostNet to match hostNetwork
  bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml
  bindata/v4.1.0/kube-apiserver/pod.yaml
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#983 add current profile annotations to CVO manifests
  manifests/0000_20_kube-apiserver-operator_08_flowschema.yaml
Labels: approved, lgtm

#989 connectivitycheckcontroller: disable by default
  pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
Labels: approved, lgtm

#986 Bug 1888861: set servicesSubnet correctly in dual-stack clusters
  bindata/bootkube/config/bootstrap-config-overrides.yaml
  go.mod
  go.sum
  pkg/cmd/render/render_test.go
  pkg/operator/configobservation/network/observe_network.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/network/observe_network.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#984 BUG 1888309: p&f: make oas/oauth SAR/TokenReview traffic exempt
  manifests/0000_20_kube-apiserver-operator_08_flowschema.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#993 bump library-go for static pod uid
  go.mod
  go.sum
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/go.mod
  vendor/github.com/openshift/api/go.sum
  vendor/github.com/openshift/api/network/v1/001-clusternetwork-crd.yaml
  vendor/github.com/openshift/api/network/v1/002-hostsubnet-crd.yaml
  vendor/github.com/openshift/api/network/v1/003-netnamespace-crd.yaml
  vendor/github.com/openshift/api/network/v1/004-egressnetworkpolicy-crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-patch
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/crd-schema-gen.mk
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go
  vendor/github.com/openshift/library-go/pkg/operator/connectivitycheckcontroller/bindata/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/loglevel/logging_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/loglevel/util.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go
  vendor/k8s.io/client-go/tools/cache/controller.go
  vendor/k8s.io/client-go/tools/cache/reflector.go
  vendor/k8s.io/component-base/logs/registry.go
  vendor/modules.txt
Labels: approved, lgtm

#994 bug 1888026: [release-4.6] bump library-go for static pod uid
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissions.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/core.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#960 [release-4.3] Bug 1876486: static-pod-installer: remove deadlock by recreating inst…
  go.mod
  go.sum
  vendor/github.com/openshift/api/build/v1/generated.proto
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/build/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/imageregistry/v1/00-crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-custom-resource-definition.yaml
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer_polling.go
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apps.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/bindata/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/bindata/bindata.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#995 Restrict log permissions
  bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml
  bindata/v4.1.0/kube-apiserver/pod.yaml
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, lgtm
