Repository openshift/cluster-kube-apiserver-operator, pull requests merged in 2020-11, with the labels that each got.

#1000 Use 'kubernetes.io/tls' instead of SecretTypeTLS which is not being substituted
  bindata/bootkube/manifests/secret-aggregator-client-signer.yaml
  bindata/bootkube/manifests/secret-control-plane-client-signer.yaml
  bindata/bootkube/manifests/secret-kube-apiserver-to-kubelet-signer.yaml
  bindata/bootkube/manifests/secret-loadbalancer-serving-signer.yaml
  bindata/bootkube/manifests/secret-localhost-serving-signer.yaml
  bindata/bootkube/manifests/secret-service-network-serving-signer.yaml
Labels: approved, lgtm

#985 Bug 1888862: [4.6] set servicesSubnet correctly in dual-stack clusters
  bindata/bootkube/config/bootstrap-config-overrides.yaml
  go.mod
  pkg/cmd/render/render_test.go
  pkg/operator/configobservation/network/observe_network.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1002 Revert "Set dnsPolicy ClusterFirstWithHostNet to match hostNetwork"
  bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml
  bindata/v4.1.0/kube-apiserver/pod.yaml
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, lgtm

#1001 picks up setting `TCP_USER_TIMEOUT` socket option
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/config/client/client_config.go
  vendor/github.com/openshift/library-go/pkg/network/dialer.go
  vendor/github.com/openshift/library-go/pkg/network/dialer_linux.go
  vendor/github.com/openshift/library-go/pkg/network/dialer_others.go
  vendor/modules.txt
Labels: approved, lgtm

#1004 token webhook auth: set tokenreview API to v1
  pkg/operator/configobservation/auth/webhook_authenticator.go
Labels: approved, lgtm

#1006 Support user provided service-account-signing-key and issuer
  bindata/bootkube/config/bootstrap-config-overrides.yaml
  bindata/bootkube/manifests/secret-bound-sa-token-signing-key.yaml
  pkg/cmd/render/render.go
  pkg/cmd/render/render_test.go
Labels: approved, lgtm

#1009 Bug 1895959: don't allow upgrades when webhooktokenauthenticators are set
  pkg/operator/starter.go
  pkg/operator/webhookauthenticatorupgradablecontroller/webhookauthenticatorupgradablecontroller.go
  pkg/operator/webhookauthenticatorupgradablecontroller/webhookauthenticatorupgradablecontroller_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1011 Bug 1900635: Revert "Merge pull request #1006 from abhinavdahiya/user-provided-sa-signing-key"
  bindata/bootkube/config/bootstrap-config-overrides.yaml
  bindata/bootkube/manifests/secret-bound-sa-token-signing-key.yaml
  pkg/cmd/render/render.go
  pkg/cmd/render/render_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1012 Support user provided service-account-signing-key and issuer
  bindata/bootkube/config/bootstrap-config-overrides.yaml
  bindata/bootkube/manifests/secret-bound-sa-token-signing-key.yaml
  pkg/cmd/render/render.go
  pkg/cmd/render/render_test.go
  pkg/operator/boundsatokensignercontroller/controller.go
Labels: approved, lgtm

#1013 Always set service-account-issuer flag
  bindata/bootkube/config/bootstrap-config-overrides.yaml
  pkg/cmd/render/render_test.go
Labels: approved, lgtm
