Repository openshift/cluster-kube-apiserver-operator, pull requests merged in 2021-02, with the labels that each got.

#1034 Remove tnozicka and add soltysh to OWNERS
  OWNERS
Labels: approved, bugzilla/valid-bug, lgtm

#1032 Bug 1920159: kube-apiservers overstate steady-state CPU needs slightly
  bindata/v4.1.0/kube-apiserver/pod.yaml
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1037 Bug 1883790: Revert "force cert rotation every couple days for development: aggregator-client-signer"
  pkg/operator/certrotationcontroller/certrotationcontroller.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, group-lead-approved, lgtm

#1036 Bug 1926867: competing connectivitycheckcontrollers cause pod restarts during upgrades
  go.mod
  go.sum
  pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
  vendor/github.com/openshift/library-go/pkg/config/serving/server.go
  vendor/github.com/openshift/library-go/pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/admission.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/test_helpers.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1040 Bug 1926465: bootstrap: add --advertise-address=pod.status.hostIP
  bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1038 add rolebinding for delegated in-cluster authentication
  bindata/v4.1.0/kube-apiserver/delegated-incluster-authentication-rolebinding.yaml
  pkg/operator/starter.go
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, lgtm

#1046 Speed up port reuse via SO_REUSEADDR
  bindata/v4.1.0/kube-apiserver/pod.yaml
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, lgtm

#1018 add DeprecatedAPIInUse alert
  go.mod
  go.sum
  manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml
  test/e2e/deprecated_api_test.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/LICENSE
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/go.mod
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/go.sum
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/register.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/doc.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/register.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/thanos_types.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/types.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1alpha1/alertmanager_config_types.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1alpha1/doc.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1alpha1/register.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/LICENSE
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/clientset.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/doc.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/scheme/doc.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/scheme/register.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/alertmanager.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/doc.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/generated_expansion.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/monitoring_client.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/podmonitor.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/probe.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/prometheus.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/prometheusrule.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/servicemonitor.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/thanosruler.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/typed/monitoring/v1alpha1/alertmanagerconfig.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/typed/monitoring/v1alpha1/doc.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/typed/monitoring/v1alpha1/generated_expansion.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/typed/monitoring/v1alpha1/monitoring_client.go
  vendor/modules.txt
Labels: approved, lgtm

#1043 clean up: uses a static encryption provider form the library-go
  go.mod
  go.sum
  pkg/operator/starter.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/static_provider.go
  vendor/modules.txt
Labels: approved, lgtm

#1048 bump to get latest openshift api
  bindata/bootkube/config/bootstrap-config-overrides.yaml
  go.mod
  go.sum
  vendor/github.com/openshift/api/Dockerfile.build
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_scheduler.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_12_etcd-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_20_kube-apiserver-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-controller-manager-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-scheduler-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_40_cloud-credential-operator_00_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster-authentication-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_console-operator.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-patch
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/types_authentication.go
  vendor/github.com/openshift/api/operator/v1/types_cloudcredential.go
  vendor/github.com/openshift/api/operator/v1/types_console.go
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/types_etcd.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1alpha1/0000_10_config-operator_01_imagecontentsourcepolicy.crd.yaml
  vendor/github.com/openshift/api/operator/v1alpha1/types_image_content_source_policy.go
  vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/project/v1/generated.proto
  vendor/github.com/openshift/api/project/v1/types.go
  vendor/github.com/openshift/api/project/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/modules.txt
Labels: approved, lgtm

#1049 render initial SCC in addition to having the CVO reconcile
  Dockerfile.rhel7
  bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_cr-scc-anyuid.yaml
  bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_cr-scc-hostaccess.yaml
  bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_cr-scc-hostmount-anyuid.yaml
  bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_cr-scc-hostnetwork.yaml
  bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_cr-scc-nonroot.yaml
  bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_cr-scc-privileged.yaml
  bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_cr-scc-restricted.yaml
  bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_scc-anyuid.yaml
  bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_scc-hostaccess.yaml
  bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_scc-hostmount-anyuid.yaml
  bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_scc-hostnetwork.yaml
  bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_scc-nonroot.yaml
  bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_scc-privileged.yaml
  bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_scc-restricted.yaml
Labels: approved, lgtm

#1047 token inactivity e2e: wait for KAS to stop progressing
  test/e2e/token_inactivity_timeout_test.go
Labels: approved, lgtm

#1052 make KAS-o upgradable even when webhook authenticators are set
  pkg/operator/starter.go
  pkg/operator/webhookauthenticatorupgradablecontroller/webhookauthenticatorupgradablecontroller.go
  pkg/operator/webhookauthenticatorupgradablecontroller/webhookauthenticatorupgradablecontroller_test.go
Labels: approved, lgtm
