Repository openshift/cluster-kube-apiserver-operator, pull requests merged in 2021-09, with the labels that each got.

#1221 Bug 1969404: remove override for fast cert rotation
  pkg/operator/certrotationcontroller/certrotationcontroller.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1220 Bug 1985447: Add namespace label to remaining apiserver alerts
  bindata/assets/alerts/api-usage.yaml
  bindata/assets/alerts/audit-errors.yaml
  bindata/assets/alerts/cpu-utilization.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1219 Bug 2000608: static pod startup monitor should log to a log file in addition to stderr
  go.mod
  go.sum
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  vendor/github.com/openshift/api/go.mod
  vendor/github.com/openshift/api/go.sum
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissionregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiextensions.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/policy.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/rbac.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/object_merger.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/startupmonitor/assets/startup-monitor-pod.yaml
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/startupmonitor/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/startupmonitor/pod_template.go
  vendor/github.com/openshift/library-go/test/library/encryption/assertion.go
  vendor/github.com/openshift/library-go/test/library/encryption/helpers.go
  vendor/github.com/openshift/library-go/test/library/encryption/scenarios.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1199 Bug 1998552: Enforce OpenShift's defined kubelet version skew policies
  pkg/operator/kubeletversionskewcontroller/kubelet_version_skew_controller.go
  pkg/operator/kubeletversionskewcontroller/kubelet_version_skew_controller_test.go
  pkg/operator/starter.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1217 bindata: enable podsecurity plugin
  bindata/assets/config/defaultconfig.yaml
Labels: lgtm, approved

#1214 Bug 1993800: bump(library-go): staticpod/installer: fix backoff of installers
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high

#1228 Bug 2001856: bump library-go to latest
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/cloudprovider/external.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1231 Enable PodSecurity admission by default
  bindata/assets/kube-apiserver/apiserver.openshift.io_apirequestcount.yaml
  bindata/bootkube/config/bootstrap-config-overrides.yaml
  go.mod
  go.sum
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_oauth.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/install.go
  vendor/github.com/openshift/api/machine/install.go
  vendor/github.com/openshift/api/machine/v1beta1/0000_10_machine.crd.yaml
  vendor/github.com/openshift/api/machine/v1beta1/doc.go
  vendor/github.com/openshift/api/machine/v1beta1/generated.pb.go
  vendor/github.com/openshift/api/machine/v1beta1/generated.proto
  vendor/github.com/openshift/api/machine/v1beta1/register.go
  vendor/github.com/openshift/api/machine/v1beta1/types_awsprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/types_machine.go
  vendor/github.com/openshift/api/machine/v1beta1/types_provider.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/oauth/v1/generated.proto
  vendor/github.com/openshift/api/oauth/v1/types.go
  vendor/github.com/openshift/api/oauth/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-patch
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: lgtm, approved

#1215 Bug 1992541: all the alert rules' annotations "summary" and "description" should comply with the OpenShift alerting guidelines
  bindata/assets/alerts/api-usage.yaml
  bindata/assets/alerts/cpu-utilization.yaml
  manifests/0000_90_kube-apiserver-operator_03_servicemonitor.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1234 podsecurity: enforce privileged for kube-apiserver
  bindata/assets/kube-apiserver/ns.yaml
  bindata/bootkube/manifests/00_openshift-kube-apiserver-ns.yaml
Labels: lgtm, approved

#1233 uses the etcd observers provided by library-go
  go.mod
  go.sum
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/configobservation/etcdendpoints/observe_etcd_endpoints.go
  pkg/operator/configobservation/etcdendpoints/observe_etcd_endpoints_test.go
  pkg/operator/configobservation/interfaces.go
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-patch
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/library-go/pkg/cloudprovider/external.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/etcd/OWNERS
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/etcd/listers.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/etcd/observe_etcd_endpoints.go
  vendor/modules.txt
Labels: lgtm, approved
