Repository openshift/cluster-kube-apiserver-operator, pull requests merged in 2021-12, with the labels that each got.

#1263 test/e2e/TestNamedCertificates: sign using root CA
  test/e2e/user_certs_test.go
  test/library/crypto.go
Labels: lgtm, approved

#1264 bump(library-go): to gather a fix for static pod UID version
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/network/dialer_linux.go
  vendor/github.com/openshift/library-go/pkg/network/dialer_others.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissionregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/internal/flock/flock_linux.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/internal/flock/flock_others.go
  vendor/modules.txt
Labels: lgtm, approved

#1268 [release-4.9] Bug 2029504: encryption-controller: sync secrets conditionally
  go.mod
  go.sum
  pkg/operator/starter.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/deployer/revisionedpod.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/certsyncpod/certsync_controller.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-low, backport-risk-assessed

#1270 bump(openshift/build-machinery-go)
  go.mod
  go.sum
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yaml-patch.mk
  vendor/modules.txt
Labels: lgtm, approved

#1267 reduce alert severity to warning where appropriate
  bindata/assets/alerts/cpu-utilization.yaml
  bindata/assets/alerts/kube-apiserver-slos-basic.yaml
  bindata/assets/alerts/kube-apiserver-slos-extended.yaml
Labels: lgtm, approved

#1262 Bug 2008462: config: disable pod security admission
  bindata/assets/config/defaultconfig.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1273 Upgrade library-go version
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
  vendor/modules.txt
Labels: lgtm, approved
