Repository openshift/cluster-kube-apiserver-operator, pull requests merged in 2021-05, with the labels that each got.

#1121 bug 1955226: update library-go to avoid CRD update loop
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/apiextensions.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1125 Bug 1956081: Update bootstrap manifest namespace for SNO compatibility
  bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1123 bug 1954937: update printer columns for apirequestcounts
  bindata/v4.1.0/kube-apiserver/apiserver.openshift.io_apirequestcount.yaml
  go.mod
  go.sum
  pkg/operator/v410_00_assets/bindata.go
  vendor/github.com/openshift/api/apiserver/v1/apiserver.openshift.io_apirequestcount.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_console-operator.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_console.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/quota/v1/0000_03_quota-openshift_01_clusterresourcequota.crd.yaml
  vendor/github.com/openshift/api/quota/v1/0000_03_quota-openshift_01_clusterresourcequota.crd.yaml-merge-patch
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1124 Add a nominal request to the kube-apiserver init container
  bindata/v4.1.0/kube-apiserver/pod.yaml
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm

#1128 Bug 1958094: Add flock to kube-apiserver startup
  bindata/v4.1.0/kube-apiserver/pod.yaml
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1089 bug 1959513: add default policy, use lib go audit
  bindata/v4.1.0/kube-apiserver/audit-policies-cm.yaml
  pkg/cmd/render/render.go
  pkg/cmd/render/render_test.go
  pkg/operator/audit/audit.go
  pkg/operator/audit/audit_test.go
  pkg/operator/starter.go
  pkg/operator/v410_00_assets/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/audit_policies.go
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/bindata/bindata.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1133 fixup ci-operator.yaml
  .ci-operator.yaml
  Makefile
  go.sum
Labels: approved, lgtm

#1131 Bug 1943804: split encryption tests
  Makefile
  test/e2e-encryption-rotation/encryption_rotation_test.go
  test/e2e-encryption/encryption_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1134 Set proper root image in .ci-operator.yaml
  .ci-operator.yaml
Labels: approved, bugzilla/valid-bug, lgtm

#1132 Bug 1961173: bump(*): library-go update
  go.mod
  go.sum
  pkg/operator/starter.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/condition_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/key_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/migration_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/prune_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/state_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/preconditions.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/monitoring.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/github.com/openshift/library-go/test/library/apiserver/apiserver.go
  vendor/github.com/openshift/library-go/test/library/pod_same_revision.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1127 bug 1957645: avoid warm loop for writing prometheus rules
  bindata/v4.1.0/alerts/cpu-utilization.yaml
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1079 Bug 1943804: increases termination timeouts for AWS
  Makefile
  bindata/v4.1.0/kube-apiserver/pod.yaml
  go.mod
  go.sum
  pkg/operator/configobservation/apiserver/observe_termination_duration.go
  pkg/operator/configobservation/apiserver/observe_termination_duration_test.go
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
  pkg/operator/v410_00_assets/bindata.go
  pkg/test/assets_test.go
  test/e2e/user_certs_test.go
  vendor/github.com/openshift/library-go/test/library/encryption/e_log.go
  vendor/github.com/openshift/library-go/test/library/encryption/helpers.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1136 Bug 1963730: Bump library-go for unrevisioned resourcs
  go.mod
  go.sum
  pkg/operator/starter.go
  vendor/github.com/openshift/api/build/v1/generated.proto
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/build/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/go.mod
  vendor/github.com/openshift/api/go.sum
  vendor/github.com/openshift/api/operator/v1/0000_10_config-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_console-operator.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_config.go
  vendor/github.com/openshift/api/operator/v1/types_console.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/policy.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/unstructured.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/volumesnapshotclass.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/policy.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/certsyncpod/certsync_cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/certsyncpod/certsync_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
  vendor/k8s.io/api/core/v1/annotation_key_constants.go
  vendor/k8s.io/apimachinery/pkg/api/resource/quantity_proto.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm
