Repository openshift/cluster-kube-apiserver-operator, pull requests merged in 2021-06, with the labels that each got.

#1126 Bug 1953798: Add apiserver burn rate SLO alerts
  bindata/v4.1.0/alerts/kube-apiserver-slos.yaml
  pkg/operator/starter.go
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1099 Bug 1956606: Revert "Merge pull request #1060" (Use the flow schema introduced in upstream)
  manifests/0000_20_kube-apiserver-operator_08_flowschema.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1129 Bug 1967090: webhookauth observer: set cache TTL to 30s
  pkg/operator/configobservation/auth/webhook_authenticator.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1140 Bug 1967090: Revert webhookauth observer: set cache TTL to 30s
  pkg/operator/configobservation/auth/webhook_authenticator.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1141 Bug 1966410: alert: exclude kcm samples from removed API alerts
  bindata/v4.1.0/alerts/api-usage.yaml
  pkg/operator/v410_00_assets/bindata.go
  pkg/test/assets_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1139 Bug 1907309: Add APF StorageVersionMigration manifest
  bindata/v4.1.0/kube-apiserver/storage-version-migration-flowschema.yaml
  bindata/v4.1.0/kube-apiserver/storage-version-migration-prioritylevelconfiguration.yaml
  go.mod
  go.sum
  pkg/operator/starter.go
  pkg/operator/v410_00_assets/bindata.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/eventfilters.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/migration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/migration.go
  vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1144 Bug 1953798: Fix incorrect 'scope' label in SLO recording rules
  bindata/v4.1.0/alerts/kube-apiserver-slos.yaml
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1142 Bug 1946479: inject SA tokens as projected volumes to KAS install and prune pods
  go.mod
  go.sum
  manifests/0000_20_kube-apiserver-operator_06_deployment.yaml
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/bindata/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/bindata/bindata.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1143 Bug 1921139: remove override for fast cert rotation for release
  pkg/operator/certrotationcontroller/certrotationcontroller.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1147 Bug 1921139: Revert "remove override for fast cert rotation for release"
  pkg/operator/certrotationcontroller/certrotationcontroller.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1145 kube-apiserver failed to load SNI cert and key
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/bindata/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/condition_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/migration_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/prune_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/state_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/preconditions.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/certsyncpod/certsync_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/file_utils.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/copy.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/prune/cmd.go
  vendor/modules.txt
Labels: approved, lgtm

#1149 Bug 1956081: add sigterm handler to insecurereadyz
  go.mod
  pkg/cmd/insecurereadyz/readyz.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1158 Bug 1974716: SA token issuer observer: fix observing api-audiences
  pkg/operator/configobservation/auth/auth_serviceaccountissuer.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1151 Bug 1964231: Ensure kubelet client cert change does not require a restart
  bindata/v4.1.0/config/defaultconfig.yaml
  pkg/operator/starter.go
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1163 bump library-go to get context fixes
  go.mod
  go.sum
  pkg/cmd/certregenerationcontroller/cabundlesyncer.go
  pkg/operator/boundsatokensignercontroller/controller.go
  pkg/operator/nodekubeconfigcontroller/nodekubeconfigcontroller.go
  pkg/operator/starter.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/audit_policies.go
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/bindata/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/legacy.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/migration_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/state_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissionregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiextensions.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apps.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/credentialsrequest.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/migration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/monitoring.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/policy.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/rbac.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/unstructured.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/volumesnapshotclass.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
  vendor/k8s.io/client-go/restmapper/category_expansion.go
  vendor/k8s.io/client-go/restmapper/discovery.go
  vendor/k8s.io/client-go/restmapper/shortcut.go
  vendor/modules.txt
Labels: approved, lgtm

#1164 reduces shutdown-delay-duration to 0s for SNO
  pkg/operator/configobservation/apiserver/observe_termination_duration.go
  pkg/operator/configobservation/apiserver/observe_termination_duration_test.go
Labels: approved, lgtm
