Repository openshift/cluster-kube-apiserver-operator, pull requests merged in 2021-04, with the labels that each got.

#1065 bug 1939226: make kube-apiserver readiness checks, check readyz
  bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml
  bindata/v4.1.0/kube-apiserver/pod.yaml
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1092 Update DeprecatedAPIInUse alert for new release.
  manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml
Labels: approved, lgtm, priority/critical-urgent

#1098 Bug 1948431: Bump openshift/api to get the necessary CSIMigration feature gates
  go.mod
  go.sum
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/apiserver/install.go
  vendor/github.com/openshift/api/apiserver/v1/apiserver.openshift.io_deprecatedapirequests.yaml
  vendor/github.com/openshift/api/apiserver/v1/doc.go
  vendor/github.com/openshift/api/apiserver/v1/register.go
  vendor/github.com/openshift/api/apiserver/v1/types_deprecatedapirequest.go
  vendor/github.com/openshift/api/apiserver/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/apiserver/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/install.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1102 bug 1949306: add deprecated CRD manifest
  Makefile
  bindata/v4.1.0/kube-apiserver/apiserver.openshift.io_deprecatedapirequests.yaml
  manifests/0000_20_kube-apiserver-operator_07_clusteroperator.yaml
  pkg/operator/starter.go
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1045 Bug 1949593: rename DeprecatedAPIInUse alert to APIRemovedInNextReleaseInUse
  manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml
  test/e2e/deprecated_api_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1103 Bug 1949418: bump(*): vendor update
  go.mod
  go.sum
  pkg/operator/starter.go
  vendor/github.com/openshift/library-go/pkg/config/client/transport.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/base_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/monitoring.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/unstructured.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/unstructured.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installerstate/installer_state_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/args.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1055 Bug 1932165: variables in DeprecatedAPIInUse alert's annotations.message are not parsed to existing values
  manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml
  pkg/test/assets_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1095 Add management workload annotations
  bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml
  bindata/bootkube/manifests/00_openshift-kube-apiserver-ns.yaml
  bindata/bootkube/manifests/00_openshift-kube-apiserver-operator-ns.yaml
  bindata/v4.1.0/kube-apiserver/ns.yaml
  bindata/v4.1.0/kube-apiserver/pod.yaml
  bindata/v4.1.0/kube-apiserver/recovery-pod.yaml
  manifests/0000_20_kube-apiserver-operator_00_namespace.yaml
  manifests/0000_20_kube-apiserver-operator_06_deployment.yaml
  pkg/operator/v410_00_assets/bindata.go
  pkg/recovery/apiserver_test.go
Labels: approved, bugzilla/valid-bug, lgtm

#1044 Bug 1949591: tweak removed api in use alert expression
  manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1106 bug 1949306: switch APIRequestCount from DeprecatedAPIRequest
  Makefile
  bindata/v4.1.0/kube-apiserver/apiserver.openshift.io_apirequestcount.yaml
  go.mod
  go.sum
  pkg/operator/starter.go
  pkg/operator/v410_00_assets/bindata.go
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/apiserver/v1/apiserver.openshift.io_apirequestcount.yaml
  vendor/github.com/openshift/api/apiserver/v1/register.go
  vendor/github.com/openshift/api/apiserver/v1/types_apirequestcount.go
  vendor/github.com/openshift/api/apiserver/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/apiserver/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/build/v1/generated.pb.go
  vendor/github.com/openshift/api/build/v1/generated.proto
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/build/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/build/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/cloudnetwork/OWNERS
  vendor/github.com/openshift/api/cloudnetwork/install.go
  vendor/github.com/openshift/api/cloudnetwork/v1/001-cloudprivateipconfig.crd.yaml
  vendor/github.com/openshift/api/cloudnetwork/v1/001-cloudprivateipconfig.crd.yaml-patch
  vendor/github.com/openshift/api/cloudnetwork/v1/doc.go
  vendor/github.com/openshift/api/cloudnetwork/v1/generated.pb.go
  vendor/github.com/openshift/api/cloudnetwork/v1/generated.proto
  vendor/github.com/openshift/api/cloudnetwork/v1/register.go
  vendor/github.com/openshift/api/cloudnetwork/v1/types.go
  vendor/github.com/openshift/api/cloudnetwork/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/cloudnetwork/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_console.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_dns.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_ingress.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_network.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/install.go
  vendor/github.com/openshift/api/network/v1/001-clusternetwork-crd.yaml
  vendor/github.com/openshift/api/network/v1/002-hostsubnet-crd.yaml
  vendor/github.com/openshift/api/network/v1/003-netnamespace-crd.yaml
  vendor/github.com/openshift/api/network/v1/004-egressnetworkpolicy-crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_console-operator.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_dns-operator_00-custom-resource-definition.yaml
  vendor/github.com/openshift/api/operator/v1/types_console.go
  vendor/github.com/openshift/api/operator/v1/types_dns.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1107 bug 1949306: collect new style counts
  manifests/0000_20_kube-apiserver-operator_07_clusteroperator.yaml
  pkg/operator/starter.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1091 Bug 1949956: add minreadyseconds to ensure we don't have an LB outage on kas
  pkg/operator/starter.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1110 Bug 1948311: DelegatingAuthenticationOptions TokenReview request timeout
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/authentication/authenticatorfactory/delegating.go
  vendor/k8s.io/apiserver/pkg/server/options/authentication.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/metrics/metrics.go
  vendor/k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/queueset/queueset.go
  vendor/k8s.io/apiserver/plugin/pkg/authenticator/token/webhook/webhook.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1109 Bug 1951637: don't roll a new revision on tokentimeout changes
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/configobservation/oauth/doc.go
  pkg/operator/configobservation/oauth/observe_tokenconfig.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1116 Bug 1953563: Add .ci-operator.yaml with build_root_image
  .ci-operator.yaml
  Makefile
  go.mod
  go.sum
  vendor/github.com/openshift/build-machinery-go/Makefile
  vendor/github.com/openshift/build-machinery-go/README.md
  vendor/github.com/openshift/build-machinery-go/make/default.example.mk.help.log
  vendor/github.com/openshift/build-machinery-go/make/golang.example.mk.help.log
  vendor/github.com/openshift/build-machinery-go/make/golang.mk
  vendor/github.com/openshift/build-machinery-go/make/operator.example.mk.help.log
  vendor/github.com/openshift/build-machinery-go/make/targets/golang/version.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/profile-manifests.mk
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1115 bug 1949306: stop created deprecateapirequests
  bindata/v4.1.0/alerts/api-usage.yaml
  bindata/v4.1.0/alerts/cpu-utilization.yaml
  bindata/v4.1.0/alerts/kube-apiserver-requests.yaml
  bindata/v4.1.0/kube-apiserver/apiserver.openshift.io_apirequestcount.yaml
  bindata/v4.1.0/kube-apiserver/apiserver.openshift.io_deprecatedapirequests.yaml
  go.mod
  go.sum
  manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml
  pkg/operator/starter.go
  pkg/operator/v410_00_assets/bindata.go
  test/e2e/deprecated_api_test.go
  vendor/github.com/openshift/api/apiserver/v1/apiserver.openshift.io_apirequestcount.yaml
  vendor/github.com/openshift/api/apiserver/v1/apiserver.openshift.io_deprecatedapirequests.yaml
  vendor/github.com/openshift/api/apiserver/v1/register.go
  vendor/github.com/openshift/api/apiserver/v1/types_apirequestcount.go
  vendor/github.com/openshift/api/apiserver/v1/types_deprecatedapirequest.go
  vendor/github.com/openshift/api/apiserver/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/apiserver/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/cloudnetwork/v1/001-cloudprivateipconfig.crd.yaml
  vendor/github.com/openshift/api/cloudnetwork/v1/generated.proto
  vendor/github.com/openshift/api/cloudnetwork/v1/types.go
  vendor/github.com/openshift/api/config/v1/0000_03_config-operator_01_operatorhub.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_build.crd.yaml
  vendor/github.com/openshift/api/helm/v1beta1/0000_10-helm-chart-repository.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/samples/v1/0000_10_samplesconfig.crd.yaml
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/monitoring.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/unstructured.go
  vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1111 Rename workload annotations
  bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml
  bindata/v4.1.0/kube-apiserver/pod.yaml
  bindata/v4.1.0/kube-apiserver/recovery-pod.yaml
  manifests/0000_20_kube-apiserver-operator_06_deployment.yaml
  pkg/operator/v410_00_assets/bindata.go
  pkg/recovery/apiserver_test.go
Labels: approved, bugzilla/valid-bug, lgtm

#1120 bug 1953798: stop doing live gets for optional cert syncer files that don't exist on disk yet
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_image.crd.yaml
  vendor/github.com/openshift/api/operator/v1alpha1/0000_10_config-operator_01_imagecontentsourcepolicy.crd.yaml
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/certsyncpod/certsync_controller.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1122 bug 1955256: stop collecting deprecateapicount
  manifests/0000_20_kube-apiserver-operator_07_clusteroperator.yaml
  pkg/operator/starter.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
