Repository openshift/cluster-kube-apiserver-operator, pull requests merged in 2021-08, with the labels that each got.

#1194 Bug 1985997: staticpod/startupmonitor: shorten and unify reason strings
  pkg/operator/startupmonitorreadiness/readiness_checks.go
  pkg/operator/startupmonitorreadiness/readiness_checks_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1197 Bug 1985997: scaffolding for e2e tests for the static pod monitor
  Makefile
  test/e2e-sno-disruptive/sno_disruptive_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1196 Bug 1985997: readiness checks handle network errors better
  pkg/operator/startupmonitorreadiness/readiness_checks.go
  pkg/operator/startupmonitorreadiness/readiness_checks_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1191 Bug 1989461: kube-apiserver: make flock wait for release and remove port wait
  bindata/assets/kube-apiserver/pod.yaml
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1200 Bug 1989633: bump(library-go): staticpod/installer: skip backoff if lastAvailableRevision > targetRevision
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/rbac.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/startupmonitor/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/startupmonitor/monitor.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1190 Bug 1986829: metrics: use client cert auth for metrics scraping
  manifests/0000_90_kube-apiserver-operator_03_servicemonitor.yaml
  manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1198 Bug 1985997: Enable static pod fallback logic for SNO, with disruptive e2e test
  go.mod
  go.sum
  pkg/operator/startupmonitorreadiness/enablement.go
  test/e2e-sno-disruptive/helpers.go
  test/e2e-sno-disruptive/sno_disruptive_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/startupmonitorcondition/startup_monitor_condition.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodfallback/static_pod_fallback_condition.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1202 Bug 1990610: prevent panic in startup monitor enablement check
  pkg/operator/startupmonitorreadiness/enablement.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1201 Bug 1985073: use 1m resolution for control plane cpu alerts
  bindata/assets/alerts/cpu-utilization.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1203 Bug 1991357: bump library.go
  bindata/assets/alerts/api-usage.yaml
  go.mod
  go.sum
  test/e2e/deprecated_api_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1185 Bug 1985447: Add namespace labels to kube-apiserver-operator alerts
  bindata/assets/alerts/kube-apiserver-slos.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1206 Bug 1994257: Actually create prometheus rule for audit error alert
  pkg/operator/starter.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1207 Bug 1994643: enable shutdown-send-retry-after and startup-send-retry-after-until-ready
  bindata/assets/config/defaultconfig.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#1210 Bug 1996032: Bump kube libraries to 1.22.1 GA version
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_ingress.crd.yaml
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/go.mod
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/images.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/kustomize.mk
  vendor/github.com/sirupsen/logrus/.travis.yml
  vendor/github.com/sirupsen/logrus/CHANGELOG.md
  vendor/github.com/sirupsen/logrus/README.md
  vendor/github.com/sirupsen/logrus/entry.go
  vendor/github.com/sirupsen/logrus/go.sum
  vendor/github.com/sirupsen/logrus/json_formatter.go
  vendor/github.com/sirupsen/logrus/logger.go
  vendor/github.com/sirupsen/logrus/terminal_check_unix.go
  vendor/github.com/sirupsen/logrus/text_formatter.go
  vendor/golang.org/x/time/rate/rate.go
  vendor/k8s.io/apiserver/pkg/admission/metrics/metrics.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/webhook/mutating/dispatcher.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/webhook/validating/dispatcher.go
  vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go
  vendor/k8s.io/apiserver/pkg/server/deprecated_insecure_serving.go
  vendor/k8s.io/apiserver/pkg/server/options/audit.go
  vendor/k8s.io/apiserver/pkg/server/secure_serving.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/store.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1211 Bug 1994643: remove startup-send-retry-after-until-ready option
  bindata/assets/config/defaultconfig.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent
