Repository openshift/cluster-kube-apiserver-operator, pull requests merged in 2022-01, with the labels that each got.

#1276 Bug 2034484: library-go bump
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go
  vendor/github.com/openshift/library-go/pkg/controller/metrics/client_metrics.go
  vendor/github.com/openshift/library-go/pkg/controller/metrics/workqueue_metrics.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/resource_cache.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/bindata/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
  vendor/k8s.io/component-base/metrics/prometheus/clientgo/leaderelection/metrics.go
  vendor/k8s.io/component-base/metrics/prometheus/clientgo/metrics.go
  vendor/k8s.io/component-base/metrics/prometheus/restclient/metrics.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1288 Bug 2035986: Replace deprecated annotation
  bindata/assets/kube-apiserver/pod.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1249 Bug 2033784: set kube-apiserver degraded=true if webhook matches a virtual resource
  pkg/operator/webhooksupportabilitycontroller/conditions.go
  pkg/operator/webhooksupportabilitycontroller/degraded_webhook_admission_test.go
  pkg/operator/webhooksupportabilitycontroller/degraded_webhook_on_virtual_resource.go
  pkg/operator/webhooksupportabilitycontroller/degraded_webhook_on_virtual_resource_test.go
  pkg/operator/webhooksupportabilitycontroller/webhook_supportability_controller.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1291 Bug 2038968: bump(openshift/api): to get CSI migration gates switched off
  bindata/bootkube/config/bootstrap-config-overrides.yaml
  go.mod
  go.sum
  vendor/github.com/openshift/api/build/v1/generated.pb.go
  vendor/github.com/openshift/api/build/v1/generated.proto
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/build/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/build/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/imageregistry/v1/00-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/00_imageregistry.crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/00_imageregistry.crd.yaml-patch
  vendor/github.com/openshift/api/imageregistry/v1/01_imagepruner.crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/types.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1beta1/0000_10_machine.crd.yaml
  vendor/github.com/openshift/api/machine/v1beta1/0000_10_machineset.crd.yaml
  vendor/github.com/openshift/api/machine/v1beta1/types_machine.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1275 bug 2005901: Guard controller pdb
  go.mod
  go.sum
  pkg/operator/starter.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1294 Bug 2037856: bump library go
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/config/leaderelection/leaderelection.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/bindata/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1274 Bug 2037274: starter: include metrics controller
  go.mod
  go.sum
  manifests/0000_20_kube-apiserver-operator_03_configmap.yaml
  manifests/0000_20_kube-apiserver-operator_06_deployment.yaml
  pkg/operator/starter.go
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yaml-patch.mk
  vendor/github.com/openshift/library-go/pkg/crypto/missing_san.go
  vendor/github.com/openshift/library-go/pkg/operator/metricscontroller/legacy_cn_certs_sync.go
  vendor/github.com/openshift/library-go/pkg/operator/metricscontroller/metrics_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
  vendor/github.com/prometheus/client_golang/api/client.go
  vendor/github.com/prometheus/client_golang/api/prometheus/v1/api.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-urgent, backport-risk-assessed

#1295 bug 2005901: Sync the library-go
  go.mod
  go.sum
  pkg/operator/starter.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1284 Bug 2034559: alerts: update latency thresholds
  bindata/assets/alerts/kube-apiserver-slos-basic.yaml
  bindata/assets/alerts/kube-apiserver-slos-extended.yaml
  manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent
