Repository openshift/cluster-kube-apiserver-operator, pull requests merged in 2022-11, with the labels that each got.

#1380 Bug 2100429: Allow ephemeral volumes in all SCCs
  bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_scc-anyuid.yaml
  bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_scc-hostaccess.yaml
  bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_scc-hostmount-anyuid.yaml
  bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_scc-hostnetwork-v2.yaml
  bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_scc-hostnetwork.yaml
  bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_scc-nonroot-v2.yaml
  bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_scc-nonroot.yaml
  bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_scc-restricted-v2.yaml
  bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_scc-restricted.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1392 OCPBUGS-1601: CVE-2022-3259: enable HSTS for kube-apiserver
  bindata/assets/config/defaultconfig.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug

#1398 bootstrap-kube-apiserver: specify resources.requests
  bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml
Labels: lgtm, approved

#1401 OCPBUGS-2071: revert dev cert rotation
  pkg/operator/certrotationcontroller/certrotationcontroller.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug

#1405 OCPBUGS-3663: Revert "turn PodSecurity admission to enforce restricted globally"
  bindata/assets/config/defaultconfig.yaml
Labels: lgtm, approved, bugzilla/valid-bug, backport-risk-assessed, jira/severity-critical, jira/valid-bug

#1408 OCPBUGS-3929: update apf configuration to use v1beta2
  manifests/0000_20_kube-apiserver-operator_08_flowschema.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-moderate, jira/valid-bug

#1409 OCPBUGS-3985: update for featureset rendering
  bindata/assets/kube-apiserver/apiserver.openshift.io_apirequestcount.yaml
  go.mod
  go.sum
  pkg/operator/startupmonitorreadiness/readiness_checks.go
  pkg/test/assets_test.go
  vendor/github.com/openshift/library-go/pkg/assets/assets.go
  vendor/github.com/openshift/library-go/pkg/crypto/OWNERS
  vendor/github.com/openshift/library-go/pkg/operator/render/options/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/render/render.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/OWNERS
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installerstate/installer_state_controller.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug

#1410 OCPBUGS-3041: guard controller: set an explicit hostname to avoid name collisions
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/cloudprovider/external.go
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-important, jira/valid-bug
