Repository openshift/cluster-kube-apiserver-operator, pull requests merged in 2022-12, with the labels that each got.

#1407 OCPBUGS-3841: update apf configuration to use v1beta2
  manifests/0000_20_kube-apiserver-operator_08_flowschema.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-moderate, jira/valid-bug

#1411 OCPBUGS-4299: bootstrap-kube-apiserver: specify resources.requests
  bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug

#1417 Drop flags removed in k8s 1.26
  bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml
Labels: lgtm, approved

#1420 drop log-file flag removed in 1.26
  bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml
Labels: lgtm, approved
