Repository openshift/cluster-kube-apiserver-operator, pull requests merged in 2022-06, with the labels that each got.

#1358 Bug 2086519: exempt build controller SA from PodSecurity admission
  bindata/assets/config/defaultconfig.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#1359 Bug 2074031: Support tuning GOGC within a limited range.
  bindata/assets/kube-apiserver/pod.yaml
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#1360 Bug 2100347: Bump(openshift/library-go) latency profile observer, controller
  go.mod
  go.sum
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/starter.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/node/helpers.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/node/observe_latency_profile.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/node/suppress_config_updates.go
  vendor/github.com/openshift/library-go/pkg/operator/latencyprofilecontroller/controller.go
  vendor/github.com/openshift/library-go/pkg/operator/latencyprofilecontroller/profilerejectionchecker.go
  vendor/github.com/openshift/library-go/pkg/operator/latencyprofilecontroller/revisionconfigmatcher.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1307 Bug 2050407: revert dev cert rotation
  pkg/operator/certrotationcontroller/certrotationcontroller.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#1361 Bug 2100155: Add new alert on Pod Security violations
  bindata/assets/alerts/podsecurity-violations.yaml
  pkg/operator/starter.go
  pkg/test/assets_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1363 Bug 2101444: specify resource=pod for PSa violation alerts
  bindata/assets/alerts/podsecurity-violations.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent, staff-eng-approved

#1362 Bug 2100155: specify resource=pod for PSa violation alerts
  bindata/assets/alerts/podsecurity-violations.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent, staff-eng-approved
