Repository openshift/cluster-kube-apiserver-operator, pull requests merged in 2023-05, with the labels that each got.

#1488 Read feature manifest
  go.mod
  go.sum
  pkg/cmd/render/render.go
  pkg/cmd/render/render_test.go
  pkg/operator/configobservation/auth/podsecurityadmission.go
  pkg/operator/configobservation/auth/podsecurityadmission_test.go
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/starter.go
  vendor/github.com/openshift/api/config/v1/feature_gates.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/library-go/pkg/cloudprovider/external.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/featuregate.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/hardcoded_featuregate_reader.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/observe_featuregates.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/simple_featuregate_reader.go
  vendor/github.com/openshift/library-go/pkg/operator/render/options/config.go
  vendor/github.com/openshift/library-go/pkg/operator/render/options/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/generic.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug

#1490 read featureset from the manifests
  go.mod
  go.sum
  pkg/cmd/render/render.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/stable.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/library-go/pkg/operator/render/options/config.go
  vendor/github.com/openshift/library-go/pkg/operator/render/options/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/render/render.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug

#1497 OCPBUGS-14038: Update APIRemovedInNextRelease alerts
  bindata/assets/alerts/api-usage.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1492 OCPBUGS-13303: pkg/operator/startupmonitor: skip openshift-apiserver readiness check…
  pkg/operator/startupmonitorreadiness/readiness_checks.go
  pkg/operator/startupmonitorreadiness/readiness_checks_test.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1491 OCPBUGS-13547: Remove featureset flag and use only the manifest
  go.mod
  go.sum
  pkg/cmd/render/render.go
  pkg/cmd/render/render_test.go
  pkg/cmd/render/testdata/rendered/default-fg/featuregate.yaml
  pkg/operator/starter.go
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/route.crd.yaml
  vendor/github.com/openshift/api/route/v1/route.crd.yaml-patch
  vendor/github.com/openshift/api/route/v1/stable.route.testsuite.yaml
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/manifests/allrequestbodies-rules.yaml
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/manifests/writerequestbodies-rules.yaml
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/testdata/allrequestbodies.yaml
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/testdata/multipleCr.yaml
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/testdata/oauth.yaml
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/testdata/writerequestbodies.yaml
  vendor/github.com/openshift/library-go/pkg/operator/render/options/generic.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference
