Repository openshift/cluster-kube-apiserver-operator, pull requests merged in 2023-02, with the labels that each got.

#1436 update APIRemovedInNextRelease alerts
  bindata/assets/alerts/api-usage.yaml
Labels: lgtm, approved

#1431 API-1520: Update SLO alerts based on upstream improvements
  bindata/assets/alerts/kube-apiserver-slos-basic.yaml
  bindata/assets/alerts/kube-apiserver-slos-extended.yaml
Labels: lgtm, approved

#1432 OCPBUGS-5873: dashboard: use apiserver_storage_objects metric
  manifests/0000_90_kube-apiserver-operator_05_api_performance_dashboard.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-important, jira/valid-bug, jira/valid-reference

#1438 Update OWNERS to remove/replace adambkaplan
  pkg/operator/configobservation/images/OWNERS
Labels: lgtm, approved

#1442 bump(*)
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/startupmonitor/assets/startup-monitor-pod.yaml
  vendor/modules.txt
Labels: lgtm, approved

#1445 OCPBUGS-7369: Guard pod set readiness probe endpoint explicitly
  go.mod
  go.sum
  pkg/operator/starter.go
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/manifests/guard-pod.yaml
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1447 WRKLDS-705: Bump openshift/api to enable DynamicResourceAllocation through TechPreviewNoUpgrade
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/stable.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#1434 STOR-1051: Allow CSI inline volumes in all SCCs
  bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_scc-anyuid.yaml
  bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_scc-hostaccess.yaml
  bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_scc-hostmount-anyuid.yaml
  bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_scc-hostnetwork-v2.yaml
  bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_scc-hostnetwork.yaml
  bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_scc-nonroot-v2.yaml
  bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_scc-nonroot.yaml
  bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_scc-restricted-v2.yaml
  bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_scc-restricted.yaml
Labels: lgtm, approved, jira/valid-reference

#1448 OCPBUGS-7756: Guard pod set readiness probe endpoint explicitly
  go.mod
  go.sum
  pkg/operator/starter.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/manifests/guard-pod.yaml
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1439 [4.12] OCPBUGS-6789: make the bootstrap kube-apiserver honor cluster-wide featuregates
  bindata/bootkube/config/bootstrap-config-overrides.yaml
  pkg/cmd/render/render.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
