Repository openshift/cluster-kube-apiserver-operator, pull requests merged in 2023-09, with the labels that each got.

#1545 OCPBUGS-10362: revert dev cert rotation on 4.14
  pkg/operator/certrotationcontroller/certrotationcontroller.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1549 Bump openshift/* libs
  go.mod
  go.sum
  vendor/k8s.io/kube-openapi/pkg/cached/cache.go
  vendor/k8s.io/kube-openapi/pkg/handler/handler.go
  vendor/k8s.io/kube-openapi/pkg/handler3/handler.go
  vendor/modules.txt
Labels: lgtm, approved, acknowledge-critical-fixes-only

#1543 OCPBUGS-15504: manifest: remove kube-apiserver PrometheusRule
  manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference

#1542 OCPBUGS-18247: manifests: don't include recording rules when Console capability is not enabled
  manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml
  manifests/0000_90_kube-apiserver-operator_05_api_performance_dashboard.yaml
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#1547 OCPBUGS-19024: remove featuregate upgradeable controller that moved to cluster-config-operator
  pkg/operator/featureupgradablecontroller/feature_upgradeable_controller.go
  pkg/operator/featureupgradablecontroller/feature_upgradeable_controller_test.go
  pkg/operator/starter.go
  test/e2e/featuregate_upgradeable_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1557 OCPBUGS-16794: installerpod: change pod manifest mode to 0600
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/modules.txt
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1556 [release-4.14] OCPBUGS-19553: Update static pod manifests perms
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/modules.txt
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1560 bump(openshift/client-go,library-go)
  go.mod
  go.sum
  vendor/github.com/openshift/client-go/config/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/doc.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/factory.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/doc.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_authentication.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_cloudcredential.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_clustercsidriver.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_config.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_console.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_csisnapshotcontroller.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_dns.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_etcd.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_ingresscontroller.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_insightsoperator.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_kubeapiserver.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_kubecontrollermanager.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_kubescheduler.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_kubestorageversionmigrator.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_network.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_openshiftapiserver.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_openshiftcontrollermanager.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_serviceca.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_servicecatalogapiserver.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_servicecatalogcontrollermanager.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_storage.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1alpha1/fake/fake_etcdbackup.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1alpha1/fake/fake_imagecontentsourcepolicy.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1alpha1/fake/fake_olm.go
  vendor/github.com/openshift/client-go/operator/informers/externalversions/factory.go
  vendor/github.com/openshift/client-go/operatorcontrolplane/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/operatorcontrolplane/clientset/versioned/doc.go
  vendor/github.com/openshift/client-go/operatorcontrolplane/informers/externalversions/factory.go
  vendor/modules.txt
Labels: lgtm, approved

#1562 Update "deprecated API in use" alert expressions for 1.28.
  bindata/assets/alerts/api-usage.yaml
Labels: lgtm, approved

#1558 [release-4.13] OCPBUGS-19825: Update staticpod file permissions to conform with CIS benchmarks
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/modules.txt
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1561 Update required GV for ValidatingAdmissionPolicy gate.
  pkg/operator/configobservation/apienablement/observe_runtime_config.go
Labels: lgtm, approved
