Repository openshift/cluster-kube-apiserver-operator, pull requests merged in 2023-06, with the labels that each got.

#1503 OCPBUGS-13946: degraded_webhook.go x509: certificate signed by unknown authority
  pkg/operator/webhooksupportabilitycontroller/degraded_webhook.go
  pkg/operator/webhooksupportabilitycontroller/degraded_webhook_conversion.go
  pkg/operator/webhooksupportabilitycontroller/webhook_supportability_controller.go
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1511 OCPBUGS-14940: api_performance_dashboard: show apiserver_longrunning_requests metric
  manifests/0000_90_kube-apiserver-operator_05_api_performance_dashboard.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1484 OCPBUGS-3986: dashboard: use recording rules for most metrics
  manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml
  manifests/0000_90_kube-apiserver-operator_05_api_performance_dashboard.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1482 OCPBUGS-8404: pkg/operator/configobserver: check that the serving certificate refer…
  pkg/operator/configobservation/apiserver/observe_apiserver.go
  pkg/operator/configobservation/apiserver/observe_apiserver_test.go
  test/e2e/user_certs_test.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1520 api_performance_dashboard: show apiserver_request_total instead of apiserver_dropped_requests
  manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml
  manifests/0000_90_kube-apiserver-operator_05_api_performance_dashboard.yaml
Labels: lgtm, approved

#1518 api_performance_dashboard: show apiserver_longrunning_requests metric
  manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml
  manifests/0000_90_kube-apiserver-operator_05_api_performance_dashboard.yaml
Labels: lgtm, approved

#1516 update probes for best practices and consistency
  bindata/assets/kube-apiserver/pod.yaml
Labels: approved

#1510 OCPBUGS-13946: do not use one second timeout when asserting a webhook connection
  pkg/operator/webhooksupportabilitycontroller/degraded_webhook.go
  pkg/operator/webhooksupportabilitycontroller/degraded_webhook_admission.go
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1499 OCPBUGS-13763: dont log jwt tokens
  go.mod
  go.sum
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster_storage_operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/stable.storage.testsuite.yaml
  vendor/github.com/openshift/api/operator/v1/types_storage.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/library-go/pkg/cloudprovider/external.go
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/manifests/allrequestbodies-rules.yaml
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/manifests/writerequestbodies-rules.yaml
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/testdata/allrequestbodies.yaml
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/testdata/multipleCr.yaml
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/testdata/oauth.yaml
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/testdata/writerequestbodies.yaml
  vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller.go
  vendor/modules.txt
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference
