Repository openshift/cluster-kube-apiserver-operator, pull requests merged in 2023-12, with the labels that each got.

#1590 [release-4.14]: OCPBUGS-24022: Add workload partitioning annotation
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/manifests/guard-pod.yaml
  vendor/modules.txt
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#1591 [release-4.13]: OCPBUGS-24023: Add workload partitioning annotation
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/manifests/guard-pod.yaml
  vendor/modules.txt
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#1599 OCPBUGS-24701: ignore vendor folder in SAST scan
  .synk
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1600 [4.14] OCPBUGS-25384: psa cluster fleet evaluation
  go.mod
  go.sum
  pkg/operator/podsecurityreadinesscontroller/conditions.go
  pkg/operator/podsecurityreadinesscontroller/conditions_test.go
  pkg/operator/podsecurityreadinesscontroller/podsecurityreadinesscontroller.go
  pkg/operator/podsecurityreadinesscontroller/podsecurityreadinesscontroller_test.go
  pkg/operator/podsecurityreadinesscontroller/warning.go
  pkg/operator/podsecurityreadinesscontroller/warning_test.go
  pkg/operator/starter.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/rbac.go
  vendor/github.com/openshift/library-go/pkg/operator/status/condition.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
  vendor/k8s.io/pod-security-admission/LICENSE
  vendor/k8s.io/pod-security-admission/api/attributes.go
  vendor/k8s.io/pod-security-admission/api/constants.go
  vendor/k8s.io/pod-security-admission/api/doc.go
  vendor/k8s.io/pod-security-admission/api/helpers.go
  vendor/modules.txt
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1598 OCPBUGS-18761: revert dev cert rotation in 4.15
  pkg/operator/certrotationcontroller/certrotationcontroller.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1587 OCPBUGS-24005: webhookcontroller: report when a webhook resource is missing a caBundle provided by the service-ca-operator
  pkg/operator/webhooksupportabilitycontroller/conditions.go
  pkg/operator/webhooksupportabilitycontroller/degraded_webhook.go
  pkg/operator/webhooksupportabilitycontroller/degraded_webhook_admission.go
  pkg/operator/webhooksupportabilitycontroller/degraded_webhook_admission_test.go
  pkg/operator/webhooksupportabilitycontroller/degraded_webhook_conversion.go
  pkg/operator/webhooksupportabilitycontroller/degraded_webhook_conversion_test.go
  pkg/operator/webhooksupportabilitycontroller/degraded_webhook_on_virtual_resource.go
  pkg/operator/webhooksupportabilitycontroller/degraded_webhook_on_virtual_resource_test.go
  pkg/operator/webhooksupportabilitycontroller/degraded_webhook_test.go
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1606 OCPBUGS-24907: Updating ose-cluster-kube-apiserver-operator-container image to be consistent with ART
  .ci-operator.yaml
  Dockerfile.rhel7
  bindata/assets/alerts/api-usage.yaml
  go.mod
  go.sum
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference
