Repository openshift/cluster-kube-apiserver-operator, pull requests merged in 2023-08, with the labels that each got.

#1532 [release-4.13] OCPBUGS-17081: make webhook connection failure a warning in log
  pkg/operator/webhooksupportabilitycontroller/degraded_webhook.go
  pkg/operator/webhooksupportabilitycontroller/degraded_webhook_admission.go
  pkg/operator/webhooksupportabilitycontroller/degraded_webhook_conversion.go
  pkg/operator/webhooksupportabilitycontroller/webhook_supportability_controller.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#1536 Set runtime-config in lockstep with feature-gates, if needed.
  bindata/assets/config/defaultconfig.yaml
  bindata/bootkube/config/bootstrap-config-overrides.yaml
  pkg/cmd/render/render.go
  pkg/cmd/render/render_test.go
  pkg/operator/configobservation/apienablement/observe_runtime_config.go
  pkg/operator/configobservation/apienablement/observe_runtime_config_test.go
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
Labels: lgtm, approved

#1538 OCPBUGS-17436: Enable DynamicResourceAllocation API in kube-apiserver
  pkg/operator/configobservation/apienablement/observe_runtime_config.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1540 Reverts DynamicResourceAllocation enablement on techpreview
  bindata/assets/config/defaultconfig.yaml
  bindata/bootkube/config/bootstrap-config-overrides.yaml
  pkg/cmd/render/render.go
  pkg/cmd/render/render_test.go
  pkg/operator/configobservation/apienablement/observe_runtime_config.go
  pkg/operator/configobservation/apienablement/observe_runtime_config_test.go
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
Labels: lgtm, approved, do-not-merge/hold, jira/valid-bug

#1541 OCPBUGS-17436: Unrevert 1536 and 1538.
  bindata/assets/config/defaultconfig.yaml
  bindata/bootkube/config/bootstrap-config-overrides.yaml
  pkg/cmd/render/render.go
  pkg/cmd/render/render_test.go
  pkg/operator/configobservation/apienablement/observe_runtime_config.go
  pkg/operator/configobservation/apienablement/observe_runtime_config_test.go
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference
