Repository openshift/cluster-kube-apiserver-operator, pull requests merged in 2023-01, with the labels that each got.

#1377 make api team approver
  OWNERS
Labels: lgtm, approved

#1425 Revert "drop log-file flag removed in 1.26"
  bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml
Labels: lgtm, approved

#1416 OCPBUGS-4478: guard controller: set an explicit hostname to avoid name collisions
  bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml
  bindata/bootkube/manifests/secret-aggregator-client-signer.yaml
  bindata/bootkube/manifests/secret-bound-sa-token-signing-key.yaml
  bindata/bootkube/manifests/secret-control-plane-client-signer.yaml
  bindata/bootkube/manifests/secret-kube-apiserver-to-kubelet-signer.yaml
  bindata/bootkube/manifests/secret-loadbalancer-serving-signer.yaml
  bindata/bootkube/manifests/secret-localhost-serving-signer.yaml
  bindata/bootkube/manifests/secret-service-network-serving-signer.yaml
  go.mod
  go.sum
  pkg/test/assets_test.go
  vendor/github.com/openshift/library-go/pkg/assets/assets.go
  vendor/github.com/openshift/library-go/pkg/operator/render/options/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/render/render.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug

#1427 remove use of deprecated klog flags
  bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml
Labels: lgtm, approved

#1419 make the bootstrap kube-apiserver honor cluster-wide featuregates
  bindata/bootkube/config/bootstrap-config-overrides.yaml
  pkg/cmd/render/render.go
Labels: lgtm, approved

#1391 Fix typo in PodSecurityViolation alert's description
  bindata/assets/alerts/podsecurity-violations.yaml
Labels: lgtm, approved

#1428 OCPBUGS-272: Remove duplicate find word in error msg for degraded webhook
  pkg/operator/webhooksupportabilitycontroller/degraded_webhook.go
  pkg/operator/webhooksupportabilitycontroller/degraded_webhook_admission_test.go
  pkg/operator/webhooksupportabilitycontroller/degraded_webhook_conversion_test.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug

#1412 OCPBUGS-4301: bootstrap-kube-apiserver: specify resources.requests
  bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#1429 OCPBUGS-4551: guard controller: set an explicit hostname to avoid name collisions
  bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml
  bindata/bootkube/manifests/secret-aggregator-client-signer.yaml
  bindata/bootkube/manifests/secret-bound-sa-token-signing-key.yaml
  bindata/bootkube/manifests/secret-control-plane-client-signer.yaml
  bindata/bootkube/manifests/secret-kube-apiserver-to-kubelet-signer.yaml
  bindata/bootkube/manifests/secret-loadbalancer-serving-signer.yaml
  bindata/bootkube/manifests/secret-localhost-serving-signer.yaml
  bindata/bootkube/manifests/secret-service-network-serving-signer.yaml
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug

#1403 OCPBUGS-3985: enable pod security admission for techpreview
  bindata/assets/config/defaultconfig.yaml
  go.mod
  go.sum
  pkg/cmd/render/render.go
  pkg/cmd/render/render_test.go
  pkg/operator/configobservation/auth/podsecurityadmission.go
  pkg/operator/configobservation/auth/podsecurityadmission_test.go
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  vendor/github.com/openshift/api/config/install.go
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1alpha1/0000_10_config-operator_01_insightsdatagather.crd.yaml
  vendor/github.com/openshift/api/config/v1alpha1/Makefile
  vendor/github.com/openshift/api/config/v1alpha1/doc.go
  vendor/github.com/openshift/api/config/v1alpha1/register.go
  vendor/github.com/openshift/api/config/v1alpha1/techpreview.insightsdatagather.testsuite.yaml
  vendor/github.com/openshift/api/config/v1alpha1/types_insights.go
  vendor/github.com/openshift/api/config/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/image/v1/generated.pb.go
  vendor/github.com/openshift/api/image/v1/generated.proto
  vendor/github.com/openshift/api/image/v1/types.go
  vendor/github.com/openshift/api/image/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/image/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1beta1/types_gcpprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/observe_featuregates.go
  vendor/github.com/openshift/library-go/pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug

#1430 increase audit log size to contain an entire upgrade+e2e run
  bindata/assets/config/defaultconfig.yaml
Labels: lgtm, approved

#1421 OCPBUGS-5345: routes/status resources can leak sensitive data
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/bindata/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug
