Repository openshift/cluster-kube-apiserver-operator, pull requests merged in 2024-10, with the labels that each got.

#1743 OCPBUGS-42083: Don't rollout revision until three etcd endpoints are listed
  pkg/operator/starter.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#1750 NO-JIRA: Update "deprecated API in use" alert expressions for 1.31.
  bindata/assets/alerts/api-usage.yaml
  go.mod
  go.sum
  pkg/cmd/certregenerationcontroller/cmd.go
  pkg/operator/starter.go
  test/e2e/certrotation_test.go
  test/e2e/operator_test.go
  vendor/github.com/openshift/library-go/pkg/apiserver/jsonpatch/jsonpatch.go
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/manifests/base-policy.yaml
  vendor/github.com/openshift/library-go/pkg/operator/genericoperatorclient/dynamic_operator_client.go
  vendor/github.com/openshift/library-go/pkg/operator/genericoperatorclient/dynamic_staticpod_operator_client.go
  vendor/github.com/openshift/library-go/pkg/operator/genericoperatorclient/test_operator_client.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/monitoring.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/object_merger.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/node/node_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/canonicalize.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/informers.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/test_helpers.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#1738 OCPBUGS-34310: Updating ose-cluster-kube-apiserver-operator-container image to be consistent with ART for 4.17
  Dockerfile.rhel7
Labels: lgtm, approved, cherry-pick-approved, staff-eng-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1758 OCPBUGS-43657: audit: do not log requests to /livez
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/controller/factory/controller_context.go
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/manifests/base-policy.yaml
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/featuregate.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/prune_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissionregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/prune/cmd.go
  vendor/modules.txt
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1756 API-1835: migrate the installer controller to SSA
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/apiserver/jsonpatch/jsonpatch.go
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/admission.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/node/node_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/test_helpers.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference
