Repository openshift/cluster-kube-apiserver-operator, pull requests merged in 2024-12, with the labels that each got.

#1775 OCPBUGS-39575: revert dev cert rotation
  pkg/operator/certrotationcontroller/certrotationcontroller.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#1777 CNTRLPLANE-1: Add resource.k8s.io/v1beta1 API for Kubernetes 1.32
  pkg/operator/configobservation/apienablement/observe_runtime_config.go
  pkg/operator/configobservation/apienablement/observe_runtime_config_test.go
Labels: lgtm, approved, jira/valid-reference

#1776 OCPBUGS-45943: skip generating certs when networkConfig.status.ServiceNetwork is nil
  pkg/operator/certrotationcontroller/servicehostname.go
  pkg/operator/certrotationcontroller/servicehostname_test.go
Labels: lgtm, approved, ok-to-test, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1779 NO-JIRA: bump library-go
  go.mod
  go.sum
  pkg/operator/starter.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/awsplatformstatus.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/nodespec.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/release.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/vspherefailuredomainhostgroup.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/vspherefailuredomainregionaffinity.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/vspherefailuredomainzoneaffinity.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/vsphereplatformfailuredomainspec.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/internal/internal.go
  vendor/github.com/openshift/client-go/operator/applyconfigurations/internal/internal.go
  vendor/github.com/openshift/client-go/operator/applyconfigurations/operator/v1/olm.go
  vendor/github.com/openshift/client-go/operator/applyconfigurations/operator/v1/olmspec.go
  vendor/github.com/openshift/client-go/operator/applyconfigurations/operator/v1/olmstatus.go
  vendor/github.com/openshift/client-go/operator/applyconfigurations/operator/v1/openstackloadbalancerparameters.go
  vendor/github.com/openshift/client-go/operator/applyconfigurations/utils.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_olm.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_operator_client.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/olm.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/operator_client.go
  vendor/github.com/openshift/client-go/operator/informers/externalversions/generic.go
  vendor/github.com/openshift/client-go/operator/informers/externalversions/operator/v1/interface.go
  vendor/github.com/openshift/client-go/operator/informers/externalversions/operator/v1/olm.go
  vendor/github.com/openshift/client-go/operator/listers/operator/v1/expansion_generated.go
  vendor/github.com/openshift/client-go/operator/listers/operator/v1/olm.go
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/controller/auditpolicy/auditpolicy_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/events/recorder.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/node/node_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference
