Repository openshift/cluster-kube-apiserver-operator, pull requests merged in 2024-04, with the labels that each got.

#1661 NO-ISSUE: Revert "certrotationcontroller: set AutoRegenerateAfterOfflineExpiry for generated certificates
  pkg/operator/certrotationcontroller/certrotationcontroller.go
Labels: lgtm, approved, jira/valid-reference

#1659 OCPBUGS-31384: use RotatedSigningCASecret controller in update only mode
  go.mod
  go.sum
  pkg/operator/certrotationcontroller/certrotationcontroller.go
  test/e2e/certrotation_test.go
  vendor/github.com/blang/semver/.travis.yml
  vendor/github.com/blang/semver/LICENSE
  vendor/github.com/blang/semver/README.md
  vendor/github.com/blang/semver/json.go
  vendor/github.com/blang/semver/package.json
  vendor/github.com/blang/semver/range.go
  vendor/github.com/blang/semver/semver.go
  vendor/github.com/blang/semver/sort.go
  vendor/github.com/blang/semver/sql.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/annotations.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/admission.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/modules.txt
Labels: lgtm, approved, jira/severity-critical, jira/valid-bug, jira/valid-reference

#1577 OCPBUGS-22969: Use v1 for flowcontrol API
  manifests/0000_20_kube-apiserver-operator_08_flowschema.yaml
Labels: lgtm, approved, jira/severity-critical, jira/valid-bug, jira/valid-reference

#1662 OCPBUGS-31807: Use RotatedSigningCASecret in update only mode
  go.mod
  go.sum
  pkg/operator/certrotationcontroller/certrotationcontroller.go
  test/e2e/certrotation_test.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller.go
  vendor/modules.txt
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#1611 OCPBUGS-25922: [release-4.13] dashboard: use recording rules for most metrics
  manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml
  manifests/0000_90_kube-apiserver-operator_05_api_performance_dashboard.yaml
Labels: lifecycle/stale, lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1664 WRKLDS-1015: tolerate node-role.kubernetes.io/control-plane:NoExecute
  manifests/0000_20_kube-apiserver-operator_06_deployment.yaml
Labels: lgtm, approved, jira/valid-reference

#1660 OCPEDGE-902: add SNO control plane high cpu usage alert
  bindata/assets/alerts/cpu-utilization-sno.yaml
  pkg/operator/starter.go
  pkg/operator/workloadpartitioning/cpuPartitioningAlertRenderer.go
  vendor/k8s.io/utils/cpuset/OWNERS
  vendor/k8s.io/utils/cpuset/cpuset.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference
