Repository openshift/cluster-kube-apiserver-operator, pull requests merged in 2024-07, with the labels that each got.

#1705 [release-4.16]OCPBUGS-35831: add SNO control plane high cpu usage alert
  bindata/assets/alerts/cpu-utilization-sno.yaml
  bindata/assets/alerts/cpu-utilization.yaml
  pkg/operator/highcpuusagealertcontroller/highcpuusagealert_controller.go
  pkg/operator/highcpuusagealertcontroller/highcpuusagealert_controller_test.go
  pkg/operator/highcpuusagealertcontroller/testdata/alert_2_cores.yaml
  pkg/operator/highcpuusagealertcontroller/testdata/alert_8_cores.yaml
  pkg/operator/starter.go
  vendor/k8s.io/client-go/dynamic/fake/simple.go
  vendor/k8s.io/utils/cpuset/OWNERS
  vendor/k8s.io/utils/cpuset/cpuset.go
  vendor/modules.txt
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1706 [release-4.15]OCPBUGS-35832: add SNO control plane high cpu usage alert
  bindata/assets/alerts/cpu-utilization-sno.yaml
  bindata/assets/alerts/cpu-utilization.yaml
  pkg/operator/highcpuusagealertcontroller/highcpuusagealert_controller.go
  pkg/operator/highcpuusagealertcontroller/highcpuusagealert_controller_test.go
  pkg/operator/highcpuusagealertcontroller/testdata/alert_2_cores.yaml
  pkg/operator/highcpuusagealertcontroller/testdata/alert_8_cores.yaml
  pkg/operator/starter.go
  vendor/k8s.io/client-go/dynamic/fake/simple.go
  vendor/k8s.io/utils/cpuset/OWNERS
  vendor/k8s.io/utils/cpuset/cpuset.go
  vendor/modules.txt
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-low, jira/valid-bug, jira/valid-reference

#1707 [release-4.14]OCPBUGS-31354: add SNO control plane high cpu usage alert
  bindata/assets/alerts/cpu-utilization-sno.yaml
  bindata/assets/alerts/cpu-utilization.yaml
  pkg/operator/highcpuusagealertcontroller/highcpuusagealert_controller.go
  pkg/operator/highcpuusagealertcontroller/highcpuusagealert_controller_test.go
  pkg/operator/highcpuusagealertcontroller/testdata/alert_2_cores.yaml
  pkg/operator/highcpuusagealertcontroller/testdata/alert_8_cores.yaml
  pkg/operator/starter.go
  vendor/k8s.io/client-go/dynamic/fake/simple.go
  vendor/k8s.io/utils/cpuset/OWNERS
  vendor/k8s.io/utils/cpuset/cpuset.go
  vendor/modules.txt
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1686 AUTH-521: add disabled syncer as reason to CFE for PSA
  pkg/operator/podsecurityreadinesscontroller/conditions.go
  pkg/operator/podsecurityreadinesscontroller/conditions_test.go
  pkg/operator/podsecurityreadinesscontroller/podsecurityreadinesscontroller.go
  pkg/operator/podsecurityreadinesscontroller/podsecurityreadinesscontroller_test.go
  pkg/operator/podsecurityreadinesscontroller/violation.go
Labels: lgtm, approved, jira/valid-reference

#1704 NO-JIRA: nodekubeconfigcontroller: set ownership component for node kubeconfigs
  pkg/operator/nodekubeconfigcontroller/nodekubeconfigcontroller.go
  pkg/operator/nodekubeconfigcontroller/nodekubeconfigcontroller_test.go
Labels: lgtm, approved, jira/valid-reference
