Repository openshift/cluster-kube-apiserver-operator, pull requests merged in 2024-05, with the labels that each got.

#1674 NO-ISSUE: Revert "add SNO control plane high cpu usage alert"
  bindata/assets/alerts/cpu-utilization-sno.yaml
  pkg/operator/starter.go
  pkg/operator/workloadpartitioning/cpuPartitioningAlertRenderer.go
  vendor/k8s.io/utils/cpuset/OWNERS
  vendor/k8s.io/utils/cpuset/cpuset.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#1675 OCPBUGS-33522: add a controller that reconciles SCCs' volumes
  bindata/assets/config/config-overrides.yaml
  pkg/operator/sccreconcilecontroller/sccreconcilecontroller.go
  pkg/operator/starter.go
  vendor/github.com/openshift/client-go/security/applyconfigurations/internal/internal.go
  vendor/github.com/openshift/client-go/security/applyconfigurations/security/v1/allowedflexvolume.go
  vendor/github.com/openshift/client-go/security/applyconfigurations/security/v1/fsgroupstrategyoptions.go
  vendor/github.com/openshift/client-go/security/applyconfigurations/security/v1/idrange.go
  vendor/github.com/openshift/client-go/security/applyconfigurations/security/v1/rangeallocation.go
  vendor/github.com/openshift/client-go/security/applyconfigurations/security/v1/runasuserstrategyoptions.go
  vendor/github.com/openshift/client-go/security/applyconfigurations/security/v1/securitycontextconstraints.go
  vendor/github.com/openshift/client-go/security/applyconfigurations/security/v1/selinuxcontextstrategyoptions.go
  vendor/github.com/openshift/client-go/security/applyconfigurations/security/v1/supplementalgroupsstrategyoptions.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/scheme/doc.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/doc.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/podsecuritypolicyreview.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/podsecuritypolicyselfsubjectreview.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/podsecuritypolicysubjectreview.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/rangeallocation.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/security_client.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/securitycontextconstraints.go
  vendor/github.com/openshift/client-go/security/informers/externalversions/factory.go
  vendor/github.com/openshift/client-go/security/informers/externalversions/generic.go
  vendor/github.com/openshift/client-go/security/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/github.com/openshift/client-go/security/informers/externalversions/security/interface.go
  vendor/github.com/openshift/client-go/security/informers/externalversions/security/v1/interface.go
  vendor/github.com/openshift/client-go/security/informers/externalversions/security/v1/rangeallocation.go
  vendor/github.com/openshift/client-go/security/informers/externalversions/security/v1/securitycontextconstraints.go
  vendor/github.com/openshift/client-go/security/listers/security/v1/expansion_generated.go
  vendor/github.com/openshift/client-go/security/listers/security/v1/rangeallocation.go
  vendor/github.com/openshift/client-go/security/listers/security/v1/securitycontextconstraints.go
  vendor/modules.txt
Labels: lgtm, approved, jira/severity-critical, jira/valid-bug, jira/valid-reference

#1679 [4.15] OCPBUGS-33697: add a controller that reconciles SCCs' volumes
  bindata/assets/config/config-overrides.yaml
  pkg/operator/sccreconcilecontroller/sccreconcilecontroller.go
  pkg/operator/starter.go
  vendor/github.com/openshift/client-go/security/applyconfigurations/internal/internal.go
  vendor/github.com/openshift/client-go/security/applyconfigurations/security/v1/allowedflexvolume.go
  vendor/github.com/openshift/client-go/security/applyconfigurations/security/v1/fsgroupstrategyoptions.go
  vendor/github.com/openshift/client-go/security/applyconfigurations/security/v1/idrange.go
  vendor/github.com/openshift/client-go/security/applyconfigurations/security/v1/rangeallocation.go
  vendor/github.com/openshift/client-go/security/applyconfigurations/security/v1/runasuserstrategyoptions.go
  vendor/github.com/openshift/client-go/security/applyconfigurations/security/v1/securitycontextconstraints.go
  vendor/github.com/openshift/client-go/security/applyconfigurations/security/v1/selinuxcontextstrategyoptions.go
  vendor/github.com/openshift/client-go/security/applyconfigurations/security/v1/supplementalgroupsstrategyoptions.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/scheme/doc.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/doc.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/podsecuritypolicyreview.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/podsecuritypolicyselfsubjectreview.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/podsecuritypolicysubjectreview.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/rangeallocation.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/security_client.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/securitycontextconstraints.go
  vendor/github.com/openshift/client-go/security/informers/externalversions/factory.go
  vendor/github.com/openshift/client-go/security/informers/externalversions/generic.go
  vendor/github.com/openshift/client-go/security/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/github.com/openshift/client-go/security/informers/externalversions/security/interface.go
  vendor/github.com/openshift/client-go/security/informers/externalversions/security/v1/interface.go
  vendor/github.com/openshift/client-go/security/informers/externalversions/security/v1/rangeallocation.go
  vendor/github.com/openshift/client-go/security/informers/externalversions/security/v1/securitycontextconstraints.go
  vendor/github.com/openshift/client-go/security/listers/security/v1/expansion_generated.go
  vendor/github.com/openshift/client-go/security/listers/security/v1/rangeallocation.go
  vendor/github.com/openshift/client-go/security/listers/security/v1/securitycontextconstraints.go
  vendor/modules.txt
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#1681 [4.14] OCPBUGS-33930: add a controller that reconciles SCCs' volumes
  bindata/assets/config/config-overrides.yaml
  go.mod
  go.sum
  pkg/operator/sccreconcilecontroller/sccreconcilecontroller.go
  pkg/operator/starter.go
  vendor/github.com/openshift/client-go/security/applyconfigurations/internal/internal.go
  vendor/github.com/openshift/client-go/security/applyconfigurations/security/v1/allowedflexvolume.go
  vendor/github.com/openshift/client-go/security/applyconfigurations/security/v1/fsgroupstrategyoptions.go
  vendor/github.com/openshift/client-go/security/applyconfigurations/security/v1/idrange.go
  vendor/github.com/openshift/client-go/security/applyconfigurations/security/v1/rangeallocation.go
  vendor/github.com/openshift/client-go/security/applyconfigurations/security/v1/runasuserstrategyoptions.go
  vendor/github.com/openshift/client-go/security/applyconfigurations/security/v1/securitycontextconstraints.go
  vendor/github.com/openshift/client-go/security/applyconfigurations/security/v1/selinuxcontextstrategyoptions.go
  vendor/github.com/openshift/client-go/security/applyconfigurations/security/v1/supplementalgroupsstrategyoptions.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/doc.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/scheme/doc.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/doc.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/podsecuritypolicyreview.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/podsecuritypolicyselfsubjectreview.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/podsecuritypolicysubjectreview.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/rangeallocation.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/security_client.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/securitycontextconstraints.go
  vendor/github.com/openshift/client-go/security/informers/externalversions/factory.go
  vendor/github.com/openshift/client-go/security/informers/externalversions/generic.go
  vendor/github.com/openshift/client-go/security/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/github.com/openshift/client-go/security/informers/externalversions/security/interface.go
  vendor/github.com/openshift/client-go/security/informers/externalversions/security/v1/interface.go
  vendor/github.com/openshift/client-go/security/informers/externalversions/security/v1/rangeallocation.go
  vendor/github.com/openshift/client-go/security/informers/externalversions/security/v1/securitycontextconstraints.go
  vendor/github.com/openshift/client-go/security/listers/security/v1/expansion_generated.go
  vendor/github.com/openshift/client-go/security/listers/security/v1/rangeallocation.go
  vendor/github.com/openshift/client-go/security/listers/security/v1/securitycontextconstraints.go
  vendor/modules.txt
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#1677 OCPBUGS-34062: [4.13] add a controller that reconciles SCCs' volumes
  go.mod
  go.sum
  pkg/operator/sccreconcilecontroller/sccreconcilecontroller.go
  pkg/operator/starter.go
  vendor/github.com/openshift/client-go/security/applyconfigurations/internal/internal.go
  vendor/github.com/openshift/client-go/security/applyconfigurations/security/v1/allowedflexvolume.go
  vendor/github.com/openshift/client-go/security/applyconfigurations/security/v1/fsgroupstrategyoptions.go
  vendor/github.com/openshift/client-go/security/applyconfigurations/security/v1/idrange.go
  vendor/github.com/openshift/client-go/security/applyconfigurations/security/v1/rangeallocation.go
  vendor/github.com/openshift/client-go/security/applyconfigurations/security/v1/runasuserstrategyoptions.go
  vendor/github.com/openshift/client-go/security/applyconfigurations/security/v1/securitycontextconstraints.go
  vendor/github.com/openshift/client-go/security/applyconfigurations/security/v1/selinuxcontextstrategyoptions.go
  vendor/github.com/openshift/client-go/security/applyconfigurations/security/v1/supplementalgroupsstrategyoptions.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/doc.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/scheme/doc.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/doc.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/podsecuritypolicyreview.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/podsecuritypolicyselfsubjectreview.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/podsecuritypolicysubjectreview.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/rangeallocation.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/security_client.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/securitycontextconstraints.go
  vendor/github.com/openshift/client-go/security/informers/externalversions/factory.go
  vendor/github.com/openshift/client-go/security/informers/externalversions/generic.go
  vendor/github.com/openshift/client-go/security/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/github.com/openshift/client-go/security/informers/externalversions/security/interface.go
  vendor/github.com/openshift/client-go/security/informers/externalversions/security/v1/interface.go
  vendor/github.com/openshift/client-go/security/informers/externalversions/security/v1/rangeallocation.go
  vendor/github.com/openshift/client-go/security/informers/externalversions/security/v1/securitycontextconstraints.go
  vendor/github.com/openshift/client-go/security/listers/security/v1/expansion_generated.go
  vendor/github.com/openshift/client-go/security/listers/security/v1/rangeallocation.go
  vendor/github.com/openshift/client-go/security/listers/security/v1/securitycontextconstraints.go
  vendor/modules.txt
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#1689 OCPBUGS-33963: Create one-shot migrations for the flowcontrol group.
  bindata/assets/kube-apiserver/storage-version-migration-flowschema-v1beta3.yaml
  bindata/assets/kube-apiserver/storage-version-migration-prioritylevelconfiguration-v1beta3.yaml
  pkg/operator/starter.go
Labels: lgtm, approved, jira/severity-critical, jira/valid-bug, jira/valid-reference
