Repository openshift/cluster-kube-apiserver-operator, pull requests merged in 2024-09, with the labels that each got.

#1729 OCPBUGS-34679: revert dev cert rotation 4.17
  pkg/operator/certrotationcontroller/certrotationcontroller.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#1731 OCPBUGS-41257: introduce --operand-kubernetes-version flag and resolve API group versions accordingly
  pkg/cmd/render/render.go
  pkg/operator/configobservation/apienablement/observe_runtime_config.go
  pkg/operator/configobservation/apienablement/observe_runtime_config_test.go
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/starter.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1735 create CRDs from openshift/api
  Dockerfile.rhel7
Labels: approved

#1665 NO-JIRA: Re-apply "certrotationcontroller: set AutoRegenerateAfterOfflineExpiry for generated certificates"
  pkg/operator/certrotationcontroller/certrotationcontroller.go
Labels: lgtm, approved, jira/valid-reference

#1736 WRKLDS-1449: cleanup flag validation after they have been added to the installer
  pkg/cmd/render/render.go
  pkg/cmd/render/render_test.go
Labels: lgtm, approved, jira/valid-reference
