Repository openshift/cluster-kube-apiserver-operator, pull requests merged in 2024-06, with the labels that each got.

#1695 OCPBUGS-25104: revert dev cert rotation 4.16
  pkg/operator/certrotationcontroller/certrotationcontroller.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#1697 OCPBUGS-34800: Update APIRemovedInNextReleaseInUse for kube 1.30 / ocp 4.17
  bindata/assets/alerts/api-usage.yaml
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1693 OCPBUGS-34544: Disable PersistentVolumeLabel admission plugin
  bindata/assets/config/defaultconfig.yaml
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1694 OCPBUGS-34782: manifests: add ownership annotation for kubelet-bootstrap-kubeconfig
  bindata/bootkube/manifests/configmap-kubelet-bootstrap-kubeconfig-ca.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1676 OCPEDGE-902: add SNO control plane high cpu usage alert
  bindata/assets/alerts/cpu-utilization-sno.yaml
  pkg/operator/highcpuusagealertcontroller/highcpuusagealert_controller.go
  pkg/operator/highcpuusagealertcontroller/highcpuusagealert_controller_test.go
  pkg/operator/highcpuusagealertcontroller/testdata/alert_2_cores.yaml
  pkg/operator/highcpuusagealertcontroller/testdata/alert_8_cores.yaml
  pkg/operator/starter.go
  vendor/k8s.io/utils/cpuset/OWNERS
  vendor/k8s.io/utils/cpuset/cpuset.go
  vendor/modules.txt
Labels: lgtm, approved, qe-approved, jira/valid-reference

#1680 OCPEDGE-1102: Revert high cpu usage alert description
  bindata/assets/alerts/cpu-utilization.yaml
Labels: lgtm, approved, jira/valid-reference
