Repository openshift/cluster-kube-apiserver-operator, pull requests merged in 2024-01, with the labels that each got.

#1512 OCPBUGS-14496: manifests: fix the scope of the TechPreviewNoUpgrade alert
  manifests/0000_90_kube-apiserver-operator_03_servicemonitor.yaml
Labels: lgtm, approved, qe-approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#1619 OCPBUGS-21846: sync(library-go): revision_controller: update last revision only when a revision is completely rendered
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1621 NO-ISSUE: prevent update status conflicts
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/genericoperatorclient/dynamic_operator_client.go
  vendor/github.com/openshift/library-go/pkg/operator/genericoperatorclient/dynamic_staticpod_operator_client.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissionregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiextensions.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apps.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/migration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/monitoring.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/policy.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/rbac.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/volumesnapshotclass.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/test_helpers.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#1546 OCPBUGS-18939: manifest: drop slo latency metrics in favor of sli
  bindata/assets/alerts/kube-apiserver-slos-basic.yaml
  bindata/assets/alerts/kube-apiserver-slos-extended.yaml
  manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference

#1584 NO-JIRA: Add ownership for the admin kubeconfig
  bindata/bootkube/manifests/configmap-admin-kubeconfig-client-ca.yaml
Labels: lgtm, approved, jira/valid-reference

#1632 OCPBUGS-24005: when skipping a webhook check because of missing CA log the name of the webhook
  pkg/operator/webhooksupportabilitycontroller/degraded_webhook.go
  pkg/operator/webhooksupportabilitycontroller/degraded_webhook_admission_test.go
  pkg/operator/webhooksupportabilitycontroller/degraded_webhook_conversion_test.go
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference
