Repository openshift/cluster-kube-apiserver-operator, pull requests merged in 2025-07, with the labels that each got.

#1865 OCPBUGS-57811: Updating ose-cluster-kube-apiserver-operator-container image to be consistent with ART for 4.20
  .ci-operator.yaml
  Dockerfile.rhel7
  go.mod
  pkg/operator/kubeletversionskewcontroller/kubelet_version_skew_controller_test.go
  test/e2e/serviceaccountissuer_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1867 Revert "[release-4.19] OCPBUGS-58116: certregenerationcontroller: start configInformers again"
  pkg/cmd/certregenerationcontroller/cmd.go
Labels: lgtm, approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#1871 NO-JIRA: Update the deprecated API usage alerts for 1.33.
  bindata/assets/alerts/api-usage.yaml
Labels: lgtm, approved, jira/valid-reference

#1866 OCPBUGS-58232: Don't wait for 2 etcd members when the cluster is TNF installed with assisted-installer
  pkg/operator/starter.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1875 OCPBUGS-50489: Add missing service ports to apiserver service
  bindata/assets/kube-apiserver/svc.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1873 OCPBUGS-44842: Set not-before/not-after annotations
  go.mod
  go.sum
  pkg/operator/nodekubeconfigcontroller/nodekubeconfigcontroller.go
  pkg/operator/nodekubeconfigcontroller/nodekubeconfigcontroller_test.go
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/annotations.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/metadata.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/core.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1882 NO-JIRA: Add negative tests of GOAWAY-chance
  pkg/operator/configobservation/apiserver/observe_goaway_chance_test.go
Labels: lgtm, approved, jira/valid-reference
