Repository openshift/cluster-kube-apiserver-operator, pull requests merged in 2025-06, with the labels that each got.

#1854 NO-JIRA: Enable MutatingAdmissionPolicy group version
  pkg/operator/configobservation/apienablement/observe_runtime_config.go
Labels: lgtm, approved, jira/valid-reference

#1856 NO-JIRA: remove unused yaml
  manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml
  manifests/0000_90_kube-apiserver-operator_05_api_performance_dashboard.yaml
Labels: lgtm, approved, ok-to-test, jira/valid-reference

#1810 CNTRLPLANE-79: Disable oauth admission plugins
  bindata/assets/config/defaultconfig.yaml
  pkg/operator/configobservation/apiserver/observe_admission_plugins.go
  pkg/operator/configobservation/apiserver/observe_admission_plugins_test.go
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
Labels: lgtm, approved, jira/valid-reference

#1836 OCPBUGS-55465: Stop serving admissionregistration.k8s.io/v1beta1.
  pkg/operator/configobservation/apienablement/observe_runtime_config.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1853 OCPBUGS-56551: certregenerationcontroller: start configInformers again
  pkg/cmd/certregenerationcontroller/cmd.go
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#1846 NO-JIRA: Enable watch termination grace period
  bindata/assets/config/defaultconfig.yaml
Labels: lgtm, approved, jira/valid-reference

#1862 OCPBUGS-58158: Enable watch termination grace period
  bindata/assets/config/defaultconfig.yaml
Labels: lgtm, approved, jira/severity-critical, jira/valid-bug, jira/valid-reference
