Repository openshift/cluster-kube-apiserver-operator, pull requests merged in 2025-02, with the labels that each got.

#1794 NO-JIRA: alerts: update APIRemovedInNextEUSReleaseInUse for 1.32
  bindata/assets/alerts/api-usage.yaml
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#1784 MON-4129: adjust Prometheus classic histograms 'le' related selectors in rules defs and relabel config to accommodate the update to Prometheus v3
  bindata/assets/alerts/kube-apiserver-slos-basic.yaml
  bindata/assets/alerts/kube-apiserver-slos-extended.yaml
  manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#1795 OCPBUGS-48686: bump(library-go)
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1796 OCPBUGS-49773: Bump library-go for static pod controller apply fixes.
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/node/observe_minimum_kubelet_version.go
  vendor/github.com/openshift/library-go/pkg/operator/events/recorder.go
  vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/node/node_controller.go
  vendor/modules.txt
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1744 OCPBUGS-49764: bindata/alerts/slo: improve burnrate calculation
  bindata/assets/alerts/kube-apiserver-slos-basic.yaml
  bindata/assets/alerts/kube-apiserver-slos-extended.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1789 OCPQE-28167: Increase waitForFallbackDegradedConditionTimeout
  test/e2e-sno-disruptive/sno_disruptive_test.go
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#1742 OCPBUGS-49763: Disregard health endpoints in the burn rate alerts
  bindata/assets/alerts/kube-apiserver-slos-basic.yaml
  bindata/assets/alerts/kube-apiserver-slos-extended.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1804 OCPBUGS-49980: change one sum:apiserver_request:burnrate5m to sum:apiserver_request:burnrate6h
  bindata/assets/alerts/kube-apiserver-slos-basic.yaml
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1763 API-1689: TLS registry: add description
  bindata/assets/kube-apiserver/trusted-ca-cm.yaml
  bindata/bootkube/manifests/configmap-admin-kubeconfig-client-ca.yaml
  bindata/bootkube/manifests/configmap-csr-controller-ca.yaml
  bindata/bootkube/manifests/secret-aggregator-client-signer.yaml
  bindata/bootkube/manifests/secret-control-plane-client-signer.yaml
  bindata/bootkube/manifests/secret-kube-apiserver-to-kubelet-signer.yaml
  bindata/bootkube/manifests/secret-loadbalancer-serving-signer.yaml
  bindata/bootkube/manifests/secret-localhost-serving-signer.yaml
  bindata/bootkube/manifests/secret-service-network-serving-signer.yaml
  pkg/operator/certrotationcontroller/certrotationcontroller.go
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#1809 [release-4.13]OCPBUGS-50850:Increase waitForFallbackDegradedConditionTimeout
  test/e2e-sno-disruptive/sno_disruptive_test.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1792 OCPBUGS-48673: targetconfigcontroller: check live etcd endpoints
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1814 NO-ISSUE: Bump TraceAll log level to v=10
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: lgtm, approved, ok-to-test, jira/valid-reference

#1817 MON-4129: revert https://github.com/openshift/cluster-kube-apiserver-operator/pull/1784
  bindata/assets/alerts/kube-apiserver-slos-basic.yaml
  bindata/assets/alerts/kube-apiserver-slos-extended.yaml
Labels: lgtm, approved, jira/valid-reference

#1815 MON-4129: slos: accomodate for Prometheus v3 "le" normalization
  bindata/assets/alerts/kube-apiserver-slos-basic.yaml
  bindata/assets/alerts/kube-apiserver-slos-extended.yaml
Labels: lgtm, approved, jira/valid-reference

#1754 OCPNODE-2940: add support for minimumKubeletVersion
  bindata/assets/config/defaultconfig.yaml
  pkg/cmd/render/render.go
  pkg/cmd/render/render_test.go
  pkg/cmd/render/testdata/rendered/default-fg/featuregate.yaml
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/configobservation/node/observe_authorization_mode.go
  pkg/operator/configobservation/node/observe_authorization_mode_test.go
  pkg/operator/configobservation/node/observe_minimum_kubelet_version.go
  pkg/operator/configobservation/node/observe_minimum_kubelet_version_test.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: lgtm, approved, jira/valid-reference

#1760 AUTH-541: OIDC structured auth config
  pkg/operator/configobservation/auth/auth_metadata.go
  pkg/operator/configobservation/auth/auth_metadata_test.go
  pkg/operator/configobservation/auth/external_oidc.go
  pkg/operator/configobservation/auth/external_oidc_test.go
  pkg/operator/configobservation/auth/webhook_authenticator.go
  pkg/operator/configobservation/auth/webhook_authenticator_test.go
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/starter.go
Labels: lgtm, approved, qe-approved, jira/valid-reference, acknowledge-critical-fixes-only
