Repository openshift/cluster-kube-apiserver-operator, pull requests merged in 2025-08, with the labels that each got.

#1847 OCPNODE-2559: SCC: add nested-podman and restricted-v3
  bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_cr-scc-nested-container.yaml
  bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_cr-scc-restricted-v3.yaml
  bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_scc-nested-container.yaml
  bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_scc-restricted-v3.yaml
Labels: lgtm, approved, jira/valid-reference

#1872 OCPBUGS-59527: certrotationcontroller: extend node-system-admin-signer lifetime
  pkg/operator/certrotationcontroller/certrotationcontroller.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1812 OCPBUGS-55217: Optimistically update Kube Server and Client CA bundles
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1864 RFE-4153: enabled readonly filesystem
  bindata/assets/kube-apiserver/pod.yaml
  manifests/0000_20_kube-apiserver-operator_06_deployment.yaml
Labels: lgtm, approved, jira/valid-reference

#1907 Revert "OCPBUGS-57049: certrotation: move test case name outside of AutoRegenerateAfterOfflineExpiry"
  pkg/operator/certrotationcontroller/certrotationcontroller.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1887 OCPBUGS-60121: [release-4.19] Set goaway chance to 0.001
  bindata/assets/config/defaultconfig.yaml
  pkg/cmd/render/render.go
  pkg/operator/configobservation/apiserver/observe_goaway_chance.go
  pkg/operator/configobservation/apiserver/observe_goaway_chance_test.go
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
Labels: lgtm, approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference
