Repository openshift/cluster-kube-apiserver-operator, pull requests merged in 2025-03, with the labels that each got.

#1820 NO-JIRA: readme: describe mapping between operatorLogLevel and log level
  README.md
Labels: lgtm, approved, ok-to-test, jira/valid-reference

#1824 OCPBUGS-35102: Bump library-go
  go.mod
  go.sum
  vendor/github.com/evanphx/json-patch/.gitignore
  vendor/github.com/evanphx/json-patch/LICENSE
  vendor/github.com/evanphx/json-patch/README.md
  vendor/github.com/evanphx/json-patch/errors.go
  vendor/github.com/evanphx/json-patch/merge.go
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/annotations.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/json_patch_helpers.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/apiregistration.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1827 MON-4160: operator: add topology metrics
  pkg/operator/configmetrics/configmetrics.go
Labels: lgtm, approved, jira/valid-reference
